### ISSUE TITLE
Does Delete button function as Remove button for channels where user is noncreator?

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#101]
Screenshot Example

![delete_channel_not_created_by_user](https://user-images.githubusercontent.com/11938477/39478914-b73aff8c-4d31-11e8-8975-0ab0cb50f433.jpg)

**Comment by bluenevus** [comment]
Only if you were given permission.  Until the permissions are worked out..we are going to see things we shouldn’t and not see things we should.  Bilel is working the permissions in

https://github.com/MicroHealthLLC/mRMS/issues/22

which should resolve this
--- Vr Frank
