### ISSUE TITLE
Separate the document name/download icon links/functions

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#107]
1. Move the download button after the document name and put more white space between the name and the download icon.
2. Separate the click functions so that clicking the document name will display the default pivot table, and clicking the download icon will download the document (as it does now).

Screenshot Example

![separate_document_name_download_functions](https://user-images.githubusercontent.com/11938477/39531081-68335a2a-4df8-11e8-8edb-56bb716f48b8.jpg)

**Comment by bluenevus** [comment]
I agree with number 1

But number 2 should probably be a button that says clear reports to get a blank slate if that is what you are looking for.  Having 2 links there would be confusing.  Those buttons should be on the button bar at the top with the other buttons


--- Vr Frank

**Comment by LAlexMHllc** [comment]
I do not want the other reports to be cleared, just make it easier to create a different report without having to either: click Cancel, then click report name from table to view default pivot table OR to click through the other saved reports until something displays similar enough to modify.

**Comment by bluenevus** [comment]
That is what I’m talking about clearing all the presets back to the default so you can create a different report.  Its clearing filters or clearing the pivot so you can create a new pivot

--- Vr Frank

**Comment by LAlexMHllc** [comment]
OK. I'll separate this issue into two separate issues the close this issue.
