### ISSUE TITLE
Include a Clear button on top bar of Report screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#108]
Remove the download icon/function from document name and include a Download button on the top bar with the other buttons

**Comment by bluenevus** [comment]
Well it’s the other way around.

The download at the document is just fine.  However at the top they can have a “Clear” button that clears the filters for a new report creation

--- Vr Frank

**Comment by LAlexMHllc** [comment]
ok. will fix
