### ISSUE TITLE
print is not fitting on the page even if you change the orientation

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#131]
![image](https://user-images.githubusercontent.com/3675043/40321749-14b830f4-5cfe-11e8-93f6-55e39930c8bc.png)

![image](https://user-images.githubusercontent.com/3675043/40321762-1d129adc-5cfe-11e8-8afd-0d65952c770e.png)

**Comment by bluenevus** [comment]
should we default the scale to 50% to fit and landscape?

**Comment by bilel-kedidi** [comment]
i did export to EXCEL, you could check that

**Comment by bilel-kedidi** [comment]
pdf is disabled now, excel is working fine
