### ISSUE TITLE
I'm unable to see more than 6 users on this list, can't scroll and can't type to search

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#135]
![image](https://user-images.githubusercontent.com/3675043/41120235-e6acbfbe-6a62-11e8-85ce-84fe40ce7da8.png)

**Comment by bilel-kedidi** [comment]
![screenshot from 2018-06-08 09-58-14](https://user-images.githubusercontent.com/5988861/41149066-807c9d5e-6b02-11e8-88f4-33f6aa9d7940.png)

**Comment by bluenevus** [comment]
create a new channel and try permissions.  you will see there is a limit

also try to type in the search...doesn't work.

**Comment by bluenevus** [comment]
I added you to proposal channel.  you will see there, there is a limit and that is the latest created channel

also seach doesn't work in the box
