### ISSUE TITLE
when uploading a spreadsheet, any field that is multiline like string causes issues

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#136]
when uploading a spreadsheet, any field that is multiline like string causes issues

text is fine even though I know that is a string but when that is multiline text field type or an object, it fails to load.  Right now, we simply delete that column then load but is there any way to ignore that column so we can load the fields that do work and ignore the ones that don't so people can simply upload the spreadsheet and pivot the fields that work?

**Comment by bilel-kedidi** [comment]
COULD YOU SEND ME CSV EXAMPLE FOR THIS.

**Comment by bluenevus** [comment]
example here.  it will fail to load in the pivot because of the multiline text field in the column "Description of Requirement"  that goes with any spreadsheet.  so it take some prep work when I just want that field ignored so they can upload it as is.


[hhs-fy2016-sci-supplemental-data2.zip](https://github.com/MicroHealthLLC/mRMS/files/2137253/hhs-fy2016-sci-supplemental-data2.zip)
