### ISSUE TITLE
eserializationError: Error while trying to deserialize arguments: could not obtain a connection from the pool within 5.000 seconds 

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#140]
ActiveJob::DeserializationError: Error while trying to deserialize arguments: could not obtain a connection from the pool within 5.000 seconds (waited 5.001 seconds); all pooled connections were in use
Traceback
ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.001 seconds); all pooled connections were in use

**Comment by bilel-kedidi** [comment]
try to add pool: 30 to config/database.yml
