### ISSUE TITLE
new report button missing in menu even though user has permission to add new report

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#154]
new report missing in menu even though user has permission to add new report

**Comment by bluenevus** [comment]
![image](https://user-images.githubusercontent.com/3675043/43414440-b8b2aa52-9400-11e8-98ac-81579e535d29.png)

MISSING THE NEW REPORT BUTTON
![image](https://user-images.githubusercontent.com/3675043/43414455-c59dba72-9400-11e8-9d00-813bd9178e35.png)

**Comment by bluenevus** [comment]
the update button is also missing on existing reports so they don't have permissions to add edit even though it was checked.

**Comment by bilel-kedidi** [comment]
is it fixed?
