### ISSUE TITLE
Shared Reports Channel screen - clicking file on Data Sets table displays error screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#155]
Screenshot Example

![file_under_shared_report_click_displays_error_screen](https://user-images.githubusercontent.com/11938477/44592280-1ab40480-a78e-11e8-95f4-8649e6b39e75.jpg)

**Comment by bilel-kedidi** [comment]
added new permission called can view report, should be checked to see the report
