### ISSUE TITLE
If a user is unable to download a file, then why is Upload Data button displayed/functioning?

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#156]
When the Upload Data button is displayed/functions, a user should be able to download the file so it can be modified, then uploaded.
OR
The Upload Data button should not be displayed for users without permission to download the file.

Screenshot Example

![upload_data_btn_without_download_button](https://user-images.githubusercontent.com/11938477/44596228-720ba200-a799-11e8-827d-3e26ce07e43c.jpg)

**Comment by bilel-kedidi** [comment]
Hi,
Upload Data is meant to upload document file or update it
User can add document is the channel is public ot he did create that channel or he has permission to add  reports

**Comment by LAlexMHllc** [comment]
Should a user be able to download the file so it can be modified, then uploaded? If yes, then download function needs to be included.

Screenshot Example

![include_download_function](https://user-images.githubusercontent.com/11938477/45162698-96657680-b1bc-11e8-9cf1-039117d8f80c.jpg)
