### ISSUE TITLE
Fix "Back" button on channel screen to avoid Page does not exist screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#193]
Example Screenshot

![channel_back_btn_page_does_not_exist](https://user-images.githubusercontent.com/11938477/47101057-0a0c9180-d207-11e8-80b4-cbdce8fda6e2.jpg)

**Comment by bluenevus** [comment]
Well we don’t want to remove the back button.  We want to fix it.

Vr Frank

--- vr, Frank
