### ISSUE TITLE
Spreadsheet does not display for report after file upload - option may be using novixpivotjs plugin to directly edit data on pivottables.js

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#2]

**Comment by bluenevus** [comment]
The solution to this may be to simply allow direct entry into the data using
**https://github.com/fbrussa/NovixPivotJS**

Looks like it solves the issue and we don't necessarily need to have a spreadsheet at the bottom because the data can be edited directly.
