### ISSUE TITLE
Edit Channel form Options should not be changed except FROM Personal TO Groups or Public

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#206]
Screenshot Example

![edit_channel_options](https://user-images.githubusercontent.com/11938477/47657876-52617300-db68-11e8-8c20-f11e400b9323.jpg)

**Comment by bluenevus** [comment]
They probably need to be able to change it because if they have a ton of data they did in personal…they may want to now make it as a group without recreating the whole thing

We want flexibility for the user


--- vr, Frank

**Comment by LAlexMHllc** [comment]
Will test Personal to Group and Personal to Public. The tests from Group to Public and Public to Group caused issues. Procedures will need to be put in place before allowing a user to switch channel types.
