### ISSUE TITLE
Error Screen displays after clicking Change My Password email link

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#207]
Screenshot Example from Firefox

![change_my_password_from_email_link](https://user-images.githubusercontent.com/11938477/47662490-678ecf80-db71-11e8-83ec-8f50ed5b50b6.jpg)

**Comment by LAlexMHllc** [comment]
Screenshot Example from Chrome

![change_my_password_from_email_link_chrome](https://user-images.githubusercontent.com/11938477/47663212-e0daf200-db72-11e8-96f4-6c6404523763.jpg)

**Comment by bilel-kedidi** [comment]
is this still happen?

**Comment by bilel-kedidi** [comment]
@bluenevus

**Comment by bluenevus** [comment]
no
