### ISSUE TITLE
ActionView::Template::Error: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#211]
Message
ActionView::Template::Error: invalid byte sequence in UTF-8
URL
https://mrms.microhealthllc.com/channels/23/reports/73?query_id=110
Traceback
CSV::MalformedCSVError: Unquoted fields do not allow \r or \n (line 29).

**Comment by bilel-kedidi** [comment]
@bluenevus need the file that cause that issue

**Comment by bluenevus** [comment]
I k ow what this is..commas in the field

On Fri, Mar 1, 2019, 12:00 PM bilel-kedidi <notifications@github.com> wrote:

> @bluenevus
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbluenevus&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C9d191cb8bf1447988ce908d69e67792a%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636870564595335334&sdata=2jqQqrAh15YsO8X9I%2F8aoEJcGxvbJj6ELKLLt0JFWec%3D&reserved=0>
> need the file that cause that issue
>
> ?
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmRMS%2Fissues%2F211%23issuecomment-468735218&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C9d191cb8bf1447988ce908d69e67792a%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636870564595335334&sdata=AgfsYshYzAgYu64JeuaunmhRjwQPUmgpllz%2FF1b3eUE%3D&reserved=0>,
> or mute the thread
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADgTo0i7hMr6XLShEaUSx3z8n7qN6Gc9ks5vSVzHgaJpZM4ZQdWf&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C9d191cb8bf1447988ce908d69e67792a%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C0%7C636870564595345348&sdata=R8AGDjbE%2FlF7pYvY5WGSqyxh8YGpE%2Fl20k0jDmYG3wk%3D&reserved=0>
> .
>

-- 

Please consider environment before printing this email

_If you are not 
the intended recipient you are notified that disclosing, copying, 
distributing or taking any action in reliance on the contents of this 
information is strictly prohibited.  __Please notify the sender immediately 
by e-mail and delete this e-mail from your system.  Thank You_
*
*
