### ISSUE TITLE
Update image links

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#235]
Screenshot Examples of broken image links

![broken_image_links](https://user-images.githubusercontent.com/11938477/52724060-a445d180-2f7c-11e9-9f4c-0fb1fa39c62f.jpg)

**Comment by LAlexMHllc** [comment]
Sidebar menu - DONE
News - NOT DONE

**Comment by LAlexMHllc** [comment]
Still need to fix admin avatar

**Comment by bilel-kedidi** [comment]
they should

**Comment by bluenevus** [comment]
This is from moving servers

On Fri, Mar 1, 2019, 11:57 AM bilel-kedidi <notifications@github.com> wrote:

> they should
>
> ?
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmRMS%2Fissues%2F235%23issuecomment-468734186&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C8bd0a57977e7497c199008d69e6709b2%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C1%7C636870562727315703&sdata=PRXt%2FrdP1iPeFj3KF3%2Fagk59CwR65F5OT5hgweZWCq0%3D&reserved=0>,
> or mute the thread
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADgTo1qv0OQ9hkKrarpWyukB8b12zYlaks5vSVwNgaJpZM4aPJBI&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C8bd0a57977e7497c199008d69e6709b2%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C1%7C636870562727325712&sdata=k2RPCJ7oDf%2BVHT7rlYDzCGLqw4iwmaKTCaRbbziO%2FIo%3D&reserved=0>
> .
>

-- 

Please consider environment before printing this email

_If you are not 
the intended recipient you are notified that disclosing, copying, 
distributing or taking any action in reliance on the contents of this 
information is strictly prohibited.  __Please notify the sender immediately 
by e-mail and delete this e-mail from your system.  Thank You_
*
*
