### ISSUE TITLE
Fix file links so error message does not display

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#237]
Screenshot Example of issue

![report_file_links](https://user-images.githubusercontent.com/11938477/51621584-d8405080-1f02-11e9-8180-51abca585a16.jpg)

**Comment by bluenevus** [comment]
This is working as designed.  Its literally missing the files which need to be reuploaded because the server was moved.

--- vr, Frank

**Comment by bilel-kedidi** [comment]
@bluenevus  did you manage to move all files?

**Comment by bluenevus** [comment]
Never mind this.  They all have to reupload their data.  We moved servers

On Fri, Mar 1, 2019, 12:00 PM bilel-kedidi <notifications@github.com> wrote:

> @bluenevus
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbluenevus&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C9c61d0e31a7246aace9708d69e675d76%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C1%7C636870564117035913&sdata=a5e2VlfLRvL1oIedRKzmW9Tyf8zIcAaKCxLjRNHrvYM%3D&reserved=0>
> did you manage to move all files?
>
> ?
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicroHealthLLC%2FmRMS%2Fissues%2F237%23issuecomment-468734952&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C9c61d0e31a7246aace9708d69e675d76%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C1%7C636870564117045917&sdata=dpV6qW0vP%2BVMLConrlAAA3r3aHztGDbxHhm2S5TiC8o%3D&reserved=0>,
> or mute the thread
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADgTo-pSuBwT6N44Hhm2AZuaOdIadelKks5vSVyZgaJpZM4aPKcL&data=02%7C01%7Cfrank.tucker%40microhealthllc.com%7C9c61d0e31a7246aace9708d69e675d76%7C487ea2d67ea04a4b87736f4833ed2108%7C0%7C1%7C636870564117045917&sdata=%2BiQKsSLeBX63qvdqJwD5hHCXM9QJdWcBZudrdK8ZZIg%3D&reserved=0>
> .
>

-- 

Please consider environment before printing this email

_If you are not 
the intended recipient you are notified that disclosing, copying, 
distributing or taking any action in reliance on the contents of this 
information is strictly prohibited.  __Please notify the sender immediately 
by e-mail and delete this e-mail from your system.  Thank You_
*
*
