### ISSUE TITLE
Error rendering PivotTable UI for .xlxs file after "Upload a file", but not URL

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#256]
Screenshot Example

![error_rendering_pivottable_ui_for_xlxs](https://user-images.githubusercontent.com/11938477/55238797-bcf80700-520b-11e9-8d1e-9d084b49127a.jpg)

**Comment by bilel-kedidi** [comment]
Could u send me that fille

Le ven. 29 mars 2019 à 15:17, LAlexMHllc <notifications@github.com> a
écrit :
