### ISSUE TITLE
new feature to allow users to leave a channel or request being added to a list of channels

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#276]
new feature to allow users to leave a channel or request being added to a list of channels

the channel administrator can then accept the invite with some notification on his channel screen and notification that someone left on their channel screen or channel info screen or something like that

**Comment by bilel-kedidi** [comment]
Added notification on left channel.
my question is how user can add request to channel if he cannot view it

**Comment by bluenevus** [comment]
Yeah...in microsoft teams they do with a team code.  Alternatively you can show them a list of channel names to send a request to that channel admin through notifications in the app



--
Dr. Frank Tucker
CEO
MicroHealth, LLC
People * Value * Innovation

O: (855) 294-3547 |  F: (855)-850-1264
Address:  8229 Boone Blvd, Suite 500  |  Vienna, VA 22182
<http://www.microhealthonline.com/>Email: frank.tucker@microhealthllc.com<mailto:frank.tucker@microhealthllc.com>
www.microhealthllc.com<http://www.microhealthllc.com/>

________________________________
