### ISSUE TITLE
the first user is always blank on every channel

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#282]
the first user is always blank on every channel

![image](https://user-images.githubusercontent.com/3675043/55484916-5ef66580-55f7-11e9-9302-f4287802dc66.png)

**Comment by bilel-kedidi** [comment]
i think the user has no name!!! added email if it's blank

**Comment by bluenevus** [comment]
We have no users without a name.

 

I do have users that I deactivated.  If they are deactivated, they should have their permissions in each channel revoked.  I think that is a person deactivated

 

Alternatively it could be me but I definitely have a name 😊  There is only 2 people that have access to this many channels, me and the person that I deactivated

 

--- vr, Frank

**Comment by bluenevus** [comment]
I'm almost positive its my as the logged in user
