### ISSUE TITLE
the news feed no longer shows on this page on the right but there is news

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#290]
![image](https://user-images.githubusercontent.com/3675043/55503816-6fb9d200-561d-11e9-8209-63664988218a.png)

**Comment by bluenevus** [comment]
home page that is

**Comment by bilel-kedidi** [comment]
try to set the news number on setting page

**Comment by bluenevus** [comment]
Right!!!

 

--- vr, Frank
