### ISSUE TITLE
Its missing the settings configuration page

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#332]
![image](https://user-images.githubusercontent.com/3675043/114404350-9e0b0a00-9b73-11eb-95a7-fc56c16b317e.png)

content page is missing that placed information on the landing page

module page that turns on and off features

authentication that puts rules on it

![image](https://user-images.githubusercontent.com/3675043/114404507-bf6bf600-9b73-11eb-9f69-b9b323b5d9bb.png)

keys to configure it in the ui

![image](https://user-images.githubusercontent.com/3675043/114404556-cb57b800-9b73-11eb-9abe-cc49d3ce21b7.png)

**Comment by LAlexMHllc** [comment]
Closing, Settings screen included
