### ISSUE TITLE
the social login doesn't work, doesn't show

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#335]
![image](https://user-images.githubusercontent.com/3675043/114405285-88e2ab00-9b74-11eb-98bb-4b1c1476ae58.png)

**Comment by bluenevus** [comment]
it shows but there is no way to configure it in admin this is missing and the admin access is missing

![image](https://user-images.githubusercontent.com/3675043/117467747-f985a900-af21-11eb-84fc-17cf5c8ff445.png)

**Comment by LAlexMHllc** [comment]
Social Login links display on the Sign In screen - DONE
Screenshot Example

![sign_in_social_login_links_display](https://user-images.githubusercontent.com/11938477/119014966-7a06c980-b966-11eb-9141-e5ebb19c5c79.png)

But Sign Ins - NEED TO BE FIXED

Screenshot Example with GitHub Sign In

![social_login_github_screen](https://user-images.githubusercontent.com/11938477/119015990-6e67d280-b967-11eb-9f51-cd0130cca10b.png)

Screenshot Example with Microsoft

![social_login_microsoft_screen](https://user-images.githubusercontent.com/11938477/119016091-8ccdce00-b967-11eb-9301-2bca9c1eee45.png)
 Sign In

Screenshot Example with Google Sign In

![social_login_google_screen](https://user-images.githubusercontent.com/11938477/119016049-7f184880-b967-11eb-89d1-009e120d405b.png)
