### ISSUE TITLE
Menu links missing icons

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#337]
Home, Create Channel, All Channels, Enumerations, Settings, and Logout
Screenshot Example

![missing_menu_item_icons_top](https://user-images.githubusercontent.com/11938477/114438233-7c227f00-9b95-11eb-9635-592b4e239934.png)
![missing_menu_item_icons_btm](https://user-images.githubusercontent.com/11938477/114438263-83e22380-9b95-11eb-829b-2e7ed5b2b556.png)

**Comment by LAlexMHllc** [comment]
Menu link icons display now, except still missing Logout icon

**Comment by b-solution** [comment]
<img width="52" alt="Screenshot 2021-05-24 at 7 44 06 PM" src="https://user-images.githubusercontent.com/5988861/119364666-8e312a80-bcc8-11eb-8283-d8151f6c4cde.png">

<img width="49" alt="Screenshot 2021-05-24 at 7 44 21 PM" src="https://user-images.githubusercontent.com/5988861/119364693-94bfa200-bcc8-11eb-95b9-5b6bdce1cf21.png">
