### ISSUE TITLE
Missing button icons

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#339]
Screenshot Example

![missing_button_icons](https://user-images.githubusercontent.com/11938477/114441777-cdcd0880-9b99-11eb-8a0a-c26ac971c4ab.png)

**Comment by LAlexMHllc** [comment]
Most button icons display now, but still missing some.

Screenshot Example

![leave_channel_button_missing_icon](https://user-images.githubusercontent.com/11938477/119031349-002c0b80-b979-11eb-974a-498e58e17ddf.png)

**Comment by b-solution** [comment]
<img width="1431" alt="Screenshot 2021-05-24 at 7 40 58 PM" src="https://user-images.githubusercontent.com/5988861/119364188-1531d300-bcc8-11eb-91f3-074192af53b3.png">

<img width="1426" alt="Screenshot 2021-05-24 at 7 41 29 PM" src="https://user-images.githubusercontent.com/5988861/119364231-1f53d180-bcc8-11eb-9476-cc3039b2a928.png">
