### ISSUE TITLE
Report does not display correctly on Firefox

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#342]
Screenshot Example

![la_permissions_Group_Channel_Test_View_Report_report_link_click](https://user-images.githubusercontent.com/11938477/114452010-f1964b80-9ba5-11eb-8af4-4500ad1452e7.png)

![la_permissions_Group_Channel_Test_View_Report_report_link_click_2](https://user-images.githubusercontent.com/11938477/114452286-48038a00-9ba6-11eb-90f4-7af3c9f82c6e.png)

**Comment by b-solution** [comment]
![image](https://user-images.githubusercontent.com/5988861/129026373-60425f01-62d9-4150-96ed-d71a756d7f7c.png)
