### ISSUE TITLE
onedrive should be configurable in the ui instead of .env file

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#343]
"AZURE_APP_ID" and "AZURE_APP_SECRET"

AZURE_SCOPES = "offline_access files.readwrite.all" (This one remains same)

should be settings in setup in the application vs config files

**Comment by b-solution** [comment]
<img width="1413" alt="Screenshot 2021-05-24 at 7 49 32 PM" src="https://user-images.githubusercontent.com/5988861/119365276-3646f380-bcc9-11eb-8a67-a6ad0617bfd4.png">
