### ISSUE TITLE
Sign Up screen - Clicking "Terms and Conditions" should display info.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#345]
Screenshot Example

![sign_up_clicking_Terms_and_Conditions_link_should_display_info](https://user-images.githubusercontent.com/11938477/114596082-2a452c00-9c5d-11eb-9c39-39d7aa02f05a.png)

**Comment by LAlexMHllc** [comment]
NOTE: Not able to test due to Issue #363

**Comment by b-solution** [comment]
<img width="607" alt="Screenshot 2021-05-24 at 7 53 42 PM" src="https://user-images.githubusercontent.com/5988861/119366060-ffbda880-bcc9-11eb-9055-4c631dc31fd7.png">
