### ISSUE TITLE
Sign Up screen - Include "*Required" on top of form; put asterisk next to label of required input; and fix position of required element message.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#346]
Include "*Required" on top of form; put asterisk next to label of required input; and position "This Field is Required." message closer to required input.

Screenshot Example

![sign_up_form_required](https://user-images.githubusercontent.com/11938477/114597582-f0752500-9c5e-11eb-947e-2bca7a58b758.png)

**Comment by LAlexMHllc** [comment]
NOTE: Not able to test due to Issue #363

**Comment by b-solution** [comment]
<img width="551" alt="Screenshot 2021-05-24 at 8 08 43 PM" src="https://user-images.githubusercontent.com/5988861/119368943-0a2d7180-bccd-11eb-90bc-73dfd573a2d0.png">
