### ISSUE TITLE
Users screen - Need indicator for user with Status=false due to Registering VS changed from Status=true.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#347]
Screenshot Example

![users_status_false_due_to_register_indicator](https://user-images.githubusercontent.com/11938477/114600256-21a32480-9c62-11eb-808e-34e74ea5cc31.png)

**Comment by b-solution** [comment]
<img width="1433" alt="Screenshot 2021-05-24 at 5 06 24 PM" src="https://user-images.githubusercontent.com/5988861/119345562-7ea6e700-bcb2-11eb-8991-09be2f891c42.png">

I have added new state "pending" when new new user register its default state will be "pending". And Its other states are "active" and "inactive".
