### ISSUE TITLE
Report Dashboard - Tables/Graphs should not overlap.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#348]
Screenshot Example

![dashboard_tables_graphs_not_overlap](https://user-images.githubusercontent.com/11938477/114605125-be1bf580-9c67-11eb-962f-2877f631fe34.png)

**Comment by b-solution** [comment]
<img width="1426" alt="Screenshot 2021-05-24 at 6 33 57 PM" src="https://user-images.githubusercontent.com/5988861/119355400-a69c4780-bcbe-11eb-9e25-ad6ad988d317.png">


Fixed overlapping issue.
