### ISSUE TITLE
Report tables/charts should align left

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#349]
Screenshot Example

![report_tables_graphs_align_left](https://user-images.githubusercontent.com/11938477/114609072-603ddc80-9c6c-11eb-9a13-e28b909a4ddd.png)

**Comment by b-solution** [comment]
<img width="1428" alt="Screenshot 2021-05-24 at 8 34 00 PM" src="https://user-images.githubusercontent.com/5988861/119371418-d7d14380-bccf-11eb-814b-90c4e1fc97a7.png">
