### ISSUE TITLE
the color of these icons don't have enough contrast making it really hard to see

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#354]
![image](https://user-images.githubusercontent.com/3675043/117451942-2bdada80-af11-11eb-8692-2aeb677a67ed.png)

**Comment by bluenevus** [comment]
we really need the words next to it 
![image](https://user-images.githubusercontent.com/3675043/117453820-604f9600-af13-11eb-88ae-7e272633cb30.png)

**Comment by b-solution** [comment]
<img width="1430" alt="Screenshot 2021-06-01 at 6 55 15 PM" src="https://user-images.githubusercontent.com/5988861/120335533-f99f7b80-c30a-11eb-932e-2e01fcaeb68d.png">
