### ISSUE TITLE
there is no administration menu

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#355]
this is completely missing

![image](https://user-images.githubusercontent.com/3675043/117452096-5f1d6980-af11-11eb-97d8-434fa4725e3d.png)

**Comment by b-solution** [comment]
This menu is here in the left sidebar

![image](https://user-images.githubusercontent.com/5988861/117465002-a8e66e00-af6a-11eb-92a0-b084a55d39c2.png)

**Comment by bluenevus** [comment]
its now showing for the default admin or any admin

![image](https://user-images.githubusercontent.com/3675043/117465897-23d66700-af20-11eb-8bb2-986e863a19d2.png)

![image](https://user-images.githubusercontent.com/3675043/117465974-36e93700-af20-11eb-85e8-d021ddf8ebf0.png)

**Comment by bluenevus** [comment]
![image](https://user-images.githubusercontent.com/3675043/117467054-559bfd80-af21-11eb-9665-a57bc0f1ff8d.png)

**Comment by bluenevus** [comment]
cant change enumerations, there is no admin menu for it
![image](https://user-images.githubusercontent.com/3675043/117467233-7e23f780-af21-11eb-99fc-e4c1bd1a9f3f.png)

**Comment by b-solution** [comment]
<img width="202" alt="Screenshot 2021-06-01 at 6 51 15 PM" src="https://user-images.githubusercontent.com/5988861/120335258-c65cec80-c30a-11eb-8cce-17d6835ab301.png">
