### ISSUE TITLE
big tables result in formatting issues where the title of one bleeds into another

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#356]
![image](https://user-images.githubusercontent.com/3675043/117466937-3a30f280-af21-11eb-97cb-1eabde97c8df.png)

**Comment by b-solution** [comment]
<img width="1398" alt="Screenshot 2021-05-27 at 11 20 13 PM" src="https://user-images.githubusercontent.com/5988861/119877173-1ff79c80-bf42-11eb-9d47-5558937ba8c8.png">
