### ISSUE TITLE
Error message displays on Sign Up screen after "Sign Up" clicked on Sign In screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#363]
Screenshot Example

![sign_up_click_error_screen_displays](https://user-images.githubusercontent.com/11938477/118994156-17a4cd80-b954-11eb-89aa-ca394c8144af.png)

**Comment by b-solution** [comment]
<img width="551" alt="Screenshot 2021-05-24 at 8 08 43 PM" src="https://user-images.githubusercontent.com/5988861/119369164-4cef4980-bccd-11eb-9118-6c920f667a4b.png">
