### ISSUE TITLE
New Channel screen - Clicking "Cancel" just reloads screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#364]
Screenshot Example

![new_channel_form_clicking_Cancel_reloads_screen](https://user-images.githubusercontent.com/11938477/118999909-a74c7b00-b958-11eb-9abe-83666a473eea.png)

**Comment by b-solution** [comment]
Can you please explain, what should be the behaviour of this cancel button?

**Comment by b-solution** [comment]
![image](https://user-images.githubusercontent.com/5988861/128018078-095dcd9a-5f68-4589-8b8d-fca17be1d221.png)
