### ISSUE TITLE
Creator should be able to Edit/Delete Public Channel dashboard

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#366]
Screenshot Example

![dashboard_creator_should_be_able_edit_delete](https://user-images.githubusercontent.com/11938477/119007965-b682f700-b95f-11eb-8977-1b115e29fe09.png)

**Comment by b-solution** [comment]
![Uploading Screenshot 2021-05-24 at 7.34.14 PM.png…]()
