### ISSUE TITLE
Menu should have collapsible tab links for Personal, Group, and Public channels

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#367]
Personal Channels, Group Channels, and Public Channels would be the parent links (for type of channel). When the user clicks a channel type link, the corresponding submenu links will display.

**Comment by b-solution** [comment]
<img width="215" alt="Screenshot 2021-06-01 at 6 52 13 PM" src="https://user-images.githubusercontent.com/5988861/120334978-8b5ab900-c30a-11eb-9cdc-1251465360ae.png">
