### ISSUE TITLE
Include collapsible tab "Administration" link on menu sidebar with sub-links, for user with privilege

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#369]
Screenshot Example

![administration_menu_link_with_sublinks](https://user-images.githubusercontent.com/11938477/119150757-bc8add80-ba1c-11eb-8a27-4c891d766cc9.png)

**Comment by b-solution** [comment]
<img width="202" alt="Screenshot 2021-06-01 at 6 51 15 PM" src="https://user-images.githubusercontent.com/5988861/120334786-5fd7ce80-c30a-11eb-9014-17c451c578ca.png">
