### ISSUE TITLE
Users are not able to Sign In

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#374]
User inputs username/password, then clicks "Sign In" and the following message displays.

Screenshot Example

![users_not_able_sign_in](https://user-images.githubusercontent.com/11938477/119377462-26a8ba00-bc8b-11eb-8165-e54e22747a05.png)

**Comment by b-solution** [comment]
<img width="1431" alt="Screenshot 2021-05-27 at 9 43 04 PM" src="https://user-images.githubusercontent.com/5988861/119864907-8d9ccc00-bf34-11eb-9f58-fefbd7bf28ef.png">
