### ISSUE TITLE
Was not able to Register

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#380]
User filled in form, checked Terms and Conditions, then clicked Register; the error message screen displayed.
Screenshot Example

![user_sign_up_register_click_error_message_screen](https://user-images.githubusercontent.com/11938477/119694450-37883580-be1b-11eb-9627-c4cc25748e4c.png)

**Comment by b-solution** [comment]
<img width="1430" alt="Screenshot 2021-05-27 at 5 14 09 PM" src="https://user-images.githubusercontent.com/5988861/119824169-0ab54a80-bf0f-11eb-9373-35d734f30557.png">
