### ISSUE TITLE
Request Channel should not display on Sign In Screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#385]
Screenshot Example

![request_channel_displays_sign_in_screen](https://user-images.githubusercontent.com/11938477/119721169-d53e2d80-be38-11eb-9092-ac78cf13f9f9.png)

**Comment by b-solution** [comment]
<img width="1404" alt="Screenshot 2021-05-27 at 8 14 06 PM" src="https://user-images.githubusercontent.com/5988861/119851825-2e38bf00-bf28-11eb-8a68-5d19521ca53a.png">
