### ISSUE TITLE
onedrive client ID should be configured in settings vs .env file

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#391]
onedrive client ID should be configured in settings vs .env file

**Comment by bluenevus** [comment]
I did configure it in .env file but still get this error 
![image](https://user-images.githubusercontent.com/3675043/119877819-7d1a3080-bef7-11eb-9c7b-0fd178b60bc2.png)

**Comment by b-solution** [comment]
Please Add AZURE_KEY and AZURE_SECRET in application.yml file
<img width="1337" alt="Screenshot 2021-05-31 at 9 15 59 PM" src="https://user-images.githubusercontent.com/5988861/120224941-cce15a80-c25d-11eb-82f0-201a9a078670.png">

OR you can also update it from settings page
<img width="1416" alt="Screenshot 2021-05-31 at 9 17 21 PM" src="https://user-images.githubusercontent.com/5988861/120225026-ef737380-c25d-11eb-93c8-dd8ab17f3557.png">


And also set the CALLBACK_URL according to app environment you testing on. it's the base/home/root url of your app.
