### ISSUE TITLE
if themes no longer work since we went to metronic, can we remove it?

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#393]
![image](https://user-images.githubusercontent.com/3675043/119878141-cf5b5180-bef7-11eb-8971-ca1d41053f5f.png)

**Comment by b-solution** [comment]
<img width="809" alt="Screenshot 2021-05-31 at 12 41 47 PM" src="https://user-images.githubusercontent.com/5988861/120158497-a3004780-c20d-11eb-80ec-5303686ef32e.png">
