### ISSUE TITLE
since we removed the notification system, can we remove the settings function?

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#394]
![image](https://user-images.githubusercontent.com/3675043/119878248-e732d580-bef7-11eb-8e3b-fd8a06759b08.png)

**Comment by b-solution** [comment]
<img width="809" alt="Screenshot 2021-05-31 at 12 41 47 PM" src="https://user-images.githubusercontent.com/5988861/120158614-c1664300-c20d-11eb-8d59-e631092aa73b.png">
