### ISSUE TITLE
clicking request channel doesn't do anything

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#395]
![image](https://user-images.githubusercontent.com/3675043/119878413-147f8380-bef8-11eb-97cc-ff5d1d8d7d0f.png)

**Comment by b-solution** [comment]
<img width="683" alt="Screenshot 2021-05-28 at 10 04 05 PM" src="https://user-images.githubusercontent.com/5988861/120018497-a96da400-c000-11eb-89e8-bfc17153302c.png">
