### ISSUE TITLE
scroll bar is in the middle of the menu area instead of at the edge of the menu area

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#397]
![image](https://user-images.githubusercontent.com/3675043/119879403-34637700-bef9-11eb-81fe-57f3fccd5a59.png)

**Comment by b-solution** [comment]
<img width="88" alt="Screenshot 2021-05-28 at 10 07 10 PM" src="https://user-images.githubusercontent.com/5988861/120018827-184afd00-c001-11eb-819a-9a3e398f6c6f.png">
