### ISSUE TITLE
the dashboard no longer displays 2 per line but now only 1 per line

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#398]
![image](https://user-images.githubusercontent.com/3675043/119878909-ae473080-bef8-11eb-9ded-d74851b9abdc.png)

when it should display like so

![image](https://user-images.githubusercontent.com/3675043/119879198-f7978000-bef8-11eb-8f2d-2a747d228157.png)

**Comment by b-solution** [comment]
<img width="1278" alt="Screenshot 2021-05-31 at 11 56 43 AM" src="https://user-images.githubusercontent.com/5988861/120152801-64678e80-c207-11eb-8661-2624e7f1b873.png">

<img width="1277" alt="Screenshot 2021-05-31 at 11 56 58 AM" src="https://user-images.githubusercontent.com/5988861/120152847-70535080-c207-11eb-944d-d7c3af361bc8.png">
