### ISSUE TITLE
can we make this page behave and look more like teams in menu, listing the reports and seeing the cards of the reports?

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#399]
from this 

![image](https://user-images.githubusercontent.com/3675043/119879963-c66b7f80-bef9-11eb-8f0b-1c745587b091.png)

to this

![image](https://user-images.githubusercontent.com/3675043/119880118-eb5ff280-bef9-11eb-9f84-d6e321ca03b2.png)

**Comment by bluenevus** [comment]
also there isn't enough contrast between the menu and the main page to visually separate the menu from the content window

![image](https://user-images.githubusercontent.com/3675043/120494306-b46e5e80-c389-11eb-9487-3a63353eb213.png)

**Comment by bluenevus** [comment]
so you can imagine this 
![image](https://user-images.githubusercontent.com/3675043/121614250-4c281880-ca2c-11eb-85e6-6e2b7e5b28a2.png)

will be the little icons on the far left all the time because there will be no more icons there

on click you get the menu you see in APPS above that lists all the report channels available in the personal, group or public report

![image](https://user-images.githubusercontent.com/3675043/121614319-6cf06e00-ca2c-11eb-834a-dfa238168fab.png)

then in the main window you have cards representing all the data sets you have there like so 
![image](https://user-images.githubusercontent.com/3675043/121614377-87c2e280-ca2c-11eb-99e4-0744224f58e7.png)

**Comment by b-solution** [comment]
<img width="1428" alt="Screenshot 2021-06-29 at 11 20 49 PM" src="https://user-images.githubusercontent.com/5988861/123848084-bc8dcf80-d930-11eb-804e-495b76cc392e.png">

Is it ok or do you need any changes in it?

**Comment by bluenevus** [comment]
probably don't need created by,  Just date of last update and whether shared

**Comment by b-solution** [comment]
<img width="1416" alt="Screenshot 2021-06-30 at 12 04 29 AM" src="https://user-images.githubusercontent.com/5988861/123853336-c74b6300-d936-11eb-863b-fefbe4751446.png">
