### ISSUE TITLE
Edit User action button should display only one icon for dropdown

### ISSUE THREAD

**Issue by b-solution** [MicroHealthLLC/mRMS#404]
<img width="1279" alt="Screen Shot 2021-06-01 at 6 47 00 PM" src="https://user-images.githubusercontent.com/5988861/120334522-20a97d80-c30a-11eb-994b-4dfcd421aa2f.png">

**Comment by b-solution** [comment]
<img width="1046" alt="Screenshot 2021-06-01 at 7 42 41 PM" src="https://user-images.githubusercontent.com/5988861/120342815-95cc8100-c311-11eb-83e0-a438c00ef8e1.png">

**Comment by LAlexMHllc** [comment]
Still see a box on my screen
Screenshot Example

![edit_user_profile_action_button](https://user-images.githubusercontent.com/11938477/120348618-5713d800-c2cb-11eb-80fd-bc5af106694f.png)
