### ISSUE TITLE
clicking personal launches the request channel dialog

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#407]
![image](https://user-images.githubusercontent.com/3675043/120336620-86711780-c2c0-11eb-9765-aa06281e0404.png)

**Comment by b-solution** [comment]
<img width="1436" alt="Screenshot 2021-06-01 at 7 45 38 PM" src="https://user-images.githubusercontent.com/5988861/120343305-083d6100-c312-11eb-800e-63473ed68995.png">
