### ISSUE TITLE
too much vertical space.  can we reduce the vertical space and maximize the horizontal space use?

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#408]
![image](https://user-images.githubusercontent.com/3675043/120336788-b1f40200-c2c0-11eb-8c06-5376c13772d3.png)

**Comment by b-solution** [comment]
<img width="1216" alt="Screenshot 2021-06-28 at 3 25 45 PM" src="https://user-images.githubusercontent.com/5988861/123621959-2456f400-d825-11eb-8b1a-e1105812eeaa.png">

**Comment by b-solution** [comment]
<img width="1206" alt="Screenshot 2021-06-28 at 3 32 13 PM" src="https://user-images.githubusercontent.com/5988861/123622744-0ccc3b00-d826-11eb-8892-7f3eb3248f7f.png">
