### ISSUE TITLE
rather than have 2 separate screens can we have 1 screen to setup a channel and upload?

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#410]
can we reduce the number of screens do setup a channel and upload?

![image](https://user-images.githubusercontent.com/3675043/120337191-1616c600-c2c1-11eb-8aff-a7f487421509.png)

and this

![image](https://user-images.githubusercontent.com/3675043/120337251-2333b500-c2c1-11eb-831e-94be6ef869fe.png)

and this

![image](https://user-images.githubusercontent.com/3675043/120337276-2a5ac300-c2c1-11eb-81c7-88a7e800ed5a.png)

so its one screen vs 3 screens to do the same action

**Comment by bluenevus** [comment]
in general, I want to maximize the space, reduce the dead space and REDUCE the number of screens to do an action.  there are just a lot of screens to cycle through because each screen is like a function

**Comment by b-solution** [comment]
<img width="1424" alt="Screenshot 2021-06-25 at 1 58 42 AM" src="https://user-images.githubusercontent.com/5988861/123331604-ed4cbe00-d558-11eb-8988-b9dca899d8a1.png">
