### ISSUE TITLE
Only user with Active Status should be able to sign in successfully

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#413]
Screenshot Example

![user_inactive_status_should_not_sign_in_successfully](https://user-images.githubusercontent.com/11938477/120343936-1f0a9600-c2c7-11eb-9364-47cc23786984.png)

**Comment by b-solution** [comment]
@LAlexMHllc There are three type of state of a user  'Pending', 'Active', 'Inactive'. 
Do you want only 'Inactive' users should not be signed in?

**Comment by b-solution** [comment]
<img width="1429" alt="Screenshot 2021-06-01 at 8 05 18 PM" src="https://user-images.githubusercontent.com/5988861/120347162-7afc0b80-c315-11eb-8781-948e146a4a31.png">

Now User with Inactive Status should not be able to sign in.

**Comment by LAlexMHllc** [comment]
NOTE: Changed Issue Title.
Reopened, since user without Active Status was able to successfully Sign in

Screenshot Example

![user_status_not_active_should_not_sign_in_successfully](https://user-images.githubusercontent.com/11938477/120351013-7ca1e100-c2cd-11eb-9e11-683a8008aa10.png)

**Comment by b-solution** [comment]
<img width="1408" alt="Screenshot 2021-06-03 at 4 22 43 PM" src="https://user-images.githubusercontent.com/5988861/120637148-f382d980-c487-11eb-9838-07f72c3bf3d1.png">

**Comment by b-solution** [comment]
<img width="1218" alt="Screenshot 2021-06-03 at 4 23 51 PM" src="https://user-images.githubusercontent.com/5988861/120637290-262cd200-c488-11eb-8d33-2c777afe690f.png">
