### ISSUE TITLE
reports pages don't have maximize like the other screens

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#417]
no maximize here

![image](https://user-images.githubusercontent.com/3675043/120347985-c0dfb200-c2ca-11eb-9ce9-6e8c4b66d732.png)

but it is here on screens where the maximize is not necessarily needed

![image](https://user-images.githubusercontent.com/3675043/120348055-cdfca100-c2ca-11eb-85de-a0c22b7496f9.png)

![image](https://user-images.githubusercontent.com/3675043/120348073-d48b1880-c2ca-11eb-813e-547fb6b63255.png)

**Comment by b-solution** [comment]
<img width="1193" alt="Screenshot 2021-06-17 at 3 09 16 PM" src="https://user-images.githubusercontent.com/5988861/122377109-352e7c80-cf7e-11eb-93fd-cef26d46da26.png">

<img width="1434" alt="Screenshot 2021-06-17 at 3 10 17 PM" src="https://user-images.githubusercontent.com/5988861/122377136-3eb7e480-cf7e-11eb-9171-23b0b1afd1cc.png">

<img width="1431" alt="Screenshot 2021-06-17 at 3 08 23 PM" src="https://user-images.githubusercontent.com/5988861/122377178-47101f80-cf7e-11eb-89c3-75e3ed314de1.png">
