### ISSUE TITLE
we need  a preview of the icon in the dropdown to select the most relevant one

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#418]
![image](https://user-images.githubusercontent.com/3675043/120348314-11570f80-c2cb-11eb-8d1b-bfba15a6dbe9.png)

**Comment by b-solution** [comment]
<img width="852" alt="Screenshot 2021-06-29 at 9 16 43 PM" src="https://user-images.githubusercontent.com/5988861/123833739-1934be80-d920-11eb-8f8f-cb14cf87b7af.png">
