### ISSUE TITLE
can we have a more graphical way to create a dashboard

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#419]
currently its like this

![image](https://user-images.githubusercontent.com/3675043/120348647-5da24f80-c2cb-11eb-9747-f709da4cc894.png)

but it would be great to select the reports here and just add it to a dasboard

![image](https://user-images.githubusercontent.com/3675043/120348732-727ee300-c2cb-11eb-9445-d175b6443f62.png)

**Comment by bluenevus** [comment]
and in a report...just be able to add it to an existing dashboard 
![image](https://user-images.githubusercontent.com/3675043/120348836-8e828480-c2cb-11eb-9df5-6a808ff608de.png)

**Comment by b-solution** [comment]
1. more graphical way to create a dashboard

<img width="1221" alt="Screenshot 2021-06-29 at 6 51 08 PM" src="https://user-images.githubusercontent.com/5988861/123809560-24312400-d90b-11eb-8f14-405ab2e178bc.png">

2. Add report to an existing dashboard.

<img width="1185" alt="Screenshot 2021-06-29 at 6 51 40 PM" src="https://user-images.githubusercontent.com/5988861/123809744-4d51b480-d90b-11eb-9c2f-c4b8738cffef.png">

Select dashboards(multiple) in which you want to add a perticular report. 

<img width="1190" alt="Screenshot 2021-06-29 at 6 52 05 PM" src="https://user-images.githubusercontent.com/5988861/123809782-55a9ef80-d90b-11eb-96ce-a2d20cfaf572.png">
