### ISSUE TITLE
User should not be automatically signed in after successfully Registering; and should be Pending Status, not Active.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#421]
Screenshot Example

![successful_register_should_not_automatically_sign_in_user](https://user-images.githubusercontent.com/11938477/120356793-b7f2de80-c2d2-11eb-950a-790f15908f34.png)

**Comment by LAlexMHllc** [comment]
Screenshot Example of User Status after successfully registering - CORRECT

![user_successfully_registered_with_status_pending](https://user-images.githubusercontent.com/11938477/120357392-66971f00-c2d3-11eb-9867-17784d1fe2db.png)

**Comment by LAlexMHllc** [comment]
NOTE: When user fills in Sign In form and clicks Sign In, the message "Your account is not active" displays. - CORRECT

**Comment by b-solution** [comment]
Only 'active' State user can sign in automatically after successful signed up or registration.

<img width="1427" alt="Screenshot 2021-06-03 at 4 10 44 PM" src="https://user-images.githubusercontent.com/5988861/120636701-5de74a00-c487-11eb-8b86-521aabfc0f88.png">

**Comment by LAlexMHllc** [comment]
After Registering, user still automatically gets signed in
Screenshot Example

![successful_register_still_automatically_signed_in](https://user-images.githubusercontent.com/11938477/121554899-88358c00-c9e0-11eb-9143-7d4b001540ac.png)

**Comment by b-solution** [comment]
<img width="1314" alt="Screenshot 2021-06-11 at 5 20 53 AM" src="https://user-images.githubusercontent.com/5988861/121612910-d3997a00-ca74-11eb-91ed-a3d01c71b1bc.png">

Did you set Default user status to 'active' from setting. I think this is the reason you get active user after successful registration.
