### ISSUE TITLE
Edit User form - Active should not be selected by default for Status for Registered User (Pending Status)

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#422]
Screenshot Example of User Status on Users table after successfully registering (Sign Up form)

![user_successfully_registered_with_status_pending](https://user-images.githubusercontent.com/11938477/120357392-66971f00-c2d3-11eb-9867-17784d1fe2db.png)

Screenshot Example of Edit User with Active selected for Status by default

![edit_user_form_status_should_not_be_active_for_user_with_Pending_Status](https://user-images.githubusercontent.com/11938477/120362212-d4921500-c2d8-11eb-8fc3-b7ac1cdf0a4a.png)

**Comment by LAlexMHllc** [comment]
NOTES:
- Under SETTINGS - Authentication tab: Active is selected to be Default User Status. 
- Status is not a form element on New User form.

**Comment by b-solution** [comment]
@LAlexMHllc Do you want me to add status on New User Form?

**Comment by b-solution** [comment]
<img width="1225" alt="Screenshot 2021-06-02 at 6 30 12 PM" src="https://user-images.githubusercontent.com/5988861/120633296-6b9ad080-c483-11eb-912d-dbfe7cd96bac.png">

**Comment by b-solution** [comment]
Under SETTINGS - Authentication tab: Now we have all 'Pending', 'Active' and 'Inactive' as Default User Status.
Now Status is a form element on New User form.
