### ISSUE TITLE
Not able to see full name of channel: Should display full channel name on hover

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#423]
Screenshot Example

![popup_full_channel_name_on_hover](https://user-images.githubusercontent.com/11938477/120364474-49664e80-c2db-11eb-872c-2d528c72a1b7.png)

**Comment by b-solution** [comment]
<img width="387" alt="Screenshot 2021-06-02 at 2 52 23 PM" src="https://user-images.githubusercontent.com/5988861/120460053-33778d00-c3b2-11eb-800a-ba50de8ecbc5.png">
