### ISSUE TITLE
News section on Home screen should not display when News module is unchecked under Settings

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#424]
Screenshot Example of Settings

![settings_news_module_unchecked](https://user-images.githubusercontent.com/11938477/120365954-0dcc8400-c2dd-11eb-938b-4138160683c8.png)

Screenshot Example of Home screen - News section

![news_section_index_not_display_when_module_unchecked_under_settings](https://user-images.githubusercontent.com/11938477/120366008-20df5400-c2dd-11eb-8931-f072c4365f35.png)

**Comment by b-solution** [comment]
<img width="1426" alt="Screenshot 2021-06-02 at 5 32 43 PM" src="https://user-images.githubusercontent.com/5988861/120480565-9d9b2c80-c3c8-11eb-8c6e-dccb2f5030d0.png">

**Comment by b-solution** [comment]
<img width="1437" alt="Screenshot 2021-06-02 at 5 31 55 PM" src="https://user-images.githubusercontent.com/5988861/120480640-b60b4700-c3c8-11eb-995d-3324ea79b5c5.png">
