### ISSUE TITLE
Settings screen - Modules Page tab: Reports should be checked/disabled

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#425]
User can not Add Data Set, Upload File, etc. without Reports being checked under Settings. Therefore, Reports should remain checked.

Screenshot Example of Settings with Reports unchecked

![settings_module_page_tab_reports_unchecked_saved](https://user-images.githubusercontent.com/11938477/120367665-2473da80-c2df-11eb-807a-da501bbaa564.png)

Screenshot Example of Add Data Set button on channel screen

![add_data_set_button](https://user-images.githubusercontent.com/11938477/120368003-892f3500-c2df-11eb-8855-3aef216e52d9.png)

Screenshot Example of Error screen

![new_report_displays_error_screen](https://user-images.githubusercontent.com/11938477/120368105-acf27b00-c2df-11eb-9433-6394790c0827.png)

**Comment by b-solution** [comment]
<img width="1431" alt="Screenshot 2021-06-02 at 5 43 04 PM" src="https://user-images.githubusercontent.com/5988861/120481885-08009c80-c3ca-11eb-905e-4ef6321bbf8a.png">

Once you make reports modules checked, it cannot be unchecked again now. So that user can add data set
