### ISSUE TITLE
Sign Up form: Fix validation error message display for unchecked Terms and Conditions

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#426]
Screenshot Example

![sign_up_terms_and_conditions_unchecked_validation_message](https://user-images.githubusercontent.com/11938477/120378291-3c059000-c2ec-11eb-8dc1-babba04ebed4.png)

**Comment by b-solution** [comment]
<img width="585" alt="Screenshot 2021-06-03 at 1 43 24 PM" src="https://user-images.githubusercontent.com/5988861/120615674-f377df00-c471-11eb-85b6-496c5524a3da.png">
