### ISSUE TITLE
All users should be able to Read the News when module is enabled.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#432]
News should display on Home screen for all users when News is checked under SETTINGS - Module Page tab.

Screenshot Example of SETTINGS - Module Page tab

![settings_module_page_tab_news_reports_checked](https://user-images.githubusercontent.com/11938477/120506552-087e4080-c394-11eb-928c-6aa812e2988f.png)

Screenshot Example of Home screen

![news_should_display_on_home_screen](https://user-images.githubusercontent.com/11938477/120506106-9b6aab00-c393-11eb-8862-18b2f1b1115a.png)

**Comment by b-solution** [comment]
<img width="1439" alt="Screenshot 2021-06-03 at 2 39 05 PM" src="https://user-images.githubusercontent.com/5988861/120623858-8c5e2880-c479-11eb-9551-cfd7877f4522.png">
