### ISSUE TITLE
Profile does not display correctly on Firefox

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#433]
Screenshot Example

![profile_firefox_1](https://user-images.githubusercontent.com/11938477/120510638-9f98c780-c397-11eb-8e2f-3875ca85a180.png)
![profile_firefox_2](https://user-images.githubusercontent.com/11938477/120510653-a293b800-c397-11eb-826f-3e94d6e09c76.png)

**Comment by LAlexMHllc** [comment]
See related Issue #342

**Comment by b-solution** [comment]
<img width="1280" alt="Screen Shot 2021-06-03 at 7 54 32 PM" src="https://user-images.githubusercontent.com/5988861/120665980-aa418280-c4a5-11eb-94de-3701b80d837c.png">
