### ISSUE TITLE
Leave Channel button missing icon

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#435]
Screenshot Example

![leave_channel_button_missing_icon](https://user-images.githubusercontent.com/11938477/120515082-f6080500-c39b-11eb-9b67-4cdc1ade78ed.png)

**Comment by b-solution** [comment]
<img width="1207" alt="Screenshot 2021-06-03 at 2 37 46 PM" src="https://user-images.githubusercontent.com/5988861/120623803-7e100c80-c479-11eb-91f8-0b6e7b14b198.png">
