### ISSUE TITLE
User without Download File permission on Group Channel should not be able to download file

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#436]
Screenshot Example of Permissions

![group_channel_test_lalex_permissions_download_off](https://user-images.githubusercontent.com/11938477/120519694-e939e000-c3a0-11eb-9128-d0bfb4ce924f.png)

Screenshot Example of Export to Excel

![group_channel_test_export_to_excel](https://user-images.githubusercontent.com/11938477/120520196-8432ba00-c3a1-11eb-877a-da797b5d3741.png)

**Comment by b-solution** [comment]
When User not have permission to download
<img width="1430" alt="Screenshot 2021-06-03 at 6 59 49 PM" src="https://user-images.githubusercontent.com/5988861/120657431-ebce2f80-c49d-11eb-959b-54f9552bfd26.png">

When user have permission to download
<img width="1439" alt="Screenshot 2021-06-03 at 6 58 44 PM" src="https://user-images.githubusercontent.com/5988861/120657587-115b3900-c49e-11eb-835b-89c8e315b526.png">
