### ISSUE TITLE
configuration of callback url should be under settings instead of just application yml

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#440]
I configured the application.yml for the callback url and it works to login however all config settings need to be in the UI instead of text files

**Comment by b-solution** [comment]
<img width="1418" alt="Screenshot 2021-06-11 at 7 47 36 PM" src="https://user-images.githubusercontent.com/5988861/121705301-f2882280-caed-11eb-82f3-47388e51ede6.png">
