### ISSUE TITLE
When One Drive have no file to display after successfully connect, nothing display on screen

### ISSUE THREAD

**Issue by b-solution** [MicroHealthLLC/mRMS#443]

**Comment by b-solution** [comment]
![Uploading Screenshot 2021-06-03 at 6.36.32 PM.png…]()

**Comment by b-solution** [comment]
![Uploading Screenshot 2021-06-03 at 6.51.46 PM.png…]()

**Comment by b-solution** [comment]
<img width="1427" alt="Screenshot 2021-06-03 at 6 51 46 PM" src="https://user-images.githubusercontent.com/5988861/120656159-d0aef000-c49c-11eb-9adf-f887cb6a5931.png">

**Comment by bluenevus** [comment]
I have xls files and nothing shows

**Comment by b-solution** [comment]
@bluenevus Please check again it will work now, if the xls file in Documents folder.
