### ISSUE TITLE
When all links are not visible on the left sidebar menu, a vertical scrollbar should display.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#445]
Screenshot Example

![sidebar_menu_display_scrollbar_when_all_links_not_visible](https://user-images.githubusercontent.com/11938477/120657650-b18b7080-c452-11eb-83b7-7a3671315268.png)

**Comment by b-solution** [comment]
<img width="219" alt="Screenshot 2021-06-04 at 4 31 29 PM" src="https://user-images.githubusercontent.com/5988861/120795045-69ec0e00-c552-11eb-9e65-536e81e46b68.png">
