### ISSUE TITLE
Sign In screen - Fix text wraparound image

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#452]
Screenshot Example

![sign_in_screen_fix_text_wraparound_image](https://user-images.githubusercontent.com/11938477/120828345-6d6b9f00-c52a-11eb-903c-8e52bfc79351.png)

**Comment by bluenevus** [comment]
that happens on the landing page but strangely looks fine once logged in however, when we have something in all 4 of the content modules...it looks like this 

![image](https://user-images.githubusercontent.com/3675043/120841241-44063f80-c539-11eb-934e-c0ab6bc164dd.png)

**Comment by bluenevus** [comment]
![image](https://user-images.githubusercontent.com/3675043/120841291-52ecf200-c539-11eb-8ecc-11131caa9feb.png)

**Comment by bluenevus** [comment]
but on the landing page the 4 content modules align

![image](https://user-images.githubusercontent.com/3675043/120841364-68fab280-c539-11eb-8e2f-eb13b4d0ac5e.png)

**Comment by bluenevus** [comment]
gotta format it in the content module
