### ISSUE TITLE
home screen should show cards of data sets you have access to vs the content module which is meant for the login landing page

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#453]
![image](https://user-images.githubusercontent.com/3675043/120843120-b7a94c00-c53b-11eb-940e-1f2d150162e4.png)

**Comment by b-solution** [comment]
<img width="711" alt="Screen Shot 2021-06-23 at 8 05 17 PM" src="https://user-images.githubusercontent.com/5988861/123121220-6d422d80-d45e-11eb-80de-18723091dfe3.png">

**Comment by b-solution** [comment]
<img width="1274" alt="Screen Shot 2021-06-25 at 7 32 24 PM" src="https://user-images.githubusercontent.com/5988861/123440344-1c603f80-d5ec-11eb-8e48-b0516db9ab02.png">

Do you expect this or if you want any change in it, do let me know.

**Comment by bluenevus** [comment]
Yes.  With the categories like you have
yes, with the image, channel and report names. 
we probably can't fit every report so its 3 per category with the ones that have been used most frequently done first and with "more" so they can expand it
not with all that meta data

So its report categories like you have as fist level 1st level group
Data sets you have at the next level groups
then top 3 reports they use with "more " to expand more reports they use (of course what they have permissions to)

the report card would then be more like this  though much smaller to fit 3 across
![image](https://user-images.githubusercontent.com/3675043/123442970-712b9800-d5a3-11eb-8678-959640e4a3ed.png)

ideally, the image of the report would be more like a screenshot or thumbnail of the actual report vs the generic image as above
no other meta data

**Comment by b-solution** [comment]
<img width="1422" alt="Screenshot 2021-07-02 at 5 14 10 PM" src="https://user-images.githubusercontent.com/5988861/124273028-f2ad9800-db58-11eb-9de4-d3ccec1991fa.png">

Top 3 frequently used reports display under each section on home page.
