### ISSUE TITLE
for the landing login page, can we have one content module that goes across the entire top of the page to serve as a header

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#454]
![image](https://user-images.githubusercontent.com/3675043/120843282-eb847180-c53b-11eb-97b5-ca76c8551428.png)

**Comment by b-solution** [comment]
<img width="1384" alt="Screenshot 2021-08-09 at 7 12 21 PM" src="https://user-images.githubusercontent.com/5988861/128720643-46a42f5d-1d48-4e5c-81d4-3171ab7103bf.png">

**Comment by b-solution** [comment]
@bluenevus Please review the above screens, once you approved, I'll merged it into master. But if you want any changes let me know I'll update it.

**Comment by bluenevus** [comment]
thanks.  I think that will do
