### ISSUE TITLE
as a user I would like to easily refresh the data from onedrive without having to "re upload"

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#459]
as a user I would like to easily refresh the data from onedrive without having to "re upload"

maybe something like a refresh button for onedrive on the main screen vs the upload screen if onedrive is the source.  if onedrive isn't the source, that refresh onedrive button or icon shouldn't show

**Comment by bluenevus** [comment]
This includes dashboards so they need the ability to refresh the one drive data from multiple dashboards with one click for all sources that are "online" including URLs

**Comment by b-solution** [comment]
@bluenevus 
If the owner of the channel changed, then new owner should not be able to access data from previous owner OneDrive account.

Please explain how we handle above scenario?

**Comment by bluenevus** [comment]
the new owner can refresh.   its a new owner.  However, if that person doesn't have access to the data because they didn't fix the permission in onedrive, the will need to "reupload" because onedrive wont' allow them to refresh the data without the new owner having the same access to the data.  Essentially, the one drive issue is abstracted from rms because the person who now owns the data has to have access to the onedrive and if they don't, the refresh should have them reauthenticate and if they can't because they don't have access, onedrive gives them an error to request access like any other onedrive file

**Comment by b-solution** [comment]
I have added a refresh button for the data update
<img width="1209" alt="Screenshot 2021-09-15 at 5 40 32 PM" src="https://user-images.githubusercontent.com/5988861/133436411-48ff5130-ceab-4ca5-b4e5-76cc969e7ec2.png">

When owner was changed we need to connect it with one drive.
<img width="1205" alt="Screenshot 2021-09-15 at 5 47 42 PM" src="https://user-images.githubusercontent.com/5988861/133436542-65e89901-d2eb-4c3b-9121-df9426a8233b.png">

After successful connected you will need to reupload dataset from one drive, after that you can refresh the data from one drive.
<img width="1216" alt="Screenshot 2021-09-15 at 5 48 38 PM" src="https://user-images.githubusercontent.com/5988861/133436748-f86398f5-63ec-4c8c-96f2-7aa1ea373b95.png">

**Comment by bluenevus** [comment]
that will do.  refresh data should only show where onedrive is used as the data source

**Comment by b-solution** [comment]
@LAlexMHllc I have tested it but could not found this issue. Can you please repeat above steps and see if the issue still exist. If yes, please share the log so that I'll look into the issue. Thanks.

**Comment by bluenevus** [comment]
I tested it myself

1. I uploaded data
2. I viewed the report
3.  I clicked refresh data
4. I got this error
![image](https://user-images.githubusercontent.com/3675043/134001605-8b95e386-6d7d-49ff-bb43-e1adb4ba7127.png)

I'll send the logs in teams.

**Comment by b-solution** [comment]
@bluenevus @LAlexMHllc  I have found a small issue which I fixed, Can you please test It again? Thanks.

**Comment by LAlexMHllc** [comment]
Closing, fixed
