### ISSUE TITLE
onedrive file picker is working but the data uploaded or stored in mrms is corrupt

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#460]
it says it was successfully uploaded however after trying to create a report the pivot table errors out

![image](https://user-images.githubusercontent.com/3675043/121527277-3b45bb80-c9c8-11eb-9cd3-d68ed7a3982e.png)

downloading the file that was taken from onedrive is corrupt

![image](https://user-images.githubusercontent.com/3675043/121527404-603a2e80-c9c8-11eb-944b-1db9e3e0fe5f.png)

sample data from the onedrive is below that works when I manually upload from my drive vs onedrive.  like so 

![image](https://user-images.githubusercontent.com/3675043/121527578-8c55af80-c9c8-11eb-97d8-2012a1fa94cd.png)

using the sample data below

[SampleData.xlsx](https://github.com/MicroHealthLLC/mRMS/files/6631463/SampleData.xlsx)

**Comment by b-solution** [comment]
<img width="1409" alt="Screenshot 2021-06-11 at 2 56 54 AM" src="https://user-images.githubusercontent.com/5988861/121602422-b5298380-ca60-11eb-8a73-f4c59eef8675.png">

**Comment by bluenevus** [comment]
pulled it and I get this error 
![image](https://user-images.githubusercontent.com/3675043/121602890-f47eb280-ca15-11eb-93c7-d738eac56279.png)

**Comment by bluenevus** [comment]
I, [2021-06-10T22:15:13.434692 #4297]  INFO -- : [df378400-3aa7-4152-a4ec-d1724c90eeb3] Completed 200 OK in 28ms (Views: 8.4ms | ActiveRecord: 5.3ms)
I, [2021-06-10T22:15:32.038830 #4297]  INFO -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a] Started POST "/channels/10/reports/13/upload_document" for xx.xx.xx.xx at 2021-06-10 22:15:32 +0000
I, [2021-06-10T22:15:32.040423 #4297]  INFO -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a] Processing by ReportsController#upload_document as */*
I, [2021-06-10T22:15:32.040522 #4297]  INFO -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   Parameters: {"report"=>{"document"=>{"0"=>{"@odata.context"=>"https://graph.microsoft.com/v1.0/$metadata#dr$
D, [2021-06-10T22:15:32.043215 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[35mSQL (0.6ms)^[[0m  ^[[1m^[[34mSELECT  `users`.`id` AS t0_r0, `users`.`email` AS t0_r1, `users`.`l$
D, [2021-06-10T22:15:32.044226 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[35m (0.1ms)^[[0m  ^[[1m^[[35mBEGIN^[[0m
D, [2021-06-10T22:15:32.045940 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[35m (0.1ms)^[[0m  ^[[1m^[[35mCOMMIT^[[0m
D, [2021-06-10T22:15:32.046608 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[35m (0.2ms)^[[0m  ^[[1m^[[34mSELECT `enabled_modules`.`name` FROM `enabled_modules` WHERE `enabled_$
D, [2021-06-10T22:15:32.047207 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[36mEnabledModule Load (0.2ms)^[[0m  ^[[1m^[[34mSELECT `enabled_modules`.* FROM `enabled_modules` WH$
D, [2021-06-10T22:15:32.049280 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[35mSQL (0.3ms)^[[0m  ^[[1m^[[34mSELECT `channels`.`id` AS t0_r0, `channels`.`name` AS t0_r1, `chann$
D, [2021-06-10T22:15:32.049856 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[36mChannel Load (0.3ms)^[[0m  ^[[1m^[[34mSELECT `channels`.* FROM `channels` WHERE `channels`.`is_a$
D, [2021-06-10T22:15:32.050416 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[36mChannel Load (0.2ms)^[[0m  ^[[1m^[[34mSELECT `channels`.* FROM `channels` WHERE `channels`.`is_a$
D, [2021-06-10T22:15:32.051703 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[36mChannelOrder Load (0.3ms)^[[0m  ^[[1m^[[34mSELECT  `channel_orders`.* FROM `channel_orders` WHER$
D, [2021-06-10T22:15:32.052613 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[36mChannelOrder Load (0.2ms)^[[0m  ^[[1m^[[34mSELECT  `channel_orders`.* FROM `channel_orders` WHER$
D, [2021-06-10T22:15:32.053470 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[36mChannelOrder Load (0.2ms)^[[0m  ^[[1m^[[34mSELECT  `channel_orders`.* FROM `channel_orders` WHER$
D, [2021-06-10T22:15:32.054321 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[36mChannelOrder Load (0.2ms)^[[0m  ^[[1m^[[34mSELECT  `channel_orders`.* FROM `channel_orders` WHER$
D, [2021-06-10T22:15:32.055084 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[35m (0.2ms)^[[0m  ^[[1m^[[34mSELECT `channel_orders`.`channel_id` FROM `channel_orders` WHERE `chan$
D, [2021-06-10T22:15:32.055967 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[36mChannel Load (0.2ms)^[[0m  ^[[1m^[[34mSELECT `channels`.* FROM `channels` WHERE `channels`.`is_a$
D, [2021-06-10T22:15:32.056621 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[36mChannel Load (0.3ms)^[[0m  ^[[1m^[[34mSELECT `channels`.* FROM `channels` WHERE `channels`.`is_a$
D, [2021-06-10T22:15:32.057497 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[36mChannel Load (0.2ms)^[[0m  ^[[1m^[[34mSELECT  `channels`.* FROM `channels` WHERE `channels`.`is_$
D, [2021-06-10T22:15:32.058028 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[36mReport Load (0.2ms)^[[0m  ^[[1m^[[34mSELECT  `reports`.* FROM `reports` WHERE `reports`.`id` = 1$
D, [2021-06-10T22:15:32.058982 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[36mChannelPermission Load (0.2ms)^[[0m  ^[[1m^[[34mSELECT  `channel_permissions`.* FROM `channel_pe$
D, [2021-06-10T22:15:32.059979 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[36mCACHE Channel Load (0.0ms)^[[0m  ^[[1m^[[34mSELECT  `channels`.* FROM `channels` WHERE `channels$
D, [2021-06-10T22:15:32.060962 #4297] DEBUG -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]   ^[[1m^[[36mReportDocument Load (0.2ms)^[[0m  ^[[1m^[[34mSELECT  `report_documents`.* FROM `report_documents$
I, [2021-06-10T22:15:32.061708 #4297]  INFO -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a] Completed 500 Internal Server Error in 21ms (ActiveRecord: 4.5ms)
F, [2021-06-10T22:15:32.062272 #4297] FATAL -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]
F, [2021-06-10T22:15:32.062317 #4297] FATAL -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a] Errno::ENOENT (No such file or directory @ rb_sysopen - public/uploads/report_document/file/13/SampleData.xls$
F, [2021-06-10T22:15:32.062343 #4297] FATAL -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a]
F, [2021-06-10T22:15:32.062377 #4297] FATAL -- : [ad0cab93-f3ae-47bc-a73e-b14311480f9a] app/controllers/reports_controller.rb:45:in `initialize'
[ad0cab93-f3ae-47bc-a73e-b14311480f9a] app/controllers/reports_controller.rb:45:in `open'
[ad0cab93-f3ae-47bc-a73e-b14311480f9a] app/controllers/reports_controller.rb:45:in `block (2 levels) in upload_document'
[ad0cab93-f3ae-47bc-a73e-b14311480f9a] app/controllers/reports_controller.rb:31:in `upload_document'
[ad0cab93-f3ae-47bc-a73e-b14311480f9a] app/controllers/application_controller.rb:129:in `user_time_zone'

**Comment by bluenevus** [comment]
I sent you the logs in teams

**Comment by b-solution** [comment]
@bluenevus Please test it again!
