### ISSUE TITLE
Sign In screen: Make the images responsive

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#461]
Screenshot Example

![sign_in_screen_adjust_images_for_narrow_measure](https://user-images.githubusercontent.com/11938477/121542699-5a4b4a00-c9d6-11eb-910a-f09efaf8792a.png)

**Comment by b-solution** [comment]
<img width="711" alt="Screen Shot 2021-06-23 at 8 05 17 PM" src="https://user-images.githubusercontent.com/5988861/123121305-8054fd80-d45e-11eb-8ef6-3bd7a7985844.png">
