### ISSUE TITLE
Home screen: Make the images responsive

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#462]
Screenshot Example

![home_screen_adjust_images_for_narrow_measure](https://user-images.githubusercontent.com/11938477/121543118-abf3d480-c9d6-11eb-93f0-54e7e3e7d5da.png)

**Comment by LAlexMHllc** [comment]
See related Issue #461

**Comment by b-solution** [comment]
<img width="711" alt="Screen Shot 2021-06-23 at 8 05 17 PM" src="https://user-images.githubusercontent.com/5988861/123121563-b1cdc900-d45e-11eb-8e5b-63ac21f3860c.png">
