### ISSUE TITLE
Users screen - Deleted Users tab: Username and Status should match All Users tab

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#463]
Screenshot Example

![users_display_username_status_for_all_versus_deleted](https://user-images.githubusercontent.com/11938477/121552053-24aa5f00-c9de-11eb-9314-1ef459768e65.png)

**Comment by b-solution** [comment]
<img width="1375" alt="Screenshot 2021-06-11 at 6 33 04 AM" src="https://user-images.githubusercontent.com/5988861/121618523-5a078900-ca80-11eb-92f2-9b1fdc40d727.png">

<img width="1195" alt="Screenshot 2021-06-11 at 6 43 03 AM" src="https://user-images.githubusercontent.com/5988861/121618559-668be180-ca80-11eb-9b44-1a5c70f43814.png">

Username and Status matched in All Users tabs
