### ISSUE TITLE
New User form: "Pending" should not be active select option.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#464]
Screenshot Example

![new_user_form_pending_should_not_be_active_option](https://user-images.githubusercontent.com/11938477/121560947-08aabb80-c9e6-11eb-8779-8959df83aa12.png)

**Comment by b-solution** [comment]
<img width="1133" alt="Screenshot 2021-06-15 at 2 47 47 AM" src="https://user-images.githubusercontent.com/5988861/121964152-83782b80-cd84-11eb-8206-ad0e8d7617ee.png">
