### ISSUE TITLE
User Delete popups: Alerts or Messages?

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#465]
A popup displays after "Delete" clicked on Delete User modal. If the popup is an Alert, then the user should have to click "OK" to close. Otherwise, the popup is a Message and therefore not necessary for OK button to display; especially since it disappears before user has time to click OK.

NOTE: Also remove ":)" on Soft Deleted popup.

Screenshot Example

![delete_user_popups_ok_button](https://user-images.githubusercontent.com/11938477/121562774-c71b1000-c9e7-11eb-9c2d-81671c119510.png)

**Comment by LAlexMHllc** [comment]
When "Cancel" clicked on confirm Delete User modal, the popup remains open until the user clicks OK; so this is an Alert.
NOTE: Remove ":)"

Screenshot Example

![cancel_delete_user_alert_remains_open_til_OK_clicked](https://user-images.githubusercontent.com/11938477/121565108-2843e300-c9ea-11eb-9b9e-f49de339c907.png)

**Comment by b-solution** [comment]
<img width="419" alt="Screenshot 2021-06-11 at 6 46 54 AM" src="https://user-images.githubusercontent.com/5988861/121619233-b4edb000-ca81-11eb-9bb2-0ced661baf5c.png">

<img width="419" alt="Screenshot 2021-06-11 at 6 47 10 AM" src="https://user-images.githubusercontent.com/5988861/121619250-bc14be00-ca81-11eb-88fd-b0a327e4d00e.png">

<img width="415" alt="Screenshot 2021-06-11 at 6 47 28 AM" src="https://user-images.githubusercontent.com/5988861/121619264-c46cf900-ca81-11eb-80de-5634c8ed6a8f.png">

<img width="418" alt="Screenshot 2021-06-11 at 6 48 33 AM" src="https://user-images.githubusercontent.com/5988861/121619294-cd5dca80-ca81-11eb-873e-d95d7c1f0b0a.png">

<img width="413" alt="Screenshot 2021-06-11 at 6 52 09 AM" src="https://user-images.githubusercontent.com/5988861/121619315-d3ec4200-ca81-11eb-8b45-93a819676f80.png">
