### ISSUE TITLE
under settings for authentication, we need the ability to completely DISABLE self registration

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#468]
![image](https://user-images.githubusercontent.com/3675043/121613189-f3578080-ca29-11eb-84db-0649e7df6334.png)

and no registration option available on the website

**Comment by b-solution** [comment]
<img width="1426" alt="Screenshot 2021-06-14 at 8 51 29 PM" src="https://user-images.githubusercontent.com/5988861/121924603-7e4fb800-cd55-11eb-874c-ddcab6ceaddf.png">

<img width="1155" alt="Screenshot 2021-06-14 at 9 04 34 PM" src="https://user-images.githubusercontent.com/5988861/121924695-9293b500-cd55-11eb-88f3-e00ec04096f0.png">
