### ISSUE TITLE
GROUPS should be Groups

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#470]
![image](https://user-images.githubusercontent.com/3675043/121614606-0f105600-ca2d-11eb-9307-ed9fc4aa8138.png)

**Comment by b-solution** [comment]
<img width="532" alt="Screenshot 2021-06-11 at 4 38 25 PM" src="https://user-images.githubusercontent.com/5988861/121681835-b8f6ed80-cad4-11eb-8fc1-030c90c694b3.png">
