### ISSUE TITLE
User should be able to edit Personal channel and change to Group or Public channel

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#478]
Screenshot Example

![personal_channel_should_be_able_to_change_to_group_or_public_channel](https://user-images.githubusercontent.com/11938477/121718276-247a9400-cab0-11eb-8beb-53cae1160192.png)

**Comment by b-solution** [comment]
<img width="1426" alt="Screenshot 2021-06-14 at 10 14 48 PM" src="https://user-images.githubusercontent.com/5988861/121932206-06d25680-cd5e-11eb-813a-bb7dcfb667d6.png">
