### ISSUE TITLE
Group channel creator should be able to edit channel and change to Public channel

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#479]
Screenshot Example

![group_channel_creator_unable_change_to_public_channel](https://user-images.githubusercontent.com/11938477/121718472-5986e680-cab0-11eb-9bcb-3a44f2a999f1.png)

**Comment by b-solution** [comment]
<img width="1422" alt="Screenshot 2021-06-14 at 3 25 21 AM" src="https://user-images.githubusercontent.com/5988861/121823729-94f7ff80-ccc0-11eb-81ad-dc15e5393fa4.png">
