### ISSUE TITLE
as a user, I would like to maximize a report on a dashboard

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#481]
I see the quad charts but I would like to maximize one of the reports on the dashboard

clicking a maximize function here

![image](https://user-images.githubusercontent.com/3675043/121726225-44ae5100-cab8-11eb-804f-80f2da31af81.png)

to then see it fill the main window like so

![image](https://user-images.githubusercontent.com/3675043/121726412-83440b80-cab8-11eb-9b21-a6cbedc907d9.png)

with the ability to minimize it back to the dashboard

**Comment by b-solution** [comment]
<img width="1193" alt="Screenshot 2021-06-17 at 3 09 16 PM" src="https://user-images.githubusercontent.com/5988861/122381810-c142a300-cf82-11eb-926c-fc1fdd73f8f1.png">

<img width="1434" alt="Screenshot 2021-06-17 at 3 10 17 PM" src="https://user-images.githubusercontent.com/5988861/122381866-cacc0b00-cf82-11eb-9b5b-124998ace2c7.png">

<img width="1431" alt="Screenshot 2021-06-17 at 3 08 23 PM" src="https://user-images.githubusercontent.com/5988861/122381898-d28baf80-cf82-11eb-9512-127a27da0840.png">
