### ISSUE TITLE
can we get more chart types as options.  I think we use plotly?

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#482]
https://plotly.com/javascript/basic-charts/

I would like to maximize the choices with the exception of

WebGL vs SVG in JavaScript and Sankey Diagram and Treemap . don't need these

**Comment by b-solution** [comment]
<img width="1155" alt="Screenshot 2021-07-15 at 12 59 48 PM" src="https://user-images.githubusercontent.com/5988861/125757673-e8e2496c-cf00-4952-9277-49bc658d4261.png">

<img width="1387" alt="Screenshot 2021-07-15 at 1 06 00 PM" src="https://user-images.githubusercontent.com/5988861/125757762-7598ec48-46d7-4d35-8c41-6018bfc34de4.png">

<img width="1372" alt="Screenshot 2021-07-15 at 1 07 03 PM" src="https://user-images.githubusercontent.com/5988861/125757824-73a06f57-f22b-4511-86e2-fafb0c3009cb.png">

<img width="1377" alt="Screenshot 2021-07-15 at 1 04 22 PM" src="https://user-images.githubusercontent.com/5988861/125757882-4111c471-92a7-4934-9d54-b75f7f751d5e.png">

<img width="1205" alt="Screenshot 2021-07-15 at 1 07 43 PM" src="https://user-images.githubusercontent.com/5988861/125757913-bcab7855-a466-453b-a35b-ba3c60a22d09.png">
