### ISSUE TITLE
Shared Report - should change from radios to searchable drop-down multi-select

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#487]
Screenshot Example

![share_report_should_change_to_search_and_multi-select](https://user-images.githubusercontent.com/11938477/121950996-5c8c0c00-cd28-11eb-9c8e-1eee65b9d223.png)

**Comment by b-solution** [comment]
<img width="1220" alt="Screenshot 2021-06-16 at 2 53 35 PM" src="https://user-images.githubusercontent.com/5988861/122198743-dc45e200-ceb2-11eb-9398-55aab3f58bb6.png">
