### ISSUE TITLE
non dashboard reports are still missing the maximize button

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#493]
![image](https://user-images.githubusercontent.com/3675043/122394185-af8ddb00-cf43-11eb-8634-0984f7d21217.png)

should have this to take only the report full screen
![image](https://user-images.githubusercontent.com/3675043/122394430-f8459400-cf43-11eb-8845-e5cac38c3e12.png)

**Comment by b-solution** [comment]
<img width="1216" alt="Screenshot 2021-06-23 at 7 59 35 PM" src="https://user-images.githubusercontent.com/5988861/123120222-931b0280-d45d-11eb-81dc-658c1e657891.png">
