### ISSUE TITLE
Menu items should always be accessible, regardless of screen width.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#496]
The menu items do not display on narrow screen widths.
Screenshot Example

![menu_items_should_always_be_accessible](https://user-images.githubusercontent.com/11938477/123139192-f0925d80-d423-11eb-93ca-f474c49b6da9.png)

**Comment by b-solution** [comment]
<img width="754" alt="Screenshot 2021-06-25 at 1 57 14 AM" src="https://user-images.githubusercontent.com/5988861/123331432-b9719880-d558-11eb-83ee-60abfdccbafe.png">
