### ISSUE TITLE
Missing Share Reports on sidebar menu

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#5]

**Comment by bluenevus** [comment]
the shared folder are reports that other users shared to them

**Comment by bluenevus** [comment]
so here...if a person has a report shared with them, it would show up here in a subfolder called Shared with Me

![image](https://user-images.githubusercontent.com/3675043/40321432-081fbc28-5cfd-11e8-9022-91009c50570e.png)

then show all the reports shared with them in the table to view
