### ISSUE TITLE
group by reports and dashboards in the channel

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#500]
here everything is under the label reports.  can we have one report header and one dashboard header so we can visually separate which on is which?

![image](https://user-images.githubusercontent.com/3675043/123460361-84dffa00-d5b5-11eb-8fff-09ccc28f4be8.png)

**Comment by b-solution** [comment]
<img width="1422" alt="Screenshot 2021-06-28 at 4 39 06 PM" src="https://user-images.githubusercontent.com/5988861/123630812-66853300-d82f-11eb-9cd7-4e895da5b5c8.png">
