### ISSUE TITLE
as a user, I would like to rearrange the order of the dashboard by dragging and dropping

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#507]
![image](https://user-images.githubusercontent.com/3675043/123812861-6eda7e00-d8c2-11eb-8563-2f41cd5f5127.png)

**Comment by b-solution** [comment]
@bluenevus Did you mean the order user select here reflect on dashboard screen?

**Comment by bluenevus** [comment]
yes drag and drop the order

**Comment by b-solution** [comment]
<img width="1190" alt="Screenshot 2021-07-05 at 5 12 25 PM" src="https://user-images.githubusercontent.com/5988861/124469793-3a7c2b80-ddb4-11eb-9307-a7ea89c1c3ed.png">
