### ISSUE TITLE
On a Group or Public report screen, add the ability to add the report to an existing dashboard (like Personal report).

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#508]
Screenshot Example of Public report screen

![include_ability_to_connect_public_channel_report_to_dashboard](https://user-images.githubusercontent.com/11938477/123816470-591a8800-d8c5-11eb-92e3-0d4cc2ba8ce9.png)

Screenshot Example of Group report screen

![include_ability_to_connect_group_channel_report_to_dashboard](https://user-images.githubusercontent.com/11938477/123816498-5e77d280-d8c5-11eb-9505-943efb507146.png)

**Comment by b-solution** [comment]
<img width="1436" alt="Screenshot 2021-06-30 at 3 13 53 PM" src="https://user-images.githubusercontent.com/5988861/123943959-14bae500-d9b6-11eb-9e13-bbec3f59e769.png">

<img width="1424" alt="Screenshot 2021-06-30 at 3 14 48 PM" src="https://user-images.githubusercontent.com/5988861/123944013-213f3d80-d9b6-11eb-85b7-4da2cdd92f90.png">
