### ISSUE TITLE
personal report that says shared results in this error

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#509]
personal report that says shared results in this error
![image](https://user-images.githubusercontent.com/3675043/123817495-36d53a00-d8c6-11eb-8af9-3d8e6e11fe4a.png)

clicking shared reports results in this

![image](https://user-images.githubusercontent.com/3675043/123817466-2de46880-d8c6-11eb-9706-aba3983481d4.png)

**Comment by b-solution** [comment]
<img width="1430" alt="Screenshot 2021-07-01 at 6 50 59 PM" src="https://user-images.githubusercontent.com/5988861/124135613-6a1df180-da9d-11eb-8c2d-3923b47f1b69.png">
