### ISSUE TITLE
Missing "Shared Report" folder under Personal folder

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#512]
Screenshot Example

![shared_folder_missing_under_Personal_folder](https://user-images.githubusercontent.com/11938477/123859000-22a73200-d8f2-11eb-863c-6bcca46e8717.png)

**Comment by LAlexMHllc** [comment]
See related Issue #509

**Comment by b-solution** [comment]
<img width="1430" alt="Screenshot 2021-07-01 at 6 50 59 PM" src="https://user-images.githubusercontent.com/5988861/124135561-5a9ea880-da9d-11eb-9bec-4f678a200e9a.png">
