### ISSUE TITLE
as a user, I expected the button to be clickable however only the hyperlink is clickable

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#515]
as a user, I expected the button to be clickable however only the hyperlink is clickable

![image](https://user-images.githubusercontent.com/3675043/124155983-142d5780-da65-11eb-8235-0b7586273120.png)

**Comment by b-solution** [comment]
<img width="1216" alt="Screenshot 2021-07-06 at 3 45 46 PM" src="https://user-images.githubusercontent.com/5988861/124587649-47ab2000-de71-11eb-8727-29d44a021bb8.png">
