### ISSUE TITLE
Reports that are not shared should not display under Shared Report

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#516]
Screenshot Example

![reports_that_are_not_shared_should_not_display_under_Shared_Report](https://user-images.githubusercontent.com/11938477/124159741-7a1bde00-da69-11eb-8635-34607286a509.png)

**Comment by b-solution** [comment]
<img width="1423" alt="Screenshot 2021-07-02 at 6 47 37 PM" src="https://user-images.githubusercontent.com/5988861/124284027-01e71280-db66-11eb-9805-1ff5fe186d98.png">

Only Shared reports display under Shared Report channel.
