### ISSUE TITLE
Group Channel - Clicked "Connect with Dashboards" button and an error screen displayed

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#518]
Screenshot Example

![group_channel_clicked_connect_dashboards_button_error_screen_displayed](https://user-images.githubusercontent.com/11938477/124162961-14315580-da6d-11eb-8983-c86b20ccfc24.png)

**Comment by b-solution** [comment]
@LAlexMHllc Currently I'm not able to produce this issue. Can you check it again. if this issue still exists provide me some info to figure this out.

**Comment by LAlexMHllc** [comment]
Example Screenshots of clicks to get to Not Authorized screen

![click_1_to_view_data_set](https://user-images.githubusercontent.com/11938477/124620475-790ef600-de47-11eb-8383-86124c05cca8.png)

![click_2_to_view_report](https://user-images.githubusercontent.com/11938477/124620488-7c09e680-de47-11eb-8831-7525c4d16f18.png)

![click_3_connect_with_dashboards_button](https://user-images.githubusercontent.com/11938477/124620513-81673100-de47-11eb-84ed-be059d593dc0.png)

![click_4_not_authorized_screen](https://user-images.githubusercontent.com/11938477/124620577-90e67a00-de47-11eb-8b83-9af9e24d04a7.png)

**Comment by b-solution** [comment]
@LAlexMHllc The logged in user and the user who created this channel are not same. I think we need to add permission for report sharing as well in channel permission for group channels.

**Comment by b-solution** [comment]
<img width="1215" alt="Screenshot 2021-07-16 at 7 32 56 PM" src="https://user-images.githubusercontent.com/5988861/125964359-007c2913-1446-48f7-99ad-6e823121b42f.png">

<img width="441" alt="Screenshot 2021-07-16 at 7 33 42 PM" src="https://user-images.githubusercontent.com/5988861/125964392-4c2b5b24-bcf4-4b36-8597-74f1d81ff2a4.png">

<img width="434" alt="Screenshot 2021-07-16 at 7 34 10 PM" src="https://user-images.githubusercontent.com/5988861/125964423-f901494f-1bef-4883-9732-72a45877020e.png">

**Comment by b-solution** [comment]
When user do not have permission to shared report with dashboard
<img width="1219" alt="Screenshot 2021-07-16 at 7 35 58 PM" src="https://user-images.githubusercontent.com/5988861/125964829-09fcb552-69ba-4e6a-a5e6-e718c131cae3.png">

When user has permission to share report with dashboard
<img width="1219" alt="Screenshot 2021-07-16 at 7 36 43 PM" src="https://user-images.githubusercontent.com/5988861/125964924-252ccdca-e3ee-4d55-9cc6-4a9463b00d20.png">
