### ISSUE TITLE
as a user I would like to create a Multi-Dataset Dashboard

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#525]
Combining multiple reports from multiple data sets and create a multi-dataset dashboard.  Ideally here with a new section below that say Multi-Dataset Dashboard

![image](https://user-images.githubusercontent.com/3675043/124338529-7d50c000-db76-11eb-8713-1a55c0169054.png)

**Comment by b-solution** [comment]
<img width="1275" alt="Screenshot 2021-07-19 at 6 36 27 PM" src="https://user-images.githubusercontent.com/5988861/126168416-28dc7c1c-b22e-4843-b3d5-8ae05733db66.png">

**Comment by b-solution** [comment]
<img width="1275" alt="Screenshot 2021-07-19 at 6 36 27 PM" src="https://user-images.githubusercontent.com/5988861/126783379-4bc611e6-d542-437b-b380-1f822250622b.png">
