### ISSUE TITLE
User should sign in with email as well

### ISSUE THREAD

**Issue by b-solution** [MicroHealthLLC/mRMS#531]
<img width="457" alt="Screenshot 2021-07-06 at 5 42 49 PM" src="https://user-images.githubusercontent.com/5988861/124602017-e0e23280-de81-11eb-98fc-3402adb8e5ca.png">

User did not signed in using his email. The above field only work for username not email.

**Comment by LAlexMHllc** [comment]
Does successfully sign in with MH email
Screenshot Example

![sign_in_only_works_with_MH_email](https://user-images.githubusercontent.com/11938477/124624955-5ed71700-de4b-11eb-84b9-44f1af3e85ff.png)
