### ISSUE TITLE
Should disable "Connect with Dashboards" button when no dashboard exist

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#532]
Should apply to any report on any channel.
Screenshot Example

![click_to_view_report_when_no_dashboard_exist_1](https://user-images.githubusercontent.com/11938477/124637132-55ec4280-de57-11eb-810f-d072cbeb1267.png)

![should_disable_connect_to_dashboard_when_no_dashboard_exist](https://user-images.githubusercontent.com/11938477/124801575-feb4a380-df24-11eb-9840-37bc549a5f05.png)

**Comment by b-solution** [comment]
When dashboard exists.
<img width="1407" alt="Screenshot 2021-07-07 at 2 21 32 PM" src="https://user-images.githubusercontent.com/5988861/124734905-fcefdd80-df2e-11eb-8231-c250695f8199.png">

When dashboard not exists.
<img width="1413" alt="Screenshot 2021-07-07 at 2 22 03 PM" src="https://user-images.githubusercontent.com/5988861/124735070-201a8d00-df2f-11eb-9c33-ff098552e8a9.png">

**Comment by LAlexMHllc** [comment]
Reopened, since button should be DISABLED instead.

**Comment by b-solution** [comment]
<img width="1210" alt="Screenshot 2021-07-08 at 4 49 12 PM" src="https://user-images.githubusercontent.com/5988861/124916842-8de8b680-e00c-11eb-801d-7a85c13e5c74.png">
