### ISSUE TITLE
Should disable "New Dashboard" button when no reports exist.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#536]
Applies to any channel
Screenshot Example

![should_disable_new_dashboard_button_when_no_reports_exist](https://user-images.githubusercontent.com/11938477/124802389-e98c4480-df25-11eb-9667-4f7e941593fa.png)

**Comment by b-solution** [comment]
<img width="1434" alt="Screenshot 2021-07-08 at 9 38 31 PM" src="https://user-images.githubusercontent.com/5988861/124959685-e764db80-e034-11eb-9a2a-71fc0051781a.png">
