### ISSUE TITLE
Shared Report folder should consistently display as first subfolder to Personal folder

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#537]
Screenshot Example

![shared_report_folder_should_consistently_display_personal_first_subfolder](https://user-images.githubusercontent.com/11938477/124804381-3c66fb80-df28-11eb-998c-4d7b863ab39c.png)

**Comment by b-solution** [comment]
<img width="236" alt="Screenshot 2021-07-13 at 4 27 38 PM" src="https://user-images.githubusercontent.com/5988861/125444201-1fd95b8b-b81c-493d-bd1d-5a65222b895e.png">
