### ISSUE TITLE
as a user, I would like the ability to delete a dashboard the same way I can delete a report

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#538]
dashboards are missing the delete function
![image](https://user-images.githubusercontent.com/3675043/124831543-5e24aa80-df49-11eb-90de-a97c20e250bd.png)

however on the same screen reports have them
![image](https://user-images.githubusercontent.com/3675043/124831558-67157c00-df49-11eb-9ec4-f9653c060d79.png)

**Comment by b-solution** [comment]
<img width="1194" alt="Screenshot 2021-07-09 at 4 13 13 PM" src="https://user-images.githubusercontent.com/5988861/125074674-0451eb00-e0d7-11eb-88bd-a5ac5961e0c9.png">
