### ISSUE TITLE
the drag and drop is a hit or miss.  it lands in various areas then creates artifacts

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#539]
![image](https://user-images.githubusercontent.com/3675043/124831949-ed31c280-df49-11eb-8647-cbf123e83aea.png)

**Comment by b-solution** [comment]
<img width="1251" alt="Screenshot 2021-07-12 at 7 02 12 PM" src="https://user-images.githubusercontent.com/5988861/125300686-b1c93680-e343-11eb-91e5-9ab43d181198.png">
