### ISSUE TITLE
images are stretched horizontally on the edit dashboard

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#540]
![image](https://user-images.githubusercontent.com/3675043/124832010-033f8300-df4a-11eb-904d-f92e3f0b07ff.png)

**Comment by b-solution** [comment]
<img width="1245" alt="Screenshot 2021-07-12 at 7 20 47 PM" src="https://user-images.githubusercontent.com/5988861/125303508-4c2a7980-e346-11eb-8818-6fd84adcd29a.png">
