### ISSUE TITLE
Include the total number of reports on the dashboard card

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#542]
Screenshot Example

![should_include_total_reports_on_dashboard_card](https://user-images.githubusercontent.com/11938477/124936947-f5830f80-dfd4-11eb-8213-23559cab48d5.png)

**Comment by b-solution** [comment]
<img width="1201" alt="Screenshot 2021-07-09 at 3 55 13 PM" src="https://user-images.githubusercontent.com/5988861/125067752-19764c00-e0ce-11eb-8f0a-dbecab180ff6.png">
