### ISSUE TITLE
Home screen: "Show More" link should only display when there are more reports

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#544]
Screenshot Example

![home_screen_show_more_links_only_when_more_reports](https://user-images.githubusercontent.com/11938477/124957066-a9d96180-dfe6-11eb-9399-911cbbb21873.png)

**Comment by b-solution** [comment]
<img width="1423" alt="Screenshot 2021-07-08 at 11 49 07 PM" src="https://user-images.githubusercontent.com/5988861/124975606-9f9b7f80-e047-11eb-9efe-c37760fb7d34.png">
