### ISSUE TITLE
Home screen: More reports should be shown when "Show More" link clicked

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#547]
Screenshot Example

![home_screen_click_show_more_link_should show_more_report](https://user-images.githubusercontent.com/11938477/124980229-1dd53300-e002-11eb-8f16-153978541fff.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please test it in latest master, it's working for me.

**Comment by LAlexMHllc** [comment]
Closing, since fixed Issue #544 seems to have fixed this issue
