### ISSUE TITLE
as a user I would like the home page to include most frequent dashboards NOT just reports

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#550]
currently it only shows the most frequently used reports but it should also show dashboards as that is used more than reports

![image](https://user-images.githubusercontent.com/3675043/125081720-51f93400-e094-11eb-99dd-b17f9e700b3f.png)

**Comment by b-solution** [comment]
@bluenevus Here we display data sets(reports) not pivot tables (reports), So when a user click on them it will display the report page including all the (pivot table)reports and dashboards. like in the picture below.

<img width="1434" alt="Screenshot 2021-07-13 at 6 22 24 PM" src="https://user-images.githubusercontent.com/5988861/125459307-68ac6116-b9d8-443f-8114-48c90945e411.png">

**Comment by bluenevus** [comment]
So its not the most frequent data set that matters but the actual report or dashboard which ever is the most frequent used.

**Comment by b-solution** [comment]
<img width="294" alt="Screenshot 2021-07-15 at 3 24 54 PM" src="https://user-images.githubusercontent.com/5988861/125773231-a689646b-95dd-4b01-8168-6b998d9b20ed.png">

**Comment by b-solution** [comment]
<img width="903" alt="Screenshot 2021-07-28 at 4 05 05 AM" src="https://user-images.githubusercontent.com/5988861/127238641-8330ab1c-7f31-4f50-a2e1-05a28eb456c4.png">

<img width="903" alt="Screenshot 2021-07-28 at 4 05 17 AM" src="https://user-images.githubusercontent.com/5988861/127238657-beeaacd4-393f-45f8-b9d4-e779926bb430.png">
