### ISSUE TITLE
the reports and dashboard terms overlap the image and report count

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#551]
![image](https://user-images.githubusercontent.com/3675043/125081957-9e447400-e094-11eb-8e75-a86b40b055ab.png)

**Comment by bluenevus** [comment]
and reports 
![image](https://user-images.githubusercontent.com/3675043/125083871-e4023c00-e096-11eb-8ed2-5fabb0a602e6.png)

**Comment by b-solution** [comment]
<img width="1238" alt="Screenshot 2021-07-12 at 7 29 30 PM" src="https://user-images.githubusercontent.com/5988861/125305077-85afb480-e347-11eb-8c18-8b4df3212c96.png">
