### ISSUE TITLE
as a user, I would like to categorize these data sets by enumeration configured in admin

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#552]
There are some places where there are a lot of data sets.  In this case we need a way to organize them by Category.  Those categories should be configured in admin.  There are several ways this could be accomplished.  This could be done through a dropdown that filters those data sets that match the category.

Alternatively, they could be tabs which would be preferred.  This way users can drag and drop a dataset to a different tab.  In this way, there needs to be a way to add a category to the report itself in setting up a report or editing a report.  Of course, if they don't categorize it then its in the default "all"

![image](https://user-images.githubusercontent.com/3675043/125082767-99cc8b00-e095-11eb-9237-ce4e4cb145a6.png)

![image](https://user-images.githubusercontent.com/3675043/125082560-5ffb8480-e095-11eb-84a0-7d5119243081.png)

**Comment by b-solution** [comment]
<img width="1205" alt="Screenshot 2021-08-13 at 6 34 13 PM" src="https://user-images.githubusercontent.com/5988861/129365558-e719b3ef-732e-4709-84a1-0917ea1db1cc.png">

<img width="1192" alt="Screenshot 2021-08-13 at 6 33 42 PM" src="https://user-images.githubusercontent.com/5988861/129365595-f0e6f234-fa1c-4404-9808-cd314c7eb4c7.png">

<img width="1198" alt="Screenshot 2021-08-13 at 6 33 56 PM" src="https://user-images.githubusercontent.com/5988861/129365666-dce82d9e-62c9-41df-b3ec-ef5fcb9c5acb.png">
