### ISSUE TITLE
as a user, I would like to categorize reports whose enumeration is setup in admin

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#553]
There are some places where there are a lot of  reports and dashboards.  In this case we need a way to organize them by Type.  Those Types should be configured in admin.  There are several ways this could be accomplished.  This could be done through a dropdown that filters those reports and dashboards that match the type.

Alternatively, they could be tabs which would be preferred.  This way users can drag and drop dashboards and reports to a different tab.  In this way, there needs to be a way to add a type to the report itself in setting up a report or editing a report.  Of course, if they don't categorize it then its in the default "all"

![image](https://user-images.githubusercontent.com/3675043/125083199-12cbe280-e096-11eb-9c25-622417fd3dae.png)

![image](https://user-images.githubusercontent.com/3675043/125083166-0c3d6b00-e096-11eb-9df4-9b62d94b708e.png)

**Comment by b-solution** [comment]
@bluenevus I have attached some screens below to show you the work flow of this ticket. Please have a look and update me if you want any changes in it. It's not complete yet but basic structure of my work.

<img width="1199" alt="Screenshot 2021-08-09 at 4 29 51 PM" src="https://user-images.githubusercontent.com/5988861/128700941-50c99ebc-9df2-4fb5-9df4-8b708535bfc1.png">

<img width="1185" alt="Screenshot 2021-08-09 at 4 31 06 PM" src="https://user-images.githubusercontent.com/5988861/128701000-1c21a219-b9bf-433d-b68d-3612a28b3685.png">

<img width="1215" alt="Screenshot 2021-08-09 at 4 30 20 PM" src="https://user-images.githubusercontent.com/5988861/128701026-9d9114ff-b0c7-437b-97f6-2ae898c4fed3.png">

<img width="528" alt="Screenshot 2021-08-09 at 4 39 16 PM" src="https://user-images.githubusercontent.com/5988861/128701053-eb6a61df-0c7b-4f63-8550-73fb650faeee.png">

![image](https://user-images.githubusercontent.com/5988861/128701076-0ddc46a8-8307-4731-a6ae-6d51dac2adc6.png)

**Comment by bluenevus** [comment]
can we have the filter over here?  
![image](https://user-images.githubusercontent.com/3675043/128768069-ac556b8e-51be-45b6-960a-e24db0850bf4.png)

**Comment by b-solution** [comment]
<img width="1200" alt="Screenshot 2021-08-13 at 6 31 43 PM" src="https://user-images.githubusercontent.com/5988861/129365175-b5ff2264-dafb-4d87-9e26-27f95cdad397.png">

<img width="1221" alt="Screenshot 2021-08-13 at 6 35 12 PM" src="https://user-images.githubusercontent.com/5988861/129365276-15513f8f-3413-4115-9686-c44e9b4cad58.png">

We use javas js library for maximise, minimise and collapse. So we did not add filter aside of these icons.
