### ISSUE TITLE
Fix report card resizing on Edit Dashboard

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#558]
Screenshot Example of reports on Edit Dashboard on wider screen width

![fix_resize_reports_on_edit_dashboard_1](https://user-images.githubusercontent.com/11938477/125306001-d352ff80-e2fc-11eb-8f7c-ae0e443ab2a7.png)

Screenshot Example of reports on Edit Dashboard on narrower screen width

![fix_resize_reports_on_edit_dashboard_2](https://user-images.githubusercontent.com/11938477/125306038-d9e17700-e2fc-11eb-9848-d55caff75b5a.png)

**Comment by b-solution** [comment]
<img width="1049" alt="Screenshot 2021-07-13 at 6 46 12 PM" src="https://user-images.githubusercontent.com/5988861/125462957-6297ab3e-7492-4d14-a331-c81bf3f7cd0a.png">
