### ISSUE TITLE
Make report and dashboard images smaller so multi-line Name can fit

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#559]
Screenshot Example

![make_report_and_dashboard_images_smaller_to_fit_multi-line_Name](https://user-images.githubusercontent.com/11938477/125314565-4f9d1100-e304-11eb-83a4-9593d7bb1065.png)

**Comment by b-solution** [comment]
<img width="238" alt="Screenshot 2021-07-13 at 7 05 26 PM" src="https://user-images.githubusercontent.com/5988861/125466302-d148cbd3-1c8a-421b-b4ae-7a5644d4d289.png">

<img width="471" alt="Screenshot 2021-07-13 at 7 05 37 PM" src="https://user-images.githubusercontent.com/5988861/125466343-29eff6e2-bee8-436f-a4eb-4de57d48b0a9.png">

**Comment by LAlexMHllc** [comment]
The font size of the Name was made smaller, but the images still need to be smaller. Need to be able to fit up to 3 lines for a report/dashboard Name.

**Comment by b-solution** [comment]
<img width="984" alt="Screenshot 2021-07-14 at 5 28 25 AM" src="https://user-images.githubusercontent.com/5988861/125542097-b6e3ace2-03c5-4d23-ad59-9479bfaa3d0b.png">

<img width="701" alt="Screenshot 2021-07-14 at 5 28 38 AM" src="https://user-images.githubusercontent.com/5988861/125542112-2ed5c695-755f-4781-b1de-5856557e74e0.png">

Can you please check it again, The font size of name did not decreased it is just the difference of capital and small letters. The height of the card is auto adjust according to the text written inside.
