### ISSUE TITLE
Dashboard New/Edit forms: Should retain reports drag n drop order within Reports box when failed validation

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#568]
Screenshot Example of Dashboard form without Name filled in, with Reports filled in, Save clicked

![new_dashboard_form_without_name_filled_with_reports_selected_click_save](https://user-images.githubusercontent.com/11938477/126212159-42bdcb40-d682-44b7-bbca-8b611080acd4.png)

Screenshot Example of Dashboard form with validation error

![new_dashboard_form_without_name_filled_with_reports_selected_click_save_2](https://user-images.githubusercontent.com/11938477/126212171-e30a1d64-80a1-46b0-b4c6-ba6a3ca4c6cf.png)

**Comment by b-solution** [comment]
<img width="1199" alt="Screenshot 2021-07-26 at 4 59 23 PM" src="https://user-images.githubusercontent.com/5988861/126985251-b646528c-1faf-4774-a55c-120d05427f53.png">

**Comment by LAlexMHllc** [comment]
Since still not fixed for blank input, the Reports were not arranged in user selected order after Save clicked.
Screenshot Example

![dashboard_form_with_reports_ordered](https://user-images.githubusercontent.com/11938477/127012767-0d5afb33-bbbf-4886-afe3-c3a5b35b6c75.png)

![dashboard_form_with_reports_ordered_2](https://user-images.githubusercontent.com/11938477/127012776-744daf94-e259-402a-84ba-22eb5af05528.png)

NOTE: Will test again after fixing blank input

**Comment by b-solution** [comment]
Before:
<img width="1219" alt="Screenshot 2021-08-05 at 6 38 41 PM" src="https://user-images.githubusercontent.com/5988861/128359521-d5eb78e5-5bba-4af6-aaa8-16a7bda9ef40.png">

After:
<img width="1212" alt="Screenshot 2021-08-05 at 6 38 59 PM" src="https://user-images.githubusercontent.com/5988861/128359605-ed51e77e-6856-48fa-93a2-d633fca7ca5f.png">
