### ISSUE TITLE
Should display validation error when Name not filled on Report form and Save clicked

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#569]
Screenshot Example

![report_form_display_validation_error_when_name_not_filled_save_clicked](https://user-images.githubusercontent.com/11938477/126216206-39bf9d67-28d9-42fc-aaa5-4201d4fc23b4.png)

**Comment by b-solution** [comment]
<img width="494" alt="Screenshot 2021-07-26 at 4 45 37 PM" src="https://user-images.githubusercontent.com/5988861/126983647-1eb55c9c-38a5-4621-bc05-929bf53d4a8a.png">

**Comment by LAlexMHllc** [comment]
Input needs to be trimmed to avoid blank error message.

Screenshot Example of input blank(s), then clicked Save; error message displayed.

![report_form_trim_Name_input_to_avoid_blank_error_message](https://user-images.githubusercontent.com/11938477/127004882-f5827b10-2827-4478-96a8-e18ea0862995.png)

**Comment by b-solution** [comment]
<img width="496" alt="Screenshot 2021-08-06 at 6 52 48 PM" src="https://user-images.githubusercontent.com/5988861/128520801-89897bc0-6215-438e-a220-a798bf53d94c.png">
