### ISSUE TITLE
All Channels: Report displays incorrect Report Name

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#570]
Screenshot Example

![report_click_box](https://user-images.githubusercontent.com/11938477/126217043-86caad5b-6ce8-4b4d-80cd-d639b9d046c0.png)

![report_name_is_incorrect](https://user-images.githubusercontent.com/11938477/126217073-36f0ee90-5416-4b28-97f5-deaa014c3449.png)

**Comment by b-solution** [comment]
<img width="450" alt="Screenshot 2021-07-26 at 4 38 43 AM" src="https://user-images.githubusercontent.com/5988861/126917137-257d94a2-1c28-48f6-949f-71bceacb8f4f.png">

<img width="1189" alt="Screenshot 2021-07-26 at 4 38 19 AM" src="https://user-images.githubusercontent.com/5988861/126917142-c3fee02c-8d91-4aa2-9148-916e272668c6.png">
