### ISSUE TITLE
Fix position of the first horizontal item on the chart so it does not overlap the arrow icon

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#571]
Screenshot Example

![chart_fix_position_of_first_horizontal_item_so_no_overlap_arrow_icon](https://user-images.githubusercontent.com/11938477/126218674-cece39a2-c1d4-4cc8-a034-a4262238201d.png)

**Comment by b-solution** [comment]
<img width="1167" alt="Screenshot 2021-07-26 at 6 05 09 AM" src="https://user-images.githubusercontent.com/5988861/126920371-5dd35b86-6072-42ed-90b6-36ac4d33e2d0.png">
