### ISSUE TITLE
Sometimes Report screen displays with missing sidebar menu links

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#572]
Screenshot Example of Home screen

![home_screen_click_report_box_link](https://user-images.githubusercontent.com/11938477/126356310-3cd691c7-439c-4598-b0c4-73910d9921a1.png)

Screenshot Example of Report screen missing sidebar menu links

![report_screen_displays_with_missing_sidebar_menu_links](https://user-images.githubusercontent.com/11938477/126356461-8c55cc67-5df3-4c2c-8ce8-4456d7102e98.png)

Screenshot Example of how Report screen should display with sidebar menu links

![report_screen_displays_with_all_priv_sidebar_menu_links](https://user-images.githubusercontent.com/11938477/126356604-e8ebf35c-2a54-458c-828c-411137c73b77.png)

**Comment by b-solution** [comment]
@LAlexMHllc I'm not able to produce this issue.

**Comment by b-solution** [comment]
<img width="1433" alt="Screenshot 2021-09-20 at 5 02 59 PM" src="https://user-images.githubusercontent.com/5988861/133998957-b2921f33-544b-45e6-9a74-e18a10269096.png">
