### ISSUE TITLE
Multi Data Set Dashboard form does not display Reports with validation error after submit

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#574]
Screenshot Example of Save clicked without Name and without selected report(s)

![mult-data-set-dashboard_form_click_save_without_name_selected_reports](https://user-images.githubusercontent.com/11938477/126796649-9ad38668-e4b4-45cb-b73d-09877390fddf.png)

Screenshot Example of validation with missing reports under Draggable

![mult-data-set-dashboard_form_click_save_without_name_validation_missing_reports](https://user-images.githubusercontent.com/11938477/126796668-a614b151-6381-4b81-b139-822172662695.png)

______________________________________________________________________________________________________________________

Screenshot Example of Save clicked without Name and with selected report(s)

![mult-data-set-dashboard_form_click_save_without_name_with_selected_reports](https://user-images.githubusercontent.com/11938477/126797163-cb5a7141-f1b0-45d9-84c5-86897ad344f2.png)

Screenshot Example of validation with missing selected Reports and under Draggable

![mult-data-set-dashboard_form_click_save_without_name_validation_missing_reports_2](https://user-images.githubusercontent.com/11938477/126797884-bbe8aaf2-ee45-4619-b54f-ccb4aed2a2ee.png)

**Comment by LAlexMHllc** [comment]
NOTE: User has to click "Cancel", then click "Add Multi Data Set Dashboard" again.

**Comment by b-solution** [comment]
<img width="1190" alt="Screenshot 2021-07-26 at 4 02 30 AM" src="https://user-images.githubusercontent.com/5988861/126916134-62d21427-8a3d-4fc6-af2f-70a91b8f0fcc.png">

**Comment by LAlexMHllc** [comment]
Still need to trim Name for blank(s). Same as Dashboard Issue #582

**Comment by b-solution** [comment]
<img width="1247" alt="Screenshot 2021-08-04 at 8 56 28 PM" src="https://user-images.githubusercontent.com/5988861/128213852-14177b67-a18a-459d-bb32-d471e25a2a7d.png">
