### ISSUE TITLE
Dashboard missing Edit and Delete buttons for Group Channel creator

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#575]
Screenshot Example of Group Channel screen for creator; data set box clicked

![group_channel_creator_clicks_dataset_box](https://user-images.githubusercontent.com/11938477/126805781-8e7c5c78-5254-4d06-99b6-aa21da8932e1.png)

Screenshot Example of Dashboard box click

![group_channel_creator_clicks_dashboard_box](https://user-images.githubusercontent.com/11938477/126805814-319fb767-6c4b-4807-937f-001da50f3359.png)

Screenshot Example of missing Edit and Delete buttons on dashboard screen

![dashboard_screen_missing_edit_delete_buttons_for_creator](https://user-images.githubusercontent.com/11938477/126805968-a796788e-3319-4a1f-a04e-d7ab99c63ce2.png)

**Comment by b-solution** [comment]
<img width="1219" alt="Screenshot 2021-07-26 at 5 32 35 AM" src="https://user-images.githubusercontent.com/5988861/126918672-043ebdcd-fc0f-449e-8ab0-8b1eb6e277d5.png">
