### ISSUE TITLE
crashed when I tried to upload a report, sometimes nothing shows or it doesn't allow me to remove columns from the pivot - Critical issue

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#58]
I uploaded an existing report in excel 97.  This data here.  https://community.tableau.com/servlet/JiveServlet/downloadBody/1236-102-2-15278/Sample%20-%20Superstore.xls
I cleaned it up, removed the extra workbook tabs then uploaded it and it resulted in this

![image](https://user-images.githubusercontent.com/3675043/38889841-d6e2d6be-424d-11e8-8848-a05dd16cf8d4.png)

When it should be this with nothing loaded like other reports

![image](https://user-images.githubusercontent.com/3675043/38889921-06c07224-424e-11e8-8803-118921a68b78.png)

I then converted it from excel 97 to xlsx which is an xml based format and tried to upload that instead and it crashes every time.  Crashes puma.  This is the output before crash

![image](https://user-images.githubusercontent.com/3675043/38889777-a9d4da0a-424d-11e8-8a7e-657a4ab66f7d.png)

**Comment by bluenevus** [comment]
So I tried with a different data set I downloaded from here http://go.microsoft.com/fwlink/?LinkID=521962

and still the same thing.  This time it was xlsx native 

![image](https://user-images.githubusercontent.com/3675043/38890139-8ab7a264-424e-11e8-80e0-ca4fe09bd00e.png)

**Comment by bluenevus** [comment]
I uploaded a csv and it seemed to work fine
https://www.briandunning.com/sample-data/us-500.zip

![image](https://user-images.githubusercontent.com/3675043/38890286-f6132e48-424e-11e8-991b-d2cc919e7fc7.png)

**Comment by bluenevus** [comment]
I think it may have to do with the number of columns.  Here is a report with just a few columns and it works correctly.  I think when it gets too wide, it crashes.

![image](https://user-images.githubusercontent.com/3675043/38890451-72a64436-424f-11e8-89c9-12d02e9ca23a.png)

**Comment by bluenevus** [comment]
I then tried to upload this report here https://www.timeatlas.com/wp-content/uploads/pivot_table_example1.xls

and nothing shows up at all

![image](https://user-images.githubusercontent.com/3675043/38938843-8c649cf6-42f4-11e8-9fb4-22c788c0655a.png)

**Comment by bluenevus** [comment]
I figured it out.  The problem is the underscore.  If an underscore is used in the first row from which the system will pivot...it will create this look https://user-images.githubusercontent.com/3675043/38890139-8ab7a264-424e-11e8-80e0-ca4fe09bd00e.png

for some reason its not handling the underscore well.  also, the reports with underscore causes it to crash from time to time

**Comment by bilel-kedidi** [comment]
this is resolved now?
