### ISSUE TITLE
Multi Data Set Dashboard New/Edit forms: Should retain reports drag n drop order within Reports box when failed validation

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#582]
New form when failed validation: Missing Reports.
Should retain reports drag n drop order within Reports box and reports under Draggable Items.

Screenshot Example of New form with blank(s) input for Name; Save clicked.

![multi-data-set_dashboard-with_blank_name_save_clicked](https://user-images.githubusercontent.com/11938477/127008177-fc7376e1-2f6c-4542-929f-9e28c8b56a86.png)

Screenshot Example of validation screen without reports

![multi-data-set_dashboard-with_blank_name_save_clicked_validation_missing_reports](https://user-images.githubusercontent.com/11938477/127008263-0d54d416-9f8d-4830-bd2c-3676891550cf.png)

__________________________________________________________________________________________

Edit form when failed validation: Missing reports under Draggable Items.
Screenshot Example of New form with blank(s) input for Name; Save clicked.

![mult-data-set-dashboard_form_click_save_without_name_with_selected_reports_2](https://user-images.githubusercontent.com/11938477/127009800-29fce449-3d93-4706-a171-86bcd0c97016.png)

Screenshot Example of validation screen without reports under Draggable Items

![multi-data-set_dashboard-with_blank_name_save_clicked_validation_missing_draggable_items_reports](https://user-images.githubusercontent.com/11938477/127010043-f15151bf-f1f0-40f7-8a19-8c94320ccd01.png)

**Comment by b-solution** [comment]
Before:
<img width="1191" alt="Screenshot 2021-08-04 at 8 54 39 PM" src="https://user-images.githubusercontent.com/5988861/128213579-614cfebb-ff3e-4b79-bdd8-beed42d4fe77.png">

After:
<img width="1181" alt="Screenshot 2021-08-04 at 8 54 51 PM" src="https://user-images.githubusercontent.com/5988861/128213655-7e23b570-2eef-4c58-965b-c4ba30c2748f.png">
