### ISSUE TITLE
Dashboard and Multi Data Set Dashboard forms: Need indication to put Draggable Items into Reports box; arrange reports 2 per row and multi-rows

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#583]
Screenshot Example

![dashboard_and_multi-dashboard_display_reports_2_per_row_multi-line_also_instruct](https://user-images.githubusercontent.com/11938477/127017501-dc9d062f-0bbc-419d-9d72-d71b0464fa96.png)

**Comment by b-solution** [comment]
![image](https://user-images.githubusercontent.com/5988861/127983247-885d60d8-98f7-4a80-b1d7-c101862659b6.png)

**Comment by b-solution** [comment]
@LAlexMHllc Is it look good or do you have anything else in your mind?

**Comment by LAlexMHllc** [comment]
Still needs to be arranged 2 per row and multi-rows

**Comment by LAlexMHllc** [comment]
Closing, fixed. Works at Zoom 100%
