### ISSUE TITLE
Group Permissions screen: Change "Shared" to "Share" for Dashboard permission

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#584]
Screenshot Example

![LA_not_have_permission_share_report_dashboard_group_beta_channel](https://user-images.githubusercontent.com/11938477/127033948-b278d83c-c7fb-4cbc-b7d2-58690eba91e8.png)

**Comment by b-solution** [comment]
<img width="1190" alt="Screenshot 2021-07-27 at 4 49 14 PM" src="https://user-images.githubusercontent.com/5988861/127148794-db030064-8b0e-4b80-a103-49630011b2b6.png">

<img width="488" alt="Screenshot 2021-07-27 at 4 49 25 PM" src="https://user-images.githubusercontent.com/5988861/127148815-21e69368-ac00-439f-99c4-b37a2e141baa.png">

<img width="462" alt="Screenshot 2021-07-27 at 4 49 36 PM" src="https://user-images.githubusercontent.com/5988861/127148835-eecf36cd-daed-4de0-9d40-edf8fbdcae07.png">
