### ISSUE TITLE
"New Dashboard" button should not display for user without permission "Can Share Report with Dashboard" on group channel

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#585]
Screenshot Example of user permission on group channel

![LA_not_have_permission_share_report_dashboard_group_beta_channel](https://user-images.githubusercontent.com/11938477/127034218-8e38ac59-0835-409c-bd98-2d116a0db46b.png)

Screenshot Example of "New Dashboard" button

![LA_not_have_permission_share_report_dashboard_group_beta_channel_yet_button_displays](https://user-images.githubusercontent.com/11938477/127034287-9fa5809a-4a91-4008-9b55-580136db6e53.png)

**Comment by b-solution** [comment]
<img width="1193" alt="Screenshot 2021-07-27 at 7 40 05 PM 1" src="https://user-images.githubusercontent.com/5988861/127178547-2f0170bd-60d2-455e-844f-5b583704c7e1.png">

<img width="1205" alt="Screenshot 2021-07-27 at 7 41 13 PM" src="https://user-images.githubusercontent.com/5988861/127178573-9d3db232-151e-42ba-8b3c-efafa852c454.png">

<img width="1208" alt="Screenshot 2021-07-27 at 7 41 38 PM" src="https://user-images.githubusercontent.com/5988861/127178603-4e1f8c5c-b999-475b-ae51-d00160142cdd.png">
