### ISSUE TITLE
"Add Multi Data Set Dashboard" button should display for user with permission

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#589]
Screenshot Example

![add_multi-data-set-dashboard_button_display_for_user_with_permission](https://user-images.githubusercontent.com/11938477/127335500-a37897f2-1183-4ef2-bcde-d05a5bf6bcca.png)

**Comment by b-solution** [comment]
<img width="1428" alt="Screenshot 2021-07-29 at 3 17 13 AM" src="https://user-images.githubusercontent.com/5988861/127403387-c435486c-2a65-4171-814c-06f2b03fa175.png">
