### ISSUE TITLE
Home and Channel screens - Change "Dashboard" to "Dashboards"

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#590]
Dashboard should be plural like Reports.
Screenshot Example

![home_change_Dashboard_to_Dashboards](https://user-images.githubusercontent.com/11938477/127337485-bb36d15b-d4bd-4940-9d84-387c3b43102d.png)

![channel_screens_change_Dashboard_to_Dashboards](https://user-images.githubusercontent.com/11938477/127338932-b295933d-5472-4715-a0db-3e20b4ad6d7f.png)

**Comment by b-solution** [comment]
<img width="908" alt="Screenshot 2021-07-29 at 1 12 17 AM" src="https://user-images.githubusercontent.com/5988861/127389301-14c32bb6-2e89-4366-b8f3-4e19ebce403c.png">

<img width="1171" alt="Screenshot 2021-07-29 at 1 12 44 AM" src="https://user-images.githubusercontent.com/5988861/127389343-a8530794-fd1f-427b-8649-fdac7a00e8ef.png">
