### ISSUE TITLE
Clicking "Show More" or "Show Less" link on Fullscreen view should function without existing fullscreen.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#592]
Screenshot Example

![fullscreen_with_Show_More_link](https://user-images.githubusercontent.com/11938477/127355553-7821209a-a90a-4894-94c0-819d19e8a7f4.png)

![fullscreen_with_Show_Less_link](https://user-images.githubusercontent.com/11938477/127355575-f94ca2fb-95ea-438a-883d-c1e7c8558bfd.png)

**Comment by b-solution** [comment]
<img width="1424" alt="Screenshot 2021-08-06 at 8 41 29 PM" src="https://user-images.githubusercontent.com/5988861/128536252-4cdd4412-2f62-40c0-9143-70d2ecc1cdd4.png">

<img width="1434" alt="Screenshot 2021-08-06 at 8 41 18 PM" src="https://user-images.githubusercontent.com/5988861/128536278-73062560-4794-40d3-bd22-8063d82113d2.png">
