### ISSUE TITLE
Home screen: Should include collapse/expand button for each section

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#595]
Screenshot Example

![home_screen_include_expand-collapse_button_on_sections](https://user-images.githubusercontent.com/11938477/127517390-0b5ad00a-261c-4995-9c14-ab2bb671efa8.png)

**Comment by b-solution** [comment]
<img width="1418" alt="Screenshot 2021-08-05 at 5 59 27 PM" src="https://user-images.githubusercontent.com/5988861/128353937-786ee387-a6fb-4971-a517-39af0bee0631.png">

**Comment by LAlexMHllc** [comment]
Functions, but missing collapse/expand icons
Screenshot Example

![home_screen_missing_collapse-expand_group_icons](https://user-images.githubusercontent.com/11938477/128362120-e1a0755c-8a7d-4380-bbe1-e01a6f671978.png)

**Comment by b-solution** [comment]
@LAlexMHllc Please now icons display correctly.
