### ISSUE TITLE
Home screen - Clicked "Show More" link, but more were not shown.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#596]
Screenshot Example  for Group Dashboards

![home_screen_group_dashboards_clicked_show_more_did_not_display_more](https://user-images.githubusercontent.com/11938477/127874062-2ea96221-e3d0-4958-80a1-6fa8b191b2f7.png)

**Comment by b-solution** [comment]
<img width="897" alt="Screenshot 2021-08-02 at 6 33 28 PM" src="https://user-images.githubusercontent.com/5988861/127870118-97057769-5dd7-4096-b03c-39568fca53e4.png">

Now it display more records when "show more" clicked

**Comment by b-solution** [comment]
<img width="801" alt="Screenshot 2021-08-05 at 4 39 26 PM" src="https://user-images.githubusercontent.com/5988861/128344011-30987002-6216-4e23-b402-ac340d149ed0.png">

**Comment by LAlexMHllc** [comment]
Reopened, since still did not Show More for Group Dashboards AND now Public Dashboards

**Comment by b-solution** [comment]
<img width="845" alt="Screenshot 2021-08-17 at 5 18 38 PM" src="https://user-images.githubusercontent.com/5988861/129724391-9606390b-609a-408c-a5f9-b6add14c5ab9.png">

<img width="874" alt="Screenshot 2021-08-17 at 5 18 51 PM" src="https://user-images.githubusercontent.com/5988861/129724450-cbb40a9e-1d3e-4c8e-979b-d7017d7723f6.png">
