### ISSUE TITLE
Home screen - Clicking "Show More" or "Show Less" link should only effect that tab's display.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#597]
Screenshot Examples

![home_screen_clicked_Show_Less_when_all_other_tabs_collapsed](https://user-images.githubusercontent.com/11938477/127531929-50bbcb5f-2665-4adc-9919-3341965bec31.png)

![home_screen_clicked_Show_Less_when_all_other_tabs_collapsed_sometimes_displays_incorrect](https://user-images.githubusercontent.com/11938477/127534314-15e9804e-9c31-40a1-885f-2720374d9a15.png)

![home_screen_clicked_Show_Less_when_all_other_tabs_collapsed_sometimes_displays_incorrect_2](https://user-images.githubusercontent.com/11938477/127534336-8cf7a112-1088-432c-a29f-c79b7a60e9d9.png)

**Comment by b-solution** [comment]
<img width="814" alt="Screenshot 2021-08-05 at 4 35 52 PM" src="https://user-images.githubusercontent.com/5988861/128343600-227f71c7-5935-411e-b547-a94b877ecc1b.png">

**Comment by LAlexMHllc** [comment]
Still not fixed. Since the group sections now have collapse/expand, sometimes clicking Show More/Show Less effects these as well.

**Comment by b-solution** [comment]
@LAlexMHllc Please test this again.
