### ISSUE TITLE
Home screen - Multi Data Set Dashboards: Names should have the same style as the others

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#603]
Names are green with hover color change, unlike the others.
Screenshot Example

![home_multi-data-set-dashboards_name_styles_should_be_like_the_others](https://user-images.githubusercontent.com/11938477/127907785-cbe4c4ba-8ae2-4fc8-95d3-df772accafa0.png)

**Comment by b-solution** [comment]
<img width="915" alt="Screenshot 2021-08-03 at 1 33 29 PM" src="https://user-images.githubusercontent.com/5988861/127984495-dfc8821e-902f-434e-beb3-fa1185c39dcb.png">
