### ISSUE TITLE
Home screen - Groups sections should only display what user has permission to view

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#605]
Screenshot Example

![home_screen_group_sections_only_display_view_permissions](https://user-images.githubusercontent.com/11938477/127911222-d419af6d-f0db-4fc2-9ab7-a089410c59e6.png)

**Comment by b-solution** [comment]
<img width="977" alt="Screenshot 2021-08-03 at 4 46 43 PM" src="https://user-images.githubusercontent.com/5988861/128010033-ba201fb1-502e-4153-9d1a-a40eec325788.png">
