### ISSUE TITLE
Report screens display error message

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#620]
Screenshot Example

![report_screens_display_error](https://user-images.githubusercontent.com/11938477/129409097-ae2e38ca-95fb-42bb-b55b-fb5cc69050b2.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please confirm that this issue is resolved or not, because in development environment I'm not facing this issue.

**Comment by bluenevus** [comment]
it works but if you change the name of the enumeration "default" to something else like uncategorized then you get the same error.  If you change it back to the name "default"  then it will work.

If we have to have "default" then that should be named "uncategorized" and you cannot allow anyone to change the name else the system blows up.  I has to be hard coded in there and non modifiable and undeletable

also there needs to be an "all" option that is the default view.  that is the user by default sees "all" in the filter and it shows all.  then and only then can they change the filter to those that have been categorized
