### ISSUE TITLE
rather than a dropdown, the filters should be tabbed and drag and drop

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#629]
currently, the filters a separate for reports, dashboard however, the enumeration should be the same.  It should be a filter to setup the tab for which filters the view.  

One enumeration for data set, reports and dashboard and that enumeration is consistent between all 3.  That then should configure the tabs you see for example below.  The user should then be able to drag and drop a report to different tabs for example out of uncategorized into department or from a department to an executive tab

![image](https://user-images.githubusercontent.com/3675043/129747621-f2c200bf-ef1c-4316-ba9f-d75fa9d06a4d.png)

**Comment by b-solution** [comment]
@bluenevus  What you say about above comment?

**Comment by bluenevus** [comment]
I like it

**Comment by b-solution** [comment]
@bluenevus  one more thing, If I use only one enumeration for all(data set, multi dashboards, reports and dashboards),  We need to add only one enumeration named 'Channel Enumeration'. It include in all channels by default and used as filter (tabs) above. Plus I initialized all of them  to 'Uncategorised' category. Is it ok with you?

**Comment by bluenevus** [comment]
Sure of we can just call it Uncategorized that would be fine.

**Comment by LAlexMHllc** [comment]
Tabbed - DONE
Drag and drop - Still Needs to be done

Screenshot Example before drag n drop attempt

![unable_to_drag_n_drop_1](https://user-images.githubusercontent.com/11938477/135295982-792011fe-fa7d-4b4e-a7b6-8d453710578f.png)

Screenshot Example of drag n drop attempt

![unable_to_drag_n_drop_2](https://user-images.githubusercontent.com/11938477/135296013-386d5b39-7b4b-4429-91f7-beb453781bba.png)

Screenshot Example of failed drag n drop

![unable_to_drag_n_drop_3](https://user-images.githubusercontent.com/11938477/135296033-83592cde-3a22-42e2-b096-fe56c7cb3281.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please try to drop item on the div not on tab. When you bring item on div a small + (sign) appear then you drop the item. like in screenshot below:

<img width="454" alt="Screenshot 2021-09-30 at 4 01 27 PM" src="https://user-images.githubusercontent.com/5988861/135443819-c12f366a-c583-4c7f-923b-1ff64db29c03.png">

When you bring item on tab the + (sign) not display that is why item was not dropped. like in screenshot below:

<img width="690" alt="Screenshot 2021-09-30 at 4 04 27 PM" src="https://user-images.githubusercontent.com/5988861/135444145-9b903bd3-efd4-4d2b-b180-0f6ff9218cfb.png">


You can also experience it in video above in this comment https://github.com/MicroHealthLLC/mRMS/issues/629#issuecomment-920883680.

**Comment by bluenevus** [comment]
its really hard to get it to work with means for most users, it just wont' work.  also, the drag and drop ability should be everywhere there is a tab.  data sets, multi datasets, reports.  if there is a tab, they should be able to drag and drop

**Comment by bluenevus** [comment]
its really hard to get it to work

**Comment by LAlexMHllc** [comment]
OK, got it to work.

**Comment by LAlexMHllc** [comment]
Realized it's working on some tabs, but not on others.

**Comment by bluenevus** [comment]
the bigger problem is that its simply hard to get it to work.  You have to be so precise its not likely users will be successful.  We need the drag and drop to be much simpler for the user.  Its a very narrow range that it will allow you to drop on a tab

**Comment by LAlexMHllc** [comment]
Should make the container depth larger when none to display, so drag n drop target is easier.
Screenshot Example

![drag-n-drop-make-container-deeper-when-none](https://user-images.githubusercontent.com/11938477/135495223-544fe60f-6001-4b28-9cf4-6e6b9db7f214.png)
