### ISSUE TITLE
"Uncategorized" should be default Report Category selected on New Report form; label should be "Report Category".

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#630]
Screenshot Example of  Settings

![enumerations_report_category_with_uncategorized_as_default](https://user-images.githubusercontent.com/11938477/129752351-2b76b091-e6c8-44bb-8cf7-623831d35c3f.png)

Screenshot Example of New Report form

![uncategorized_should_be_default_Report_Category_selected_on_New_Report_form](https://user-images.githubusercontent.com/11938477/129753311-0915def2-3eb7-4b0a-ae3a-7fe51840bdae.png)

**Comment by b-solution** [comment]
<img width="508" alt="Screenshot 2021-08-18 at 6 12 10 PM" src="https://user-images.githubusercontent.com/5988861/129904183-f3cc49a4-e512-4a9b-9d5d-70688e0792b4.png">
