### ISSUE TITLE
Not Authorized screen displayed after user selected Filter on Shared Report screen

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#633]
Screenshot Example

![user_shared_report_screen_selects_filter](https://user-images.githubusercontent.com/11938477/129767274-5e0f2a88-1679-492f-87a7-52e3155f35ce.png)

![user_shared_report_screen_selected_filter_not_authorized_screen](https://user-images.githubusercontent.com/11938477/129767305-e9fa8dd2-e290-45f7-95f8-0f978b96531d.png)

**Comment by b-solution** [comment]
<img width="1435" alt="Screenshot 2021-08-19 at 4 55 14 PM" src="https://user-images.githubusercontent.com/5988861/130064466-4e8a886d-d82a-4356-b97b-8fdb3a035487.png">
