### ISSUE TITLE
Should write/apply script for existing reports, dashboards, etc. to set Category to "Uncategorized" for those without category.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#634]

**Comment by b-solution** [comment]
<img width="1386" alt="Screenshot 2021-08-19 at 6 20 59 PM" src="https://user-images.githubusercontent.com/5988861/130075869-980fb004-de34-43ba-b37c-a5106a27b754.png">

**Comment by LAlexMHllc** [comment]
Reopening, since still found some without Category.

Screenshot Example with All selected

![all_reports_selected_filter](https://user-images.githubusercontent.com/11938477/130509715-c369ddfc-5eae-43ca-9a97-86ab67675300.png)

Screenshot Example with 2 displayed when Executive option selected

![executive_reports_selected_filter](https://user-images.githubusercontent.com/11938477/130509786-42738c2f-b6cd-45ce-ae9b-b0f29ddb5d2d.png)

Screenshot Example with the other options selected with "No reports to display", even "Uncategorized"

![category_selected_for_each_option_all_have_no_reports_even_uncategorized](https://user-images.githubusercontent.com/11938477/130510118-08ca1b6a-0af7-497d-a37e-907d6cb98555.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please check it again and share the results, Thanks.

**Comment by LAlexMHllc** [comment]
Same test as above, with same incorrect result

**Comment by b-solution** [comment]
@LAlexMHllc Can you please run following command on rails console and provide me it's output? I need this data to resolve the issue.

Commands:
1. SavePivotTable.all.pluck(:report_enum_id)
2. Dashboard.all.pluck(:dashboard_enum_id)

**Comment by LAlexMHllc** [comment]
Issue still exists

**Comment by b-solution** [comment]
@LAlexMHllc Can you please check it again?

**Comment by b-solution** [comment]
@LAlexMHllc can you please confirm that is it working or not?

**Comment by LAlexMHllc** [comment]
Closing, fixed
