### ISSUE TITLE
Home screen - Multi Data Set Dashboards - Fix style of Group Dashboards

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#636]
Should be "Group Dashboards" (cap "G", bold weight)

Screenshot Example

![home_screen_multi-data-set-dashboards_should_be_Group_Dashboards_bold](https://user-images.githubusercontent.com/11938477/129789960-560d6415-1836-4bc7-9679-b869f822dfc0.png)

**Comment by b-solution** [comment]
<img width="827" alt="Screenshot 2021-08-23 at 12 42 55 PM" src="https://user-images.githubusercontent.com/5988861/130409734-954cadd0-1fdc-434d-a6ff-505b4ac4d3c4.png">
