### ISSUE TITLE
Change label "Public" to "Personal" on Channel Form; then make channel subfolder to Personal folder

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#64]
Screenshot Example

![personal_channel](https://user-images.githubusercontent.com/11938477/38945158-c11662cc-4303-11e8-9c19-37e738077dae.jpg)

**Comment by bluenevus** [comment]
I have a ticket for this which is asking for a radio button to switch from public to personal with the default being public
