### ISSUE TITLE
Home screen - Fix identification info for report cards, dashboard cards, and multi data set dashboard cards.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#640]
Just include the Name of the report, dashboard, or multi data set dashboard on the cards

**Comment by LAlexMHllc** [comment]
OR, to be consistent for all cards, just include Name and Channel

**Comment by b-solution** [comment]
<img width="817" alt="Screenshot 2021-08-23 at 12 47 31 PM" src="https://user-images.githubusercontent.com/5988861/130410223-7328b6e3-24de-4288-b75d-7ee29ac0dbfb.png">

<img width="827" alt="Screenshot 2021-08-23 at 12 42 55 PM" src="https://user-images.githubusercontent.com/5988861/130410258-3acaeb4d-9b86-47ba-b917-90222b50af0e.png">

**Comment by LAlexMHllc** [comment]
@bluenevus decided that ONLY Name should display for all reports, dashboards, and multi data set dashboards on Home screen. See edited Comment 5 days ago.

**Comment by b-solution** [comment]
<img width="807" alt="Screenshot 2021-08-24 at 7 29 44 PM" src="https://user-images.githubusercontent.com/5988861/130635393-64de445a-104e-416a-9b02-89e1e03e8212.png">

<img width="833" alt="Screenshot 2021-08-24 at 7 29 59 PM" src="https://user-images.githubusercontent.com/5988861/130635435-74136912-a881-485b-84bf-f95df8ce7126.png">
