### ISSUE TITLE
Duplicate Channel was created after changing Channel Owner to user that already had permissions

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#643]
Screenshot Example of Admin - All Channels - Change Owner

![all_channels_select_different_owner_click_Change _Owner](https://user-images.githubusercontent.com/11938477/130111663-c13f2a24-4964-41c8-8ff8-e70011160c9a.png)

Screenshot Example of Successful Save message

![all_channels_select_different_owner_click_Change _Owner_successful_save_message](https://user-images.githubusercontent.com/11938477/130111816-85aa5428-aebf-420b-8994-0739dbf7c8dc.png)

Screenshot Example of duplicate channels on sidebar menu for user that had prior permission on channel, and was changed to owner

![admin_channels_changed_owner_created_duplicate_channel](https://user-images.githubusercontent.com/11938477/130112061-6a508b81-6c8c-49eb-86f8-8c04cecd1395.png)

**Comment by LAlexMHllc** [comment]
NOTE: When Channel Owner was changed to another user (not myself), duplicate channel no longer displayed.

**Comment by bluenevus** [comment]
this is probably related #554

**Comment by b-solution** [comment]
<img width="230" alt="Screenshot 2021-09-01 at 4 20 51 PM" src="https://user-images.githubusercontent.com/5988861/131662962-69799c33-553b-4784-bebb-1abfc2f60a70.png">


<img width="225" alt="Screenshot 2021-09-01 at 4 21 22 PM" src="https://user-images.githubusercontent.com/5988861/131663058-95e113f2-0cc1-4a6e-9def-4681b65708aa.png">
