### ISSUE TITLE
Add Permissions form for Group Channel should not have successfully submitted without User selected.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#644]
Screenshot Example of Add Permissions form when no user with permission on channel exist. User is not preselected.

![group_channel_add_permission_form_when_no_users_with_permission_yet](https://user-images.githubusercontent.com/11938477/130117971-10b19da4-282e-4e0f-aa0f-85a384f21380.png)

Screenshot Example of form submit form without User selected

![add_permission_form_submitted_without_user_selected](https://user-images.githubusercontent.com/11938477/130118240-f2da8854-520d-451f-a1f8-7641ae5280cb.png)

Screenshot Example of "Success" message with admin user given permission on channel after no user selected on form.
User clicked Add Permission again and form displayed with User preselected.

![add_permissions_form_open_after_user_given_permissions](https://user-images.githubusercontent.com/11938477/130118361-b957eb07-14cb-4708-a8ec-b7d73c0a191d.png)

**Comment by b-solution** [comment]
<img width="481" alt="Screenshot 2021-08-23 at 1 35 38 PM" src="https://user-images.githubusercontent.com/5988861/130417075-21870d43-07ea-4112-9780-933a6ccae1ed.png">
