### ISSUE TITLE
User should not be preselected on Add Permissions form 

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#645]
Sometimes the form displays without User preselected; other times with User preselected.
Screenshot Examples

![add_permissions_user_sometimes_preselected](https://user-images.githubusercontent.com/11938477/130121528-9072e374-3f88-4982-b4a7-b6d9dc5d1eb7.png)

**Comment by b-solution** [comment]
<img width="499" alt="Screenshot 2021-08-23 at 1 35 22 PM" src="https://user-images.githubusercontent.com/5988861/130416923-dd5f230a-30ec-47ce-9ed6-8aa82e8a3030.png">
