### ISSUE TITLE
multidata set dashboards only shows tables

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#647]
no matter what type of chart in the report, the multidataset dashboard only displays a table

looking at the report, it doesn't have all the report types that are in the report

![image](https://user-images.githubusercontent.com/3675043/130242616-8fc03186-fc61-4500-bb62-e2ecc3d1a01e.png)

**Comment by b-solution** [comment]
Please check it again, I already fixed this.
