### ISSUE TITLE
even though a user was given the role of report manager, I'm unable to delete reports unless I'm the creator

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#65]
![image](https://user-images.githubusercontent.com/3675043/38946686-3b4afa5e-4308-11e8-825a-7dcdfed4eb71.png)

**Comment by bluenevus** [comment]
This may be resolved when you address this below as users can assign a role to the channel and the report itself
https://github.com/MicroHealthLLC/mRMS/issues/22
https://github.com/MicroHealthLLC/mRMS/issues/21

**Comment by bilel-kedidi** [comment]
will create the permission page Wednesday
