### ISSUE TITLE
Report resizing still needs work

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#654]
Screenshot Example of Display Resolution and Report at 100% Zoom.
NOTE: The horizontal scrollbar does not display (as it should not), but it's misleading since the entire chart is not displayed.

![report_100_scale_no_scrollbar_but_chart_cut_off](https://user-images.githubusercontent.com/11938477/130464738-6f41ad52-bb24-4fa3-abbd-ec56ef87e4f2.png)

Screenshot Example of Full Report display at 90% Zoom

![report_90_scale_no_scrollbar_complete_chart](https://user-images.githubusercontent.com/11938477/130464605-b16fa3a1-005f-4979-9488-4c69637783d0.png)

**Comment by bluenevus** [comment]
still don't want scrollbars.  just want it responsive

**Comment by LAlexMHllc** [comment]
Screenshot Example of Display Resolution and Report at 100% Zoom

![report_100_scale_no_scrollbar_but_chart_cut_off_2](https://user-images.githubusercontent.com/11938477/130466383-7dd6eebb-4d36-4e59-b835-1c42446ea50c.png)

Screenshot Example of Full Report display at 90% Zoom

![report_90_scale_no_scrollbar_complete_chart_2](https://user-images.githubusercontent.com/11938477/130466443-d5c3767f-4af1-42e7-8373-dc9f8803939d.png)

**Comment by b-solution** [comment]
@bluenevus @LAlexMHllc Can you please test it again and share your thoughts.

**Comment by LAlexMHllc** [comment]
Much better, but some wide charts still get cut off.
Screenshot Example

![wide_table_report_100percent_cut_off](https://user-images.githubusercontent.com/11938477/130646169-ed592310-e274-4499-8ac2-05f6eb046cfd.png)

![wide_table_report_90percent_whole](https://user-images.githubusercontent.com/11938477/130646268-0a291f02-3730-43f0-9d34-de359c16c164.png)

**Comment by bluenevus** [comment]
there may just be a limit on how wide the charts can get.  I think at this point, this chart is much to wide where the resizing would be to small to see even on a 1080p monitor.  At some point, its good and I think its good enough right now.
