### ISSUE TITLE
dahsboard reports should fit like a jigsaw puzzle and fill in the blank space

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#661]
sometimes it fits as in the reports on the right, sometimes it leaves a blank space like the report on the left. They should all fit like a jigsaw puzzle

![image](https://user-images.githubusercontent.com/3675043/130831272-353777ef-a3ae-402b-8fbf-dab5409b2fb2.png)

preferably aligned where possible.  when not, move the report into the dead space
![image](https://user-images.githubusercontent.com/3675043/130831461-c56173f2-7937-49e4-8ee9-47517891d4e4.png)

**Comment by b-solution** [comment]
<img width="1247" alt="Screenshot 2021-09-07 at 5 05 37 PM" src="https://user-images.githubusercontent.com/5988861/132341863-c8f58e8c-b8c2-4cef-b781-7cfbde270cb0.png">

<img width="1252" alt="Screenshot 2021-09-07 at 5 05 30 PM" src="https://user-images.githubusercontent.com/5988861/132341884-ed333804-5f1a-41c4-9373-8c888da45a31.png">
