### ISSUE TITLE
horizontal bar graph descriptors are cut off

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#662]
![image](https://user-images.githubusercontent.com/3675043/130833167-dc994f85-0531-4302-83b7-626f5ea267d8.png)

hovering over gives you a partial name maybe 8 characters max.  Sometimes the beginning characters, sometimes the end characters

and really if it needs to cut off, it needs to start at the beginning of the title but really we need a way to read it

**Comment by b-solution** [comment]
<img width="1140" alt="Screenshot 2021-08-31 at 4 58 28 PM" src="https://user-images.githubusercontent.com/5988861/131498800-5e2ab14a-e9bf-43bb-bff4-32b00b7945d8.png">
