### ISSUE TITLE
Administration - All Channels: Should change text "this" on confirm delete to channel Name

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#681]
User might unintentionally click the wrong Delete button, so should include channel Name on confirm delete
Screenshot Example

![all_channels_delete_message_change_this_to_channel_name](https://user-images.githubusercontent.com/11938477/131181725-196262ff-61c7-42b7-91da-e090f0898643.png)

**Comment by b-solution** [comment]
<img width="454" alt="Screenshot 2021-08-30 at 3 22 39 PM" src="https://user-images.githubusercontent.com/5988861/131325812-9a220632-caa4-4da2-8c60-82d286609fbc.png">

I have also fixed this in Channels, Reports, Datasets, Dashboards, Multi dataset dashboards and News.
