### ISSUE TITLE
created multidataset dashboard in a report channel however, other users only had read only

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#684]
created multidataset dashboard in a report channel however, other users only had read only when the channel permissions said they can do anything and everything in the channel

![image](https://user-images.githubusercontent.com/3675043/131369461-1e994008-0769-4b16-9091-e401420f038f.png)

**Comment by bluenevus** [comment]
the owner did not have permission to edit or delete the multidataset dashboard

**Comment by b-solution** [comment]
@bluenevus Can we add a new permission for can_manage_dashboard and can_manage_multi_dataset_dashboard, So that we can use it accordingly?

**Comment by bluenevus** [comment]
sure

**Comment by b-solution** [comment]
Now only those user can create, update and delete dashboards/multi dataset dashboards who has permission.

<img width="1200" alt="Screenshot 2021-09-08 at 8 14 49 PM" src="https://user-images.githubusercontent.com/5988861/132536704-933b49cd-cd06-4902-b08a-d9f23d2c241c.png">
