### ISSUE TITLE
search not working in channel permissions

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#685]
unable to search and its a long list

![image](https://user-images.githubusercontent.com/3675043/131369696-c54a97df-371f-4006-874e-2d7cea580d51.png)

**Comment by b-solution** [comment]
<img width="502" alt="Screenshot 2021-08-31 at 5 19 48 PM" src="https://user-images.githubusercontent.com/5988861/131501554-e1ea5cdd-bf55-4ea0-beff-a255c17b949f.png">
