### ISSUE TITLE
known user of the channel not showing up under permissions and may be related to #685

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#686]
![image](https://user-images.githubusercontent.com/3675043/131369752-87c97cdf-1492-4d63-b61e-83869a5ef14c.png)

known user of the system that is active doesn't show up in the channel above

![image](https://user-images.githubusercontent.com/3675043/131369846-20228964-135f-402a-b69e-4659642056ba.png)

**Comment by b-solution** [comment]
@bluenevus First you need to add permission for 'Page', after that you can search 'Page' name in the permission list. Other wise it will not be seen in the list.

**Comment by bluenevus** [comment]
page already has permission.  she just doesn't show up to add permission at all so I can't modify her permission although she is an owner of the channel

**Comment by LAlexMHllc** [comment]
User successfully created Group Channel, then clicks "Permissions" button.
Screenshot Example

![user_successfully_created_group_channel_clicks_permissions_button](https://user-images.githubusercontent.com/11938477/131522279-aeeb5c3d-c725-4204-8763-9b726346bed3.png)

Permissions table has channel creator as first entry with all permissions granted; without Edit and Delete icons.
Screenshot Example

![group_channel_permissions_with_owner_granted_all_without_edit_delete_icons](https://user-images.githubusercontent.com/11938477/131522458-e95421d3-d96a-4e39-afc0-c60331e500cd.png)
