### ISSUE TITLE
Plotly chart on Dashboard should display action icons like report

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#687]
Currently, Plotly report only displays partial action icons vertically. 
Screenshot Examples

![dashboard_plotly_chart_action_icons_display](https://user-images.githubusercontent.com/11938477/131373260-584257b7-3671-4e25-9e19-726ee7e7a88d.png)

![dashboard_plotly_chart_action_icons_display_1](https://user-images.githubusercontent.com/11938477/131373272-12540a72-c744-443b-afa9-1a1d8d24e58d.png)

Should display all action icons horizontally, like report.
Screenshot Example

![report_plotly_chart_action_icons_all_display](https://user-images.githubusercontent.com/11938477/131373306-7f23d1b1-5ec6-4276-b3bb-7cf3b5fe3686.png)

**Comment by b-solution** [comment]
<img width="1205" alt="Screenshot 2021-08-31 at 5 05 01 PM" src="https://user-images.githubusercontent.com/5988861/131499666-41351285-4e80-4b7b-a85b-460b6736b025.png">
