### ISSUE TITLE
All Channels - Should make "CHANNEL", "TYPE", and "OWNER" columns sortable

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#688]
Screenshot Example

![all_channels_make_channel_type_owner_columns_sortable](https://user-images.githubusercontent.com/11938477/131376852-b7e6adec-af7c-4981-94b5-45927f5f7bb8.png)

**Comment by b-solution** [comment]
<img width="1197" alt="Screenshot 2021-09-02 at 7 49 57 PM" src="https://user-images.githubusercontent.com/5988861/131865868-4e12a069-535e-4c6b-8cae-c56969fd6e28.png">
