### ISSUE TITLE
All Channels - Should include ability to Search and select CHANNEL

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#689]
Screenshot Example

![all_channels_include_ability_to_search_by_channel](https://user-images.githubusercontent.com/11938477/131376934-cfb48e76-6556-4237-9f3f-01f82685067b.png)

**Comment by b-solution** [comment]
<img width="1205" alt="Screenshot 2021-09-01 at 7 48 31 PM" src="https://user-images.githubusercontent.com/5988861/131693311-2f2ea3da-dd55-454e-9be5-078f1257e31f.png">
