### ISSUE TITLE
Creator of Group Channel should display as first entry on Permissions table with all privileges granted, without Edit and Delete icons.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#693]
User successfully created Group Channel, then clicks "Permissions" button.
Screenshot Example

![user_successfully_created_group_channel_clicks_permissions_button](https://user-images.githubusercontent.com/11938477/131522279-aeeb5c3d-c725-4204-8763-9b726346bed3.png)

Permissions table has channel creator as first entry with all permissions granted; without Edit and Delete icons.
Screenshot Example

![group_channel_permissions_with_owner_granted_all_without_edit_delete_icons](https://user-images.githubusercontent.com/11938477/131522458-e95421d3-d96a-4e39-afc0-c60331e500cd.png)

**Comment by b-solution** [comment]
<img width="1191" alt="Screenshot 2021-09-02 at 7 41 53 PM" src="https://user-images.githubusercontent.com/5988861/131865059-871dfb68-da13-4b10-b287-0bba798eff87.png">

**Comment by LAlexMHllc** [comment]
Reopening, since some of the group channels don't satisfy this requirement.
Screenshot Example

![beta_channel_frank_created_by](https://user-images.githubusercontent.com/11938477/132364521-499c91db-71a0-4ff0-9aca-26a1e858bf6a.png)

![beta_channel_frank_created_by_table_missing_Frank](https://user-images.githubusercontent.com/11938477/132364546-81f87091-4272-4265-a674-44b617cd1f9c.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please check it again?

**Comment by LAlexMHllc** [comment]
Closing, fixed
