### ISSUE TITLE
When group channel owner is changed: the owner should display on the Permissions table with all permissions, without Edit and Delete icons.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#694]
**Screenshot Example** when user with permissions on channel is made owner of channel.
NOTE: Owner currently does not display on Permission table, but should (see Issue #693)

![LA_permissions_Group_Channel_2_before_becoming_channel_owner](https://user-images.githubusercontent.com/11938477/131530308-e6aa9411-6b35-4662-aca4-f35d61e60b35.png)

![all_channels_change_Group_Channel_2_owner_from_Lee_to_Lisa](https://user-images.githubusercontent.com/11938477/131530365-bcf9d37a-e391-4363-b2ea-f8469fc7ff3e.png)

![group_channel_2_permissions_after_changed_owner_to_Lisa](https://user-images.githubusercontent.com/11938477/131530425-7128e351-8e3a-46fc-8ac6-1fae6dc64166.png)

_______________________________________________________________________________________________________________________

**Screenshot Example** when user without permissions on channel is made owner of channel.

![group_channel_2_owner_changed_to_user_without_prior_permissions](https://user-images.githubusercontent.com/11938477/131531179-b3447210-94ad-41dc-ac3a-cb601c14bc0e.png)

![group_channel_2_permissions_after_changed_to_Chris](https://user-images.githubusercontent.com/11938477/131531214-9db10343-2a3c-4d4a-9715-85fdb3bf4885.png)

NOTE: Edit and Delete icons should display for prior channel owner

**Comment by b-solution** [comment]
<img width="1191" alt="Screenshot 2021-09-02 at 7 41 53 PM" src="https://user-images.githubusercontent.com/5988861/131865259-6517bd79-3894-4b6f-8fae-a3031d910b8b.png">

<img width="1196" alt="Screenshot 2021-09-02 at 7 43 26 PM" src="https://user-images.githubusercontent.com/5988861/131865306-d25a7dd0-036e-4e25-a071-9665ff58460a.png">

<img width="1194" alt="Screenshot 2021-09-02 at 7 43 40 PM" src="https://user-images.githubusercontent.com/5988861/131865349-18c3fd98-ca3f-4cb7-b92e-755d9b714551.png">
