### ISSUE TITLE
Change "Created by" text to "Owned by", since Owner can be changed under All Channels

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#695]
Screenshot Example

![all_channels_change_Group_Channel_2_owner_from_Lee_to_Lisa](https://user-images.githubusercontent.com/11938477/131537514-fcadd32a-4cbd-4f67-b710-4242dede7fa3.png)

![should_Created_by_text_be_changed_to_Owned_by](https://user-images.githubusercontent.com/11938477/131537369-5b4fab84-fa75-4b68-89ec-ef32a3fd27b8.png)

**Comment by b-solution** [comment]
@LAlexMHllc Should I implement this?

**Comment by LAlexMHllc** [comment]
@b-solution  Leave alone for now

**Comment by b-solution** [comment]
@LAlexMHllc Update me on this as well, should I implement it or not?

**Comment by LAlexMHllc** [comment]
Update when OK with @bluenevus

**Comment by b-solution** [comment]
@bluenevus What do you say about this ?

**Comment by bluenevus** [comment]
leave it as is for now

**Comment by bluenevus** [comment]
On 2nd thought it should be Owned By so people know who to reach out to on the data

**Comment by b-solution** [comment]
<img width="1177" alt="Screenshot 2021-09-27 at 5 30 36 PM" src="https://user-images.githubusercontent.com/5988861/134908754-fa2062f0-1e70-4e7d-81e3-b90d1476edc0.png">

<img width="1139" alt="Screenshot 2021-09-27 at 5 31 27 PM" src="https://user-images.githubusercontent.com/5988861/134908803-46297035-2ee1-4ce0-b637-c53348f761f2.png">

<img width="1186" alt="Screenshot 2021-09-27 at 5 31 59 PM" src="https://user-images.githubusercontent.com/5988861/134908839-023da523-daf2-4246-ab9a-fc7d7621e7da.png">
