### ISSUE TITLE
"Leave Channel" button should not display for channel Owner

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#696]
Channel Owner was changed to this user, so button should not display.
**Screenshot Example** of channel changed owner

![all_channels_change_Group_Channel_2_owner_from_Lee_to_Lisa](https://user-images.githubusercontent.com/11938477/131539041-9206f38b-6767-4cb7-bcc5-5ac2bf7caeeb.png)

![leave_channel_button_should_not_display_for_channel_owner](https://user-images.githubusercontent.com/11938477/131538918-e481a2c7-0a7c-456c-b90b-7c0bc7e706e1.png)

________________________________________________________________________________________________________________________

**Screenshot Example** of channel with original owner

![leave_channel_button_does_not_dispay_for_channel_creator](https://user-images.githubusercontent.com/11938477/131538832-53c667b3-58f1-46b0-b05e-3ca29be8ae3c.png)

**Comment by b-solution** [comment]
<img width="1201" alt="Screenshot 2021-09-01 at 6 01 34 PM" src="https://user-images.githubusercontent.com/5988861/131675825-037dab6b-54cd-4a0f-a3f0-368bf45282cc.png">

<img width="1205" alt="Screenshot 2021-09-01 at 6 02 04 PM" src="https://user-images.githubusercontent.com/5988861/131675869-ff7fe5d6-1270-4fc1-957b-d9b7299b9582.png">
