### ISSUE TITLE
When checkmark clicked on Notification modal, duplicate label should not display on Notifications button.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#697]
Screenshot Example of Notification that user Left Channel

![click_notifications_click_ok](https://user-images.githubusercontent.com/11938477/131543323-8b3f71f3-532b-4407-a97b-0e1c77d1408d.png)

![notifications_duplicate_displays_after_ok_click](https://user-images.githubusercontent.com/11938477/131543418-3d5f39e6-efe9-412f-a1d4-9a1cfda4c9ff.png)

**Comment by b-solution** [comment]
<img width="1223" alt="Screenshot 2021-09-02 at 2 56 40 AM" src="https://user-images.githubusercontent.com/5988861/131751407-ae529bde-f086-486f-be1a-777eb5001387.png">

<img width="1208" alt="Screenshot 2021-09-02 at 2 56 59 AM" src="https://user-images.githubusercontent.com/5988861/131751457-7d012163-a9d3-49d0-8859-3078d569a543.png">
