### ISSUE TITLE
When group channel owner is changed, the prior owner should not automatically have their permissions removed.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#698]
The prior group channel owner should have the same permissions displayed on the table, with Edit and Delete icons.

**Comment by b-solution** [comment]
<img width="1191" alt="Screenshot 2021-09-02 at 7 41 53 PM" src="https://user-images.githubusercontent.com/5988861/131865492-671bd9bb-0e3d-46c7-8032-34d6ee2dbbe3.png">

<img width="1196" alt="Screenshot 2021-09-02 at 7 43 26 PM" src="https://user-images.githubusercontent.com/5988861/131865538-e4e81673-93e1-4a15-8949-60dcc412536d.png">

<img width="1194" alt="Screenshot 2021-09-02 at 7 43 40 PM" src="https://user-images.githubusercontent.com/5988861/131865569-2be33f1a-14d6-44d8-9949-4e9b55e52f5c.png">
