### ISSUE TITLE
"Notifications" button should display for user with Can Add/Change Permissions

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#699]
User with permissions should be able to Accept/Reject Request to join Group Channel, and be aware of user that has Left Channel.
Screenshot Example

![non-channel_owner_with_can_add_change_permissions](https://user-images.githubusercontent.com/11938477/131557935-3ad03357-c4d8-4416-8c5d-3a0ad5983b12.png)

![non-channel_owner_with_can_add_change_permissions_display_Notifications_button](https://user-images.githubusercontent.com/11938477/131557963-e939661b-aaec-48a5-87e9-a4c0984c1056.png)

**Comment by b-solution** [comment]
<img width="1195" alt="Screenshot 2021-09-02 at 3 02 24 AM" src="https://user-images.githubusercontent.com/5988861/131751522-08b5d491-3373-4467-ac0a-97506c69f4db.png">

<img width="1211" alt="Screenshot 2021-09-02 at 3 01 45 AM" src="https://user-images.githubusercontent.com/5988861/131751547-40f2327d-c96b-4aaa-b9dd-311b2dd6734d.png">
