### ISSUE TITLE
there is no way to assign permissions to channels or reports in the channel

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#7]
read, write, update, delete

**Comment by bilel-kedidi** [comment]
there is on the role page ( role can read, write...)
what i've done is this
there is 3 type of channel(public, where all user can view it/read adn write)
non public and then i should add my own users to view all reports there
personal ( private where i can only share report

**Comment by bluenevus** [comment]
Looking to assign permissions per channel per report channel group
