### ISSUE TITLE
Should display Confirm modal when "Save" clicked on Permissions modal with Can View Channel "OFF".

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#700]
Add/Edit Permission modal.
Screenshot Example

![permissions_save_clicked_without_Can_View_Channel_ON](https://user-images.githubusercontent.com/11938477/131566566-e18f44f5-63fb-4503-922b-3a26262970be.png)

![permissions_save_clicked_without_Can_View_Channel_ON_Confirm_displays](https://user-images.githubusercontent.com/11938477/131567057-d947ffa8-c4dc-43d0-844c-38e6fedce535.png)

**Comment by b-solution** [comment]
<img width="454" alt="Screenshot 2021-09-01 at 3 21 58 PM" src="https://user-images.githubusercontent.com/5988861/131655438-751f17c0-135c-444d-a4db-f6f4991f8ad0.png">

**Comment by LAlexMHllc** [comment]
Add Permissions modal - DONE


Edit Permission modal - STILL NEEDS TO BE FIXED

Screenshot Example

![edit_permissions_can_view_channel_off_click_save](https://user-images.githubusercontent.com/11938477/131879392-ed636da5-1c9b-433e-acba-5f97697fb96c.png)


![permissions_save_clicked_without_Can_View_Channel_ON_Confirm_displays](https://user-images.githubusercontent.com/11938477/131567057-d947ffa8-c4dc-43d0-844c-38e6fedce535.png)

**Comment by b-solution** [comment]
<img width="1204" alt="Screenshot 2021-09-07 at 2 30 14 PM" src="https://user-images.githubusercontent.com/5988861/132321645-4e179575-5224-4c71-966f-1fd45bbcdd87.png">

<img width="462" alt="Screenshot 2021-09-07 at 2 30 26 PM" src="https://user-images.githubusercontent.com/5988861/132321699-39b20bf3-581b-468f-93a7-6eb48688d66a.png">

**Comment by LAlexMHllc** [comment]
After updates, tests failed for both Add Permission and Edit Permission

Screenshot Example

![channel_permissions_save_clicked_without_can_view_channel](https://user-images.githubusercontent.com/11938477/132361016-d653f17f-db15-487d-be99-631e054b7915.png)

![channel_permissions_successful_save_without_can_view_channel_success](https://user-images.githubusercontent.com/11938477/132361460-96fef822-970b-4a6b-bb37-0b58475cd051.png)

![channel_permissions_edit_save_clicked_without_can_view_channel](https://user-images.githubusercontent.com/11938477/132362128-4f260486-6c6c-46c0-b9d7-41063fb403a2.png)

![channel_permissions_successful_save_without_can_view_channel_success](https://user-images.githubusercontent.com/11938477/132361460-96fef822-970b-4a6b-bb37-0b58475cd051.png)

**Comment by b-solution** [comment]
@LAlexMHllc  Can you please look into it again.

**Comment by LAlexMHllc** [comment]
Closing, fixed
