### ISSUE TITLE
right side of the header isn't lined up with the right side of the login box.  

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#709]
![image](https://user-images.githubusercontent.com/3675043/131931707-1a8aa087-08e2-4531-b331-74d0d2aa2fe3.png)

**Comment by bluenevus** [comment]
its a little bit smaller so when you look at the shadows, you can see that its in a little bit and the sign in box sticks out a little bit

**Comment by b-solution** [comment]
<img width="1359" alt="Screenshot 2021-09-07 at 3 38 39 PM" src="https://user-images.githubusercontent.com/5988861/132331250-10beb4ad-c2f8-488a-a2d3-2cd171bfcd04.png">
