### ISSUE TITLE
add support for json and xml

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#71]
pivottables say they support json and xml

https://pivottable.js.org/examples/mps.html
https://github.com/nicolaskruchten/pivottable/issues/274

while its less likely people will download a json and xml then upload I would like to support that.  More importantly, connecting to a web resource URL, they can connect and pull that data from that resource from url which is more likely in terms of json and xml vs csv and excel

for example connecting to these resources here https://catalog.data.gov/dataset?_organization_limit=0&organization=hhs-gov#topic=health_navigation

by url then being able to get that data and pivot it and of course refresh the data from the source

**Comment by bilel-kedidi** [comment]
i did it, you have to upload JSON file
