### ISSUE TITLE
the header image shouldn't have any padding and should fill the space of the content area

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#710]
![image](https://user-images.githubusercontent.com/3675043/131931775-9bb6c09a-84d5-40ae-98ca-182de914bcec.png)

**Comment by b-solution** [comment]
<img width="685" alt="Screenshot 2021-09-07 at 4 12 33 PM" src="https://user-images.githubusercontent.com/5988861/132338245-77d14355-172e-4894-951d-12504c71eb87.png">
