### ISSUE TITLE
Group Channel owner clicked Permissions button and an error screen displayed.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#715]
Screenshot Example

![lisa_group_channel_click_permissions](https://user-images.githubusercontent.com/11938477/132365017-ae85c31e-f827-4169-8df5-6ae6eb8ea1df.png)

![channel_permissions_screen_error_after_user_permission_saved_without_grants](https://user-images.githubusercontent.com/11938477/132365081-893b6802-ee8a-44e9-9772-4d822a4bd64b.png)

**Comment by b-solution** [comment]
@LAlexMHllc Can you please checkout again?

**Comment by LAlexMHllc** [comment]
Closing, fixed
