### ISSUE TITLE
Connect With Dashboards: Clicking "backspace" when Search box is empty should not remove last selected

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#718]
Screenshot Example

![connect_to_dashboard_search_box](https://user-images.githubusercontent.com/11938477/132569530-0208577c-d03d-4908-987b-2c5f24b829f9.png)

![connect_to_dashboard_search_box_backspace_when_empty_removed_last_selected](https://user-images.githubusercontent.com/11938477/132569439-3405f8bd-bbb8-4618-a4e7-b3cda4c4ff21.png)

**Comment by b-solution** [comment]
<img width="1199" alt="Screenshot 2021-09-09 at 4 47 56 PM" src="https://user-images.githubusercontent.com/5988861/132680447-1b920536-2da2-4bd1-804b-32549aaff3e0.png">
