### ISSUE TITLE
Share Report: Clicking "backspace" when Search box is empty should not remove last selected

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#720]
Screenshot Example

![share_report_search_box](https://user-images.githubusercontent.com/11938477/132698474-0eba8708-cf72-4cdd-bfdf-dcdaf2ecdb68.png)

![share_report_search_box_backspace_when_empty_removed_last_selected](https://user-images.githubusercontent.com/11938477/132698489-0d5718ab-c8b3-4abf-a54d-b0cab220038b.png)

**Comment by b-solution** [comment]
Already fixed in https://github.com/MicroHealthLLC/mRMS/pull/719


<img width="1189" alt="Screenshot 2021-09-10 at 2 20 03 PM" src="https://user-images.githubusercontent.com/5988861/132831644-6c75faed-965e-4b39-8c21-bfc53eb3f33e.png">
