### ISSUE TITLE
Data Sets are missing from Personal channel when owner is changed without Shared Reports

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#721]
Screenshot Example of Personal Channel

![admin_personal_testing123](https://user-images.githubusercontent.com/11938477/132706332-43080306-d08e-42e4-a128-994ab3a63551.png)

Screenshot Example of All Channels - Change Personal channel Owner

![all_channels_change_testing123_from_Admin_to_LA](https://user-images.githubusercontent.com/11938477/132706499-8f33a9e0-a048-4132-b4e7-5bee63bf4d80.png)

Screenshot Example of new folder under Personal channel for new owner
NOTE: Data Sets are missing because the previous owner did not Share Report

![testing123_missing_Data_Sets_LA_newOwner](https://user-images.githubusercontent.com/11938477/132707668-15b6ee06-30ee-4e3f-b03f-3444e685dc0c.png)

If Multi Data Set Dashboards were created, then new owner can view reports on dashboard
Screenshot Example

![testing123_multi-data-set_reports_screen_LA_newOwner](https://user-images.githubusercontent.com/11938477/132706625-32bcfd2a-ae24-4d74-8dc7-1837faa3e41d.png)

New owner can access the report(s) by clicking a report on the dashboard
Screenshot Example

![testing123_LA_newOwner_report_screen_after_multi-datashboard_report_click](https://user-images.githubusercontent.com/11938477/132710324-bb475d3b-4193-4bfb-b0c4-e9924517a8db.png)

**Comment by LAlexMHllc** [comment]
When a report is shared by the new owner before the Personal channel owner is changed, then the Data Set will display on the channel after channel owner is changed.
Screenshot Example of Shared Report before channel owner change

![testing123_report_shared_before_changeOwner](https://user-images.githubusercontent.com/11938477/132711365-73d889e3-f1f9-4997-9027-0adb1640df87.png)

Screenshot Example of Personal Channel with Data Set that had shared report before channel owner change displays; and missing the one that was not shared prior to change

![testing123_with_previously_shared_Data_Sets_LA_newOwner](https://user-images.githubusercontent.com/11938477/132712111-5843a965-b0be-4b75-be03-c16857e6d45b.png)

**Comment by b-solution** [comment]
<img width="1424" alt="Screenshot 2021-09-16 at 4 54 09 PM" src="https://user-images.githubusercontent.com/5988861/133608169-bbc7386e-2844-4453-8699-45e3fc75df3c.png">
