### ISSUE TITLE
Plotly chart on Multi Data Set Dashboard should display action icons like report 

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#723]
Screenshot Example

![plotly_action_icons_multidashboard_should_display_like_report](https://user-images.githubusercontent.com/11938477/133323628-eab9c511-2d94-4c1b-9be6-ba6e4fbdb0b3.png)

**Comment by b-solution** [comment]
<img width="1205" alt="Screenshot 2021-09-16 at 2 59 31 PM" src="https://user-images.githubusercontent.com/5988861/133592771-e4b2286c-d508-443e-bb04-43d5c5cfa288.png">
