### ISSUE TITLE
multidataset dashboards don't match the report

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#729]
if you recall this was fixed in the past where the report displayed properly then in multidataset it displayed the same report selected improperly.  This issue returned in the last update where the report chosen doesn't look like the same report and displays incorrectly with incorrect charts in the multidataset ddashboard

**Comment by LAlexMHllc** [comment]
Screenshot Example of Report on Multi Data Set dashboard displaying incorrectly

![multidataset_dashboard_report_displays_incorrectly](https://user-images.githubusercontent.com/11938477/134360573-67af5c27-24ab-4e51-b131-12c9af2164ca.png)

Screenshot Example of how the report should display

![multidataset_dashboard_report_displays_incorrectly_2](https://user-images.githubusercontent.com/11938477/134360680-fb02d277-a983-472e-b5c4-5df25a7f1039.png)

**Comment by b-solution** [comment]
<img width="1179" alt="Screenshot 2021-09-23 at 3 16 14 PM" src="https://user-images.githubusercontent.com/5988861/134490764-abcd31e7-e3c6-49db-a925-7bfb963dc22a.png">

<img width="675" alt="Screenshot 2021-09-23 at 3 16 23 PM" src="https://user-images.githubusercontent.com/5988861/134490789-7b2ecf45-9881-48c0-8680-5b6a1d4cb65b.png">
