### ISSUE TITLE
Report missing field selectors

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#730]
Screenshot Example

![onedrive_file_reuploaded_report_missing_field_selectors](https://user-images.githubusercontent.com/11938477/134369105-93570413-111e-437a-a58d-bc61d7b9e1a4.png)

![report_missing_field_selectors](https://user-images.githubusercontent.com/11938477/134364530-7abdd10d-6690-4aef-8a33-07ca084980b0.png)

Screenshot Example of Report displayed correctly on Multi Data Set Dashboard

![multidataset_dashboard_report_display_does_match_report](https://user-images.githubusercontent.com/11938477/134368801-fc86a1df-f63d-4330-85f1-0e0527335c3d.png)

NOTE: Even after file re uploaded from onedrive it still displayed incorrectly on Report

**Comment by bluenevus** [comment]
issue with the data uploaded
