### ISSUE TITLE
as a user, when I click refresh the data, I shouldn't have to reupload to reauthorize

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#731]
when I clicked refresh for data I shouldn't have to re-upload.  Instead, I should simply be reauthorizing the token that expired

1. I uploaded the data from my onedrive yesterday
2. The next day I clicked refresh
3. it told me that i needed to reupload the data when I should only have to reauthorize and reauthenticate NOT reuplad or have to select the file because I already did that the first time I uploaded the info from onedrive

![image](https://user-images.githubusercontent.com/3675043/134369749-014f1732-3fed-467e-a706-23046a871a78.png)

**Comment by b-solution** [comment]
@bluenevus Can you please test it again I have just fixed it. I have covered multiple scenarios i-e:
1. If file deleted from one drive It'll show the error, and tell you to re-upload file.
2. if access token expire it will refresh it automatically with the use or OneDrive refresh token.
3. if refresh token also expire then then it will ask to re authenticate one drive account.

You can test it and let me know what you think of above.

**Comment by LAlexMHllc** [comment]
Not able to Refresh Data
Screenshot Example

![connected_to_onedrive_refresh_data_fail](https://user-images.githubusercontent.com/11938477/134697565-83ca2bf6-f154-4989-b3c6-25cfcf60e07a.png)

**Comment by LAlexMHllc** [comment]
Still did not work after Re-Authenticated! message displayed.
Screenshot Example

![click_refresh_data_set_after_re_authenticated_message_displayed](https://user-images.githubusercontent.com/11938477/134699818-418d9564-3efe-465d-96fc-f6e0e3435eaf.png)

**Comment by b-solution** [comment]
<img width="1377" alt="Screenshot 2021-09-27 at 3 31 08 PM" src="https://user-images.githubusercontent.com/5988861/134892449-11b08c52-acd8-47df-9c51-39659614b2a3.png">

@LAlexMHllc @bluenevus   Please add these callback urls to your azure registered app. Then try again.

**Comment by bluenevus** [comment]
the setting above was always in azure...its how we were able to authenticate in the first place.  the problem was that app asks us to reupload instead of asking reauthentiction

**Comment by LAlexMHllc** [comment]
Now, after failed attempt to Refresh Data Set, an error message displayed on the report screen.
Screenshot Example of error message

![click_personal_report_with_onedrive_data_error_message_displayed](https://user-images.githubusercontent.com/11938477/134937703-132e3c8f-cde4-4614-851d-ffbaf4634b98.png)

**Comment by b-solution** [comment]
https://github.com/MicroHealthLLC/mRMS/issues/731#issuecomment-926700348

In above comment it is clearly stated that the URL specified in the request does not match the reply URLs configure for the application. So, please confirm that both urls (Stated below) must be present in the Azure application.

1. #{base_url}/auth/microsoft_graph_auth/callback
2. #{base_url}/welcome/onedriveredirect

if both URLs are in the app and the auth process not work then please share the Logs, So that I'll figure out the exact Issue.

**Comment by bluenevus** [comment]
yep I had them.  its why we were able to upload onedrive in the first place.  just couldn't refresh.  With that said because there were 2 key fields.  One for office 365 and one for azure, I created an azure connect for onedrive and a separate for login.  So what I did this time was create One single entry that has both onedrive and login with the 2 call back urls then updated the keys so that both uses the same entry and testing now.  we have to wait until it times out on the refresh to see if it works.  because in both cases, we could always upload and could always refresh immediately.  the problem happened when the onedrive authentication timed out and had to reauthenticate.  Instead of reauthenticate, it was asking to reupload so I'll wait a day for the onedrive token to expire, click refresh and see if it simply asks me to reauthenticate.  if it works, then we will know you have to have ONE azure entry with both callback urls then enter the same key for office 365 and the same one for azure.  If that is the case, it would make better sense in settings to combine the office 365 and azure key so admins don't make this mistake.  I assumed that because there were 2 entries, it expected 2 different keys so I created one specific for logins with the proper callback and one specific for onedrive with the proper callback and could always upload and refresh immediately.  just couldn't refresh when the token expires without reuploading vs just reauthenticating.
