### ISSUE TITLE
"System Error contact to Admin!" message sometimes displays on various screens.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#738]
Screenshot Example on Report screen

![click_personal_report_with_onedrive_data_error_message_displayed](https://user-images.githubusercontent.com/11938477/135101626-784cfb4f-6ecd-4b9d-aa7b-296aa7c476ed.png)

Screenshot Example on All Channels screen

![system_error_contact_admin_message_all_channels_screen](https://user-images.githubusercontent.com/11938477/135101152-eb0c4d73-1e22-43e9-ae5f-218c8bb3fa12.png)

**Comment by bluenevus** [comment]
can you refresh your onedrive?  like reupload and see if it works?  I changed the authentication and that might have caused it

**Comment by bluenevus** [comment]
I don't have any of these errors
