### ISSUE TITLE
User with Can View Channel permission should be able to view channel

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#739]
Screenshot Example of User permissions

![group_permissions_can_view_channel__can_view_report__can_download](https://user-images.githubusercontent.com/11938477/135122048-49117a79-8e5b-414d-8d26-a1ba63c632d9.png)

Screenshot Example of Not Authorized screen

![user_not_authorized_screen_yet_can_view_channel](https://user-images.githubusercontent.com/11938477/135122067-e102ba9b-7562-4101-8a37-f32733bd5b5c.png)

**Comment by LAlexMHllc** [comment]
NOTE: User was able to view channel when Can Add/Edit Report permission was included
Screenshot Example

![group_permissions_can_view_channel__can_view_add_edit_report__can_download](https://user-images.githubusercontent.com/11938477/135123658-6b9ad2a0-4d34-4fe9-a456-b935770a9e11.png)

**Comment by b-solution** [comment]
<img width="1417" alt="Screenshot 2021-10-01 at 6 59 09 PM" src="https://user-images.githubusercontent.com/5988861/135632755-1793e158-3c56-4c94-a378-39dae96a7a5a.png">

<img width="1435" alt="Screenshot 2021-10-01 at 6 59 00 PM" src="https://user-images.githubusercontent.com/5988861/135632831-c557ea50-93ea-4c76-9e97-c09d9b8e8458.png">
