### ISSUE TITLE
unable to migrate db

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#741]
![image](https://user-images.githubusercontent.com/3675043/135269184-5f9f2284-1836-40be-871e-538c63039272.png)

**Comment by bluenevus** [comment]
![image](https://user-images.githubusercontent.com/3675043/135279495-55efc649-adfe-4480-aac3-b3cd3d74cfbd.png)

**Comment by bluenevus** [comment]
still unable to migrate with the new pull

**Comment by bluenevus** [comment]
![image](https://user-images.githubusercontent.com/3675043/135279729-c4c240e3-2583-4b03-a276-4adc18f16dd4.png)

**Comment by b-solution** [comment]
@bluenevus Can you please check one more time, it will work now. Thanks!
