### ISSUE TITLE
refresh onedrive still does not work though upload always does

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#744]
azure is configured the way you mention with both redirect urls
![image](https://user-images.githubusercontent.com/3675043/135326026-1d1a062c-e856-4013-a358-5e6fe5aff151.png)

the application in the settings has the api keys in both the azure section and the office 365 section in the same place

you can always upload files without an issue and it properly authenticates demonstrating the keys and redirect is correct in settings in azure and the app

when you click refresh after upload will work

After you wait until your token expires like 6 hours then click refresh on the same data you uploaded and worked then clicked refresh when your token was still active and worked you get an error that the reply url doesn't match the url configured once your token expired

**Comment by bluenevus** [comment]
it didn't work when it was separated with one specific or onedrive and one for o365 with different keys one for each and one entry in azure one for each.  it did the same exact thing when I combined them into the same entry and it only happens on refresh and ONLY when the token times out

**Comment by b-solution** [comment]
@bluenevus below url not involve in the screenshot you provided above. Please add this one too in the app URLs.
#{base_url}/auth/microsoft_graph_auth/callback
