### ISSUE TITLE
Refresh Data Set button should not display for user without permission

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#748]
Screenshot Example of user permissions

![user_permissions](https://user-images.githubusercontent.com/11938477/135676950-397d3680-b306-4941-8fec-84cfb721af04.png)

Screenshot Example of Refresh Data Set button

![user_permissions_test_1A](https://user-images.githubusercontent.com/11938477/135677063-45694118-8ee2-463b-b6ad-a7fcdabdd724.png)

**Comment by b-solution** [comment]
@LAlexMHllc  I'm using Can Add/Edit Report permission for refresh dataset.

**Comment by b-solution** [comment]
Before:
<img width="1145" alt="Screenshot 2021-10-06 at 8 10 31 AM" src="https://user-images.githubusercontent.com/5988861/136134912-37d41799-21b0-45e8-9d11-8b7365097660.png">

<img width="1197" alt="Screenshot 2021-10-06 at 8 10 59 AM" src="https://user-images.githubusercontent.com/5988861/136134926-6ddbec1d-0583-4e45-ab62-7b6485627cae.png">

After:
<img width="1154" alt="Screenshot 2021-10-06 at 8 11 19 AM" src="https://user-images.githubusercontent.com/5988861/136134941-3a13e9ad-a620-4aba-bb88-e24b659e026a.png">

<img width="1193" alt="Screenshot 2021-10-06 at 8 11 35 AM" src="https://user-images.githubusercontent.com/5988861/136134953-00571444-2791-4ce2-b114-3c93ec2e8519.png">
