### ISSUE TITLE
Non-owner of Shared Report should be able to view Dashboard

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#758]
Screenshot Example of clicking dashboard card on Shared Report for non-owner

![non-owner_clicked_dashboard_card_on_shared_report_channel](https://user-images.githubusercontent.com/11938477/138900341-e830bef4-4c69-47ff-bd82-1b7d0530ccb8.png)

Screenshot Example of Not Authorized screen

![non-owner_clicked_dashboard_card_on_shared_report_channel__not_authorized_screen](https://user-images.githubusercontent.com/11938477/138900142-ebae9c36-b351-4983-932b-76e5a3af7998.png)

**Comment by LAlexMHllc** [comment]
NOTE: The Not Authorized screen displays because the Dashboard link includes the owner Channel # instead of the Shared Report #.
URL should be https://rmsqa.microhealthllc.com/channels/13/reports/17/dashboards/26

Screenshot Example

![non-owner_clicked_dashboard_card_on_shared_report_channel__with_correct_URL](https://user-images.githubusercontent.com/11938477/139697051-17270944-87a4-4595-a4a6-1c34cbbe4c4a.png)

**Comment by b-solution** [comment]
<img width="1408" alt="Screenshot 2021-11-10 at 3 52 36 PM" src="https://user-images.githubusercontent.com/5988861/141100284-56bfd374-0d87-4043-b3fb-84bc34f6a29a.png">

Shared reports dashboard open on click.
