### ISSUE TITLE
"Update by" should display the name of the user that last updated the info with the corresponding date.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#765]
This is happening on Data Sets and Reports

Screenshot Example with different Update by info for different users on same screen
NOTE: Info was not updated by either user

![Lisa_Shared_Report_Update_by_user_date](https://user-images.githubusercontent.com/11938477/139303432-27507b6f-2c1c-4768-b66b-377a5ddf2a2e.png)

![LeeAlex_Shared_Report_Update_by_user_date](https://user-images.githubusercontent.com/11938477/139303450-236c92ad-3594-4611-b428-cb38f951d89e.png)

**Comment by b-solution** [comment]
<img width="1205" alt="Screenshot 2021-11-10 at 4 19 00 PM" src="https://user-images.githubusercontent.com/5988861/141104013-a118e582-7f87-48ee-8f7c-fc97bdc87ffd.png">

**Comment by LAlexMHllc** [comment]
Fixed for Data Set, but not Report.
Currently, when Data Set is updated, all its reports update to the same time as Update Data Set Time.
When user clicks Save on Update Report form, the current date/time should display for that report.

Screenshot Example

![Update_Report_should_update_to_current_date-time](https://user-images.githubusercontent.com/11938477/141155118-be2ae0d4-5c4b-4117-8993-5efde5d8bc6e.png)

**Comment by b-solution** [comment]
<img width="1415" alt="Screenshot 2021-11-18 at 7 58 45 PM" src="https://user-images.githubusercontent.com/5988861/142442123-006a2174-ae27-473a-b814-b50634047ac9.png">

<img width="654" alt="Screenshot 2021-11-18 at 7 59 11 PM" src="https://user-images.githubusercontent.com/5988861/142442155-9d1fa5d4-bf26-41ed-86cb-232a38afd4e4.png">

<img width="1423" alt="Screenshot 2021-11-18 at 7 59 25 PM" src="https://user-images.githubusercontent.com/5988861/142442165-7434651d-d7a1-4474-b76a-450724758b38.png">
