### ISSUE TITLE
User should be able to Add Multi Data Set Dashboard on their Shared Reports channel

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#769]
Screenshot Example

![user_should_be_able_add_multi-data-set-dashboard_on_their_Shared_Reports_channel](https://user-images.githubusercontent.com/11938477/139317616-6e3f3d5c-d1db-4eac-96e1-d3b365d30a0e.png)

**Comment by b-solution** [comment]
<img width="1205" alt="Screenshot 2021-11-16 at 2 21 27 PM" src="https://user-images.githubusercontent.com/5988861/141957969-9704f281-3a04-40d3-b356-47866637e0c1.png">
