### ISSUE TITLE
Should include permission "Can Delete Report"

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#772]
Screenshot Example

![include_permission_Can_Delete_Report](https://user-images.githubusercontent.com/11938477/139456337-a48d7ea1-e292-4889-8da8-f443c69cef0a.png)

![include_permission_Can_Delete_Report_on_table](https://user-images.githubusercontent.com/11938477/139459278-2e94b311-61db-40d0-8980-e48d597ced65.png)

**Comment by b-solution** [comment]
When user did not have permission to 'Can Delete Report':
<img width="1199" alt="Screenshot 2021-11-10 at 6 10 24 PM" src="https://user-images.githubusercontent.com/5988861/141119366-31834ed3-65ab-4e7b-8a79-fc8113b66f31.png">

<img width="1203" alt="Screenshot 2021-11-10 at 6 10 47 PM" src="https://user-images.githubusercontent.com/5988861/141119378-6b01000c-3583-4f95-8ddf-b3862c8430df.png">

When user has permission to 'Can Delete Report':

<img width="1205" alt="Screenshot 2021-11-10 at 6 11 10 PM" src="https://user-images.githubusercontent.com/5988861/141119381-211ecb80-5290-4f43-9780-fc71319f60ec.png">

<img width="1215" alt="Screenshot 2021-11-10 at 6 11 28 PM" src="https://user-images.githubusercontent.com/5988861/141119388-c10ccf9a-bc32-4f07-aaa5-c534a1848822.png">
