### ISSUE TITLE
User should not be able to Upload Data and Edit Data Set without "Can Add/Edit Data Set" permission

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#777]
Currently, user is given Can Add/Edit Data Set permission when "Can Add/Edit Report" permission is ON.
NOTE: "Can Add/Edit Data Set" permission will be used for this instead (see Issue #771).

Screenshot Example

![LeeAlex_group_channel_permissions_2](https://user-images.githubusercontent.com/11938477/139479414-f4bc2bff-69b3-4e3b-bbc9-f1bc5ef8afd9.png)

Screenshot Example

![user_should_not_be_able_upload_data_edit_data_set_without_can_add_edit_data_set_permission](https://user-images.githubusercontent.com/11938477/139487127-e99649c9-d340-41eb-902c-25a9bc119d11.png)

**Comment by bluenevus** [comment]
I'm a bit confused by this.  A user can edit a report which is different than the data set.  Seems like 2 separate permissions than one

**Comment by b-solution** [comment]
When user did not have permission 'Can Add/Edit Data Set'
<img width="1208" alt="Screenshot 2021-11-16 at 2 59 00 PM" src="https://user-images.githubusercontent.com/5988861/141964450-ef6e47b7-82a3-4fb1-baa0-d14f009f0f9c.png">

<img width="1205" alt="Screenshot 2021-11-16 at 2 59 27 PM" src="https://user-images.githubusercontent.com/5988861/141964476-e1f59924-96c4-4ccd-baa0-39e448a3402a.png">

When user has permission 'Can Add/Edit Data Set'
<img width="1197" alt="Screenshot 2021-11-16 at 2 57 41 PM" src="https://user-images.githubusercontent.com/5988861/141964517-93b0d81c-ce9c-4a7a-a36b-036f0c3013de.png">

<img width="1201" alt="Screenshot 2021-11-16 at 2 58 24 PM" src="https://user-images.githubusercontent.com/5988861/141964539-6b3bd1c4-106a-4228-bfb0-9cde462a80b7.png">

**Comment by b-solution** [comment]
Yes, This permission module is getting complex by adding so much permission in it. We need to revisit the whole permission scenario.
