### ISSUE TITLE
User with "Can Manage Dashboard" permission should be able to Add New Dashboard

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#780]
Screenshot Example

![New_Dashboard_button_should_display_for_user_with_Can_Manage_Dashboard_permission](https://user-images.githubusercontent.com/11938477/139701541-e1a1fb9e-d3e7-476e-a44f-557b42fb89d0.png)

**Comment by LAlexMHllc** [comment]
NOTE: Currently, the "New Dashboard" button displays when the user has "Can Add/Edit Report" permission.

**Comment by b-solution** [comment]
When user did not have permission to 'Can manage dashboard':

<img width="1199" alt="Screenshot 2021-11-10 at 3 36 01 PM" src="https://user-images.githubusercontent.com/5988861/141098418-9d8dfe2a-bbee-4578-bd19-1df3792ce75b.png">

<img width="1212" alt="Screenshot 2021-11-10 at 3 36 24 PM" src="https://user-images.githubusercontent.com/5988861/141098425-b766555a-b312-4cf3-864a-2b6b53329f02.png">

When user has permission to 'Can manage dashboard':

<img width="1208" alt="Screenshot 2021-11-10 at 3 37 47 PM" src="https://user-images.githubusercontent.com/5988861/141098430-b33b9371-8a0d-4708-9d40-0de63b1302a4.png">

<img width="1206" alt="Screenshot 2021-11-10 at 3 38 08 PM" src="https://user-images.githubusercontent.com/5988861/141098435-88b74abb-3930-4f0f-abdb-b9c005b0eea2.png">
