### ISSUE TITLE
User with "Can Manage MultiDataSet Dashboard" permission should be able to Add New Multi Data Set Dashboard

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#781]
Screenshot Example

![New_Multi-Data-Set_Dashboard_button_should_display_for_user_with_Can_Manage_MultiDashboard_permission](https://user-images.githubusercontent.com/11938477/139705113-0df3f0b0-c680-42f7-be75-7f2e3b621521.png)

**Comment by LAlexMHllc** [comment]
NOTE: Button displays when user has both Can Share Report with Dashboard AND Can Manage MultiDataSet Dashboard permissions

**Comment by b-solution** [comment]
<img width="1200" alt="Screenshot 2021-11-10 at 3 17 47 PM" src="https://user-images.githubusercontent.com/5988861/141095582-cbd77921-1ed5-4a53-8a3e-8bbfe331181b.png">

<img width="1193" alt="Screenshot 2021-11-10 at 3 18 24 PM" src="https://user-images.githubusercontent.com/5988861/141095594-8ae87592-748a-4566-94e9-2eff0870f8b5.png">

<img width="1211" alt="Screenshot 2021-11-10 at 3 18 53 PM" src="https://user-images.githubusercontent.com/5988861/141095607-0e5d6657-9342-44a5-ae9d-2e75ad818e6a.png">
