### ISSUE TITLE
Public Channel: Any user should be able to Connect Report with Dashboard

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#787]
Screenshot Example

![public_channel_click_connect_with_dashboards](https://user-images.githubusercontent.com/11938477/140770423-c230033d-7cb7-42c4-8213-92287a99c5d2.png)

![public_channel_click_connect_with_dashboards_not_authorized](https://user-images.githubusercontent.com/11938477/140770445-853deca1-6d9a-45b6-9c1c-728a021b6be9.png)

**Comment by b-solution** [comment]
<img width="1414" alt="Screenshot 2021-11-18 at 7 52 55 PM" src="https://user-images.githubusercontent.com/5988861/142439009-e943e5a7-27c0-4a89-a31b-ad72c3fe4a99.png">

<img width="1415" alt="Screenshot 2021-11-18 at 7 53 23 PM" src="https://user-images.githubusercontent.com/5988861/142439040-9ae0fecc-212c-4636-871f-acacec708ca4.png">
