### ISSUE TITLE
Public Channel: Users should be granted all permissions on Data Sets, Reports, Dashboards, Multi Data Set Dashboards, and downloads.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#788]
All users should be able to Add Multi-Data-Set Dashboard, Add Data Set, and Update Category by drag 'n drop Data Set card
Screenshot Example

![add-data-set_dragNdrop-Data-Set-Category_add-multi-data-set-dashboard](https://user-images.githubusercontent.com/11938477/140958025-dd5d45ca-2cd1-4736-bae5-63db9eba762c.png)

All users should be able to Delete Multi-Data-Set Dashboard and Update Category by drag 'n drop Multi-Data-Set Dashboard card
Screenshot Example

![delete-multi-data-set-dasboard_dragNdrop-multi-data-set-dashboard-Category](https://user-images.githubusercontent.com/11938477/140958057-9edc5dc6-892f-4ba5-a6cf-fcb0cedd9d0e.png)

All users should be able to Add Report, Add Dashboard, Edit Data Set, Delete Data Set, Update Category by drag 'n drop Report card, and Download
Screenshot Example

![new-report_add-dashboard_upload-data_edit-delete-data-set_Update-dragNdrop-report_download](https://user-images.githubusercontent.com/11938477/140961283-d38e1c42-5f11-49fc-ba63-44ab207208e2.png)

All users should be able to Delete Dashboard and Update Category by drag 'n drop Dashboard card
Screenshot Example

![delete-dasboard_dragNdrop-dashboard-Category](https://user-images.githubusercontent.com/11938477/140961944-5957c474-8792-4860-8725-5fd769999672.png)

All users should be able to Connect Report with Dashboards, Update Report, and Export to Excel, Download
Screenshot Example

![connect-with-dashboard_update-report_export-to-excel](https://user-images.githubusercontent.com/11938477/140962960-f48cbd29-1f06-4bf8-b93f-23c144a41113.png)

**Comment by LAlexMHllc** [comment]
**NOTE**: Only public channel owner should have permission to Edit/Delete channel.
Screenshot Example

![only_public_channel_owner_permissions_edit_delete_channel](https://user-images.githubusercontent.com/11938477/140959808-87bcf612-7884-49fd-8f8e-a8057a0f8f5d.png)

**Comment by b-solution** [comment]
Public Channel: Users should be granted all permissions on Data Sets, Reports, Dashboards, Multi Data Set Dashboards, and downloads.

When Group Channel gets updated to Public Channel, ONLY the channel owner should be able to Edit/Delete Channel.

**Comment by LAlexMHllc** [comment]
All users should be able to Upload Data and Edit/Delete Data Set
Screenshot Example
![public_channel_all_users_able_upload_data_edit-delete_dataset](https://user-images.githubusercontent.com/11938477/142471865-ced42284-de8a-4ace-9e9a-4e946ecf123d.png)


All users should be able to Update Report
Screenshot Example
![public_channel_all_users_able_update_report](https://user-images.githubusercontent.com/11938477/142472296-eefc6c56-aa24-407f-9de0-a8fe79a22f04.png)

**Comment by b-solution** [comment]
<img width="1440" alt="Screenshot 2021-11-22 at 6 44 19 PM" src="https://user-images.githubusercontent.com/5988861/142872373-5e2e10b7-22ff-4916-90e6-7ef2a89a38c0.png">

<img width="1431" alt="Screenshot 2021-11-22 at 6 44 45 PM" src="https://user-images.githubusercontent.com/5988861/142872390-f30aa7cd-994a-468d-b69e-7bf6c2c448c4.png">
