### ISSUE TITLE
When Group Channel gets updated to Public Channel, ONLY the channel owner should be able to Edit/Delete Channel.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#789]
When group channel type is changed to Public, "Can Edit Channel" permission must be removed from all users, except the channel owner.
Screenshot Example of Group Channel permissions

![TEST-Group-to-Public_permissions](https://user-images.githubusercontent.com/11938477/140977065-24923eaa-fee2-4a94-831a-63587037db23.png)

Screenshot Example of Edit Channel to change type to Public

![TEST-Group-to-Public_form_change_type_to_Public](https://user-images.githubusercontent.com/11938477/140976681-1c08a972-a94f-4be1-b0c5-9e1da96b0521.png)

Screenshot Example of Edit button that should not display for channel non-owner

![group-channel-non-owner-has-Can-Edit-Channel-Perm__channel-type-now-Public__so-remove-Edit-Channel](https://user-images.githubusercontent.com/11938477/140976782-e8435518-342e-407b-a040-2b57b347ef63.png)

**Comment by b-solution** [comment]
@LAlexMHllc I think when the channel become public, we should ignore the group permission. because public channels did not associate with permissions.
What do you say about it?

**Comment by LAlexMHllc** [comment]
@b-solution  Yes, ignore group permissions. Just make sure that ONLY the public channel owner can Edit/Delete channel.

**Comment by b-solution** [comment]
<img width="1422" alt="Screenshot 2021-11-18 at 7 06 47 PM" src="https://user-images.githubusercontent.com/5988861/142430752-f2b2b122-badc-4a5a-8900-f2e5ddb15d54.png">

 ONLY the channel owner should be able to Edit/Delete Channel
