### ISSUE TITLE
change button order on report

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#79]
![image](https://user-images.githubusercontent.com/3675043/39139688-90e542e4-46f0-11e8-856b-b6e899156c51.png)

Save Report
Load Report
Upload Data
Edit
Delete
Cancel

**Comment by bluenevus** [comment]
button order has not changed
![screenshot 2018-04-23 at 5 03 26 pm](https://user-images.githubusercontent.com/3675043/39153141-488a0f7a-4718-11e8-9e71-3812e3e48a0b.png)

**Comment by bluenevus** [comment]
Save Report
Load Report
Upload Data
Edit
Delete
Cancel

**Comment by bluenevus** [comment]
should be the order
Save Report
Load Report
Upload Data
Edit
Delete
Cancel

**Comment by bilel-kedidi** [comment]
could you recheck, this s exactly the same order

**Comment by LAlexMHllc** [comment]
Edit button/function and Delete button/function should not have been removed. The buttons should have just been moved after the Upload Data button.

Example Screenshot

![report_action_buttons](https://user-images.githubusercontent.com/11938477/39434035-7369481c-4c65-11e8-8c5f-4dcd74d7dcd4.jpg)
