### ISSUE TITLE
Shared Report channel - Fix Report Name link on multi data set dashboard so clicking will display report with correct URL

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#800]
Screenshot Example of Shared Report - Multi Data Set Dashboard

![click_report_on_shared_report_channel_multi-data-set_screen](https://user-images.githubusercontent.com/11938477/142010397-cb64b9b1-58c8-4e6d-903d-63dc43fd2183.png)

Screenshot Example of error screen that displayed when Report Name was clicked

![click_report_on_shared_report_channel_multi-data-set_screen_error_screen](https://user-images.githubusercontent.com/11938477/142010534-cea111be-5fae-41cf-b2c5-86bf869a851b.png)

Screenshot Example of the shared report screen that should have displayed

![click_report_on_shared_report_channel_multi-data-set_screen_correct_URL](https://user-images.githubusercontent.com/11938477/142010781-bbcc9867-a23b-4a9b-ac62-4e41dd9559fd.png)

**Comment by b-solution** [comment]
<img width="1427" alt="Screenshot 2021-11-18 at 6 50 56 PM" src="https://user-images.githubusercontent.com/5988861/142428073-751ef82d-8563-4ad5-aa3f-1eb317631d8c.png">

<img width="1428" alt="Screenshot 2021-11-18 at 6 51 22 PM" src="https://user-images.githubusercontent.com/5988861/142428109-6b8602ca-9a66-4085-bdf1-5c78f8d74bbe.png">
