### ISSUE TITLE
User should be able to drag N drop Dashboard Card on Personal and Public channels, as well as with permission on Group channel.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#807]
Screenshot Example

![should_be_able_dragNdrop_dashboard_card_another_category](https://user-images.githubusercontent.com/11938477/142465165-ae3393ae-0f15-4654-83a9-79fcc9cea2a8.png)

**Comment by b-solution** [comment]
https://user-images.githubusercontent.com/5988861/145042500-05d07d4c-794f-4849-8329-54c758a1a415.mov
