### ISSUE TITLE
Add/Edit Permission forms: "Can View Channel" and "Can View Report" should never be set to 'OFF'

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#809]
Screenshot Example

![group_permissions_Can-View-Channel_and_Can-View-Report_should_never_be_set_to_OFF](https://user-images.githubusercontent.com/11938477/142883787-aa4fed07-62f4-4521-8218-dcbad0fab171.png)

**Comment by b-solution** [comment]
<img width="585" alt="Screenshot 2021-11-23 at 2 59 36 PM" src="https://user-images.githubusercontent.com/5988861/143004313-b7e170be-faad-4ee5-ae58-799635c29681.png">

<img width="546" alt="Screenshot 2021-11-23 at 2 59 57 PM" src="https://user-images.githubusercontent.com/5988861/143004331-d90809f6-2cb6-4ea8-abe2-b519888467ab.png">
