### ISSUE TITLE
Add/Edit Permission forms: "Can Add/Edit Report" should be 'ON' when "Can Add/Edit Data Set" is 'ON'

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#810]
Screenshot Example

![group_permissions_Can-Add-Edit-Report_should_be_ON_when_Can-Add-Edit-Data-Set_is_ON](https://user-images.githubusercontent.com/11938477/142890054-6722b319-202d-4074-b387-91e57adee1b4.png)

**Comment by b-solution** [comment]
![Uploading Screenshot 2021-11-23 at 3.10.52 PM.png…]()
