### ISSUE TITLE
Add/Edit Permission forms: "Can Delete Report" should be 'ON' when "Can Delete Data Set" is 'ON'

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#811]
Screenshot Example

![group_permissions_Can-Delete-Report_should_be_ON_when_Can-Delete-Data-Set_is_ON](https://user-images.githubusercontent.com/11938477/142890812-beb41ba2-aaed-4b07-9cda-c3f9747fa09f.png)

**Comment by b-solution** [comment]
<img width="531" alt="Screenshot 2021-11-23 at 3 21 24 PM" src="https://user-images.githubusercontent.com/5988861/143007606-15533be7-c6b2-4997-8431-ab7e6c002872.png">
