### ISSUE TITLE
Report should always display as chart instead of js/json text

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#820]
Screenshot Example on new Report displayed as text

![exploding_new_report](https://user-images.githubusercontent.com/11938477/154312714-5d7a9c6d-7c4d-4f5d-8416-b590eba96e65.png)

Screenshot Example of how new Report should display

![new_report_not-exploded](https://user-images.githubusercontent.com/11938477/154312863-981bf268-807e-4d69-acda-7b618bbec740.png)

Screenshot Example on existing Report displayed as text

![exploding_existing_report](https://user-images.githubusercontent.com/11938477/154312042-d36538af-2d2f-4fed-8ed4-bd936b45b981.png)

Screenshot Example on Dashboard with some charts displayed as text

![dashboard_with_exploding_charts](https://user-images.githubusercontent.com/11938477/154311402-10848113-e74c-43b6-8d85-9a559a1e176a.png)

**Comment by LAlexMHllc** [comment]
NOTE: See Issue #819 for the specific error that's causing this.

**Comment by bluenevus** [comment]
it turns out it was the firewall
